const POWERS_DATA = [
  { "name": "01. Absorb/Dissipate Energy", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "02. Accelerate Healing", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "03. Concentration", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "04. Contort/Escape", "category": "Control", "prereq": "3,6,9", "darkSide": false },
  { "name": "05. Control Disease", "category": "Control", "prereq": "2", "darkSide": false },
  { "name": "06. Control Pain", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "07. Detoxify Poison", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "08. Emptiness", "category": "Control", "prereq": "11", "darkSide": false },
  { "name": "09. Enhance Attribute", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "10. Force of Will", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "11. Hibernation Trance", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "12. Instinctive Astrogation", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "13. Rage", "category": "Control", "prereq": "11", "darkSide": true },
  { "name": "14. Reduce Injury", "category": "Control", "prereq": "6", "darkSide": false },
  { "name": "15. Remain Conscious", "category": "Control", "prereq": "6", "darkSide": false },
  { "name": "16. Remove Fatigue", "category": "Control", "prereq": "2,6", "darkSide": false },
  { "name": "17. Resist Stun", "category": "Control", "prereq": "", "darkSide": false },
  { "name": "18. Short-Term Memory Enhancement", "category": "Control", "prereq": "11", "darkSide": false },
  { "name": "19. Beast Languages", "category": "Sense", "prereq": "24,29,34,43", "darkSide": false },
  { "name": "20. Combat Sense", "category": "Sense", "prereq": "21,23,42", "darkSide": false },
  { "name": "21. Danger Sense", "category": "Sense", "prereq": "23,42", "darkSide": false },
  { "name": "22. Instinctive Astrogation (Sense Variation)", "category": "Sense", "prereq": "26", "darkSide": false },
  { "name": "23. Life Detection", "category": "Sense", "prereq": "", "darkSide": false },
  { "name": "24. Life Sense", "category": "Sense", "prereq": "23", "darkSide": false },
  { "name": "25. Life Web", "category": "Sense", "prereq": "23,24,30", "darkSide": false },
  { "name": "26. Magnify Senses", "category": "Sense", "prereq": "", "darkSide": false },
  { "name": "27. Postcognition", "category": "Sense", "prereq": "11,23,30", "darkSide": false },
  { "name": "28. Predict Natural Disaster", "category": "Sense", "prereq": "21,23,26,35", "darkSide": false },
  { "name": "29. Receptive Telepathy", "category": "Sense", "prereq": "23,24", "darkSide": false },
  { "name": "30. Sense Force", "category": "Sense", "prereq": "", "darkSide": false },
  { "name": "31. Sense Force Potential", "category": "Sense", "prereq": "23,24,29,30", "darkSide": false },
  { "name": "32. Sense Path", "category": "Sense", "prereq": "8,11", "darkSide": false },
  { "name": "33. Shift Sense", "category": "Sense", "prereq": "26", "darkSide": false },
  { "name": "34. Translation", "category": "Sense", "prereq": "24,29,43", "darkSide": false },
  { "name": "35. Weather Sense", "category": "Sense", "prereq": "", "darkSide": false },
  { "name": "36. Bolt of Hatred", "category": "Alter", "prereq": "", "darkSide": true },
  { "name": "37. Dark Side Web", "category": "Alter", "prereq": "", "darkSide": true },
  { "name": "38. Injure/Kill", "category": "Alter", "prereq": "23,24", "darkSide": true },
  { "name": "39. Telekinesis", "category": "Alter", "prereq": "", "darkSide": false },
  { "name": "40. Farseeing", "category": "Control+Sense", "prereq": "24", "darkSide": false },
  { "name": "41. Life Bond", "category": "Control+Sense", "prereq": "23,24,26,29", "darkSide": false },
  { "name": "42. Lightsaber Combat", "category": "Control+Sense", "prereq": "", "darkSide": false },
  { "name": "43. Projective Telepathy", "category": "Control+Sense", "prereq": "23,24,29", "darkSide": false },
  { "name": "44. Accelerate Another's Healing", "category": "Control+Alter", "prereq": "6,47", "darkSide": false },
  { "name": "45. Aura of Uneasiness", "category": "Control+Alter", "prereq": "", "darkSide": true },
  { "name": "46. Control Another's Disease", "category": "Control+Alter", "prereq": "2,5", "darkSide": false },
  { "name": "47. Control Another's Pain", "category": "Control+Alter", "prereq": "6", "darkSide": false },
  { "name": "48. Control Breathing", "category": "Control+Alter", "prereq": "3,11,39", "darkSide": false },
  { "name": "49. Detoxify Poison in Another", "category": "Control+Alter", "prereq": "2,6,7,44,47", "darkSide": false },
  { "name": "50. Electronic Manipulation", "category": "Control+Alter", "prereq": "1,62", "darkSide": true },
  { "name": "51. Feed on Dark Side", "category": "Control+Alter", "prereq": "30", "darkSide": true },
  { "name": "52. Force Lightning", "category": "Control+Alter", "prereq": "1,38,53", "darkSide": false },
  { "name": "53. Inflict Pain", "category": "Control+Alter", "prereq": "6,24", "darkSide": false },
  { "name": "54. Place Another in Hibernation Trance", "category": "Control+Alter", "prereq": "11", "darkSide": false },
  { "name": "55. Remove Another's Fatigue", "category": "Control+Alter", "prereq": "2,6,16,44,47", "darkSide": false },
  { "name": "56. Return Another to Consciousness", "category": "Control+Alter", "prereq": "6,15", "darkSide": false },
  { "name": "57. Transfer Force", "category": "Control+Alter", "prereq": "6,47", "darkSide": false },
  { "name": "58. Waves of Darkness", "category": "Control+Alter", "prereq": "", "darkSide": true },
  { "name": "59. Dim Other's Senses", "category": "Sense+Alter", "prereq": "", "darkSide": false },
  { "name": "60. Lesser Force Shield", "category": "Sense+Alter", "prereq": "1,3,26,39", "darkSide": false },
  { "name": "61. Force Wind", "category": "Sense+Alter", "prereq": "26,33,39", "darkSide": false },
  { "name": "62. Affect Mind", "category": "Control+Sense+Alter", "prereq": "", "darkSide": false },
  { "name": "63. Battle Meditation", "category": "Control+Sense+Alter", "prereq": "", "darkSide": false },
  { "name": "64. Control Mind", "category": "Control+Sense+Alter", "prereq": "DS 29,39,62", "darkSide": false },
  { "name": "65. Create Force Storms", "category": "Control+Sense+Alter", "prereq": "DS 11,12,13,23,24,26,29,30,39,40,43", "darkSide": false },
  { "name": "66. Doppleganger", "category": "Control+Sense+Alter", "prereq": "DS 6,8,23,24,26,29,30,39,43,47,57,59,62", "darkSide": false },
  { "name": "67. Drain Life Energy", "category": "Control+Sense+Alter", "prereq": "DS 6,16,23,24,26,30,47", "darkSide": false },
  { "name": "68. Drain Life Essence", "category": "Control+Sense+Alter", "prereq": "DS 6,11,23,24,26,29,30,39,40,43,47,57,59,62,64", "darkSide": false },
  { "name": "69. Enhance Coordination", "category": "Control+Sense+Alter", "prereq": "24,62", "darkSide": false },
  { "name": "70. Force Harmony", "category": "Control+Sense+Alter", "prereq": "23,24,29,43", "darkSide": false },
  { "name": "71. Memory Wipe", "category": "Control+Sense+Alter", "prereq": "DS 6,11,23,24,26,29,30,39,40,43,59,62,64", "darkSide": false },
  { "name": "72. Projected Fighting", "category": "Control+Sense+Alter", "prereq": "3,39", "darkSide": false },
  { "name": "73. Telekinetic Kill", "category": "Control+Sense+Alter", "prereq": "DS 6,24,38,53", "darkSide": false },
  { "name": "74. Transfer Life", "category": "Control+Sense+Alter", "prereq": "DS 1,2,6,7,8,11,14,15,17,23,24,26,29,30,38,39,40,43,44,47,51,53,56,57,59,62,64", "darkSide": false },
  { "name": "75. Force Scream", "category": "Special", "prereq": "", "darkSide": true },
  { "name": "76. Lifemerge", "category": "Special", "prereq": "", "darkSide": false }
// --- END OF POWERS_DATA ---
];