const NPC_DATA = {
    "races":  [
                  "Adarian",
                  "Adnerem",
                  "Advozse",
                  "Aleena",
                  "Amanin",
                  "Annoo-Dat",
                  "Anomid",
                  "Ansionan",
                  "Anx",
                  "Anzat",
                  "Aqualish",
                  "Aramandi",
                  "Arcona",
                  "Arkanian",
                  "Arpor-Lan",
                  "Ayrou",
                  "Balinaka",
                  "Balosar",
                  "Barabel",
                  "Baragwin",
                  "Besalisk",
                  "Bimm",
                  "Bith",
                  "Blood Carver",
                  "Bosph",
                  "Bothan",
                  "Brubb",
                  "Buzchub",
                  "Caamasi",
                  "Carosite",
                  "Cerean",
                  "Cha\u0027a",
                  "Chadra-Fan",
                  "Chagrian",
                  "Chevin",
                  "Chikarri",
                  "Chiss",
                  "Cizerack",
                  "Clawdite",
                  "Coynite",
                  "Cragmoloid",
                  "Dazouri",
                  "Defel",
                  "Devaronian",
                  "Draethos",
                  "Drall",
                  "Dresselian",
                  "Dug",
                  "Dulok",
                  "Duro",
                  "Elomin",
                  "Em\u0027liy",
                  "Esoomian",
                  "Ewok",
                  "Falleen",
                  "Farghul",
                  "Feeorin",
                  "Fian",
                  "Filvian",
                  "Firrerreo",
                  "Frozian",
                  "Gacerite",
                  "Gamorrean",
                  "Gand",
                  "Geelan",
                  "Givin",
                  "Gotal",
                  "Gran",
                  "Gree",
                  "Gungun",
                  "Herglic",
                  "Ho'Din",
                  "Houk",
                  "Human",
                  "Hutt",
                  "Hysalrian",
                  "Iotran",
                  "Ishi Tib",
                  "Ithorian",
                  "Jarell",
                  "Jawa",
                  "Jenet",
                  "Kaleesh",
                  "Kallidahin",
                  "Kaminoan",
                  "Kel Dor",
                  "Kerestian",
                  "Khil",
                  "Klatooinian",
                  "Krytollak",
                  "Kobok",
                  "Koorivar",
                  "Kubaz",
                  "Kushiban",
                  "Kwa",
                  "Lafrarian",
                  "Lannik",
                  "Lasat",
                  "Marasan",
                  "Meri",
                  "M'shinn",
                  "Miraluka",
                  "Mon Calamari",
                  "Mulgaari",
                  "Murachaun",
                  "Mustafarian",
                  "Muun",
                  "Myneyrsh",
                  "Nagai",
                  "Najib",
                  "Nalroni",
                  "Nautolan",
                  "Near-Human",
                  "Neimoidian",
                  "Nikto",
                  "Nimbanel",
                  "Nosaurian",
                  "Nuknog",
                  "Oblee",
                  "Omwati",
                  "Ongree",
                  "Orfite",
                  "Orrem",
                  "Ortolan",
                  "Ossan",
                  "Oswaft",
                  "Pa\u0027lowick",
                  "Pacithhip",
                  "Pantoran",
                  "Pau\u0027an",
                  "Phindian",
                  "Pho Ph\u0027eahian",
                  "Poss\u0027Nomin",
                  "Psadan",
                  "Quarren",
                  "Rakririan",
                  "Ranth",
                  "Revwien",
                  "Riileb",
                  "Rodian",
                  "Saurton",
                  "Selonian",
                  "Skrilling",
                  "Sludir",
                  "Sluissi",
                  "Snivvian",
                  "Squib",
                  "Sullustan",
                  "Svivreni",
                  "Talz",
                  "Tarasin",
                  "Tarro",
                  "Tasari",
                  "Taung",
                  "Teek",
                  "Teltior",
                  "Thakwaash",
                  "Thisspian",
                  "Tinnell",
                  "Tiss\u0027shar",
                  "Togorian",
                  "Togruta",
                  "Toong",
                  "Toydarian",
                  "Trandoshan",
                  "Trianii",
                  "Tunroth",
                  "Tusken Raider",
                  "Twi\u0027lek",
                  "Tynnan",
                  "Ubese",
                  "Ugnaught",
                  "Ugor",
                  "Uukaablian",
                  "Vaathkree",
                  "Vernol",
                  "Verpine",
                  "Vodran",
                  "Vratix",
                  "Weequay",
                  "Werbol",
                  "Whiphid",
                  "Wookiee",
                  "Woostoid",
                  "Xexto",
                  "Xi\u0027Dec",
                  "Yagai",
                  "Yagai Drone",
                  "Yevetha",
                  "Yinchorri",
                  "Zabrak",
                  "Zexx"
              ],
    "jobs":  [
                 "Arrogant Noble",
                 "Arrogant Imperial Noble",
                 "Bounty Hunter",
                 "Brash Pilot",
                 "Failed Jedi",
                 "Force Student",
                 "Gambler",
                 "Kid",
                 "Scout",
                 "Local Guard",
                 "Loyal Retainer",
                 "Mercenary",
                 "Minor Jedi",
                 "Old Senator",
                 "Outlaw",
                 "Pirate",
                 "Quixotic Jedi",
                 "Retired Captain",
                 "Smuggler",
                 "Swoop Ganger",
                 "Technician",
                 "Tough Native",
                 "Young Jedi",
                 "Young Senator",
                 "SpecForce Pathfinder",
                 "SpecForce Urban Combat Specialist",
                 "SpecForce Wilderness Fighter",
                 "SpecForce Infiltrator",
                 "SpecForce Heavy Weapon Specialist",
                 "SpecForce Technician",
                 "SpecForce Driver/Pilot",
                 "SpecForce Scanner/Comm Operator",
                 "SpaceOps Trooper",
                 "Rodian Pacifist",
                 "Resistance Leader",
                 "Rebel Saboteur",
                 "Ordnance Procurer",
                 "New Republic Intelligence Operative",
                 "New Republic Security Force Agent",
                 "Noble-In-Exile",
                 "Mon Calamari Medic",
                 "Ithorian Storyteller",
                 "Holovid Celebrity",
                 "Ex-Imperial Commando",
                 "Alliance Liaison",
                 "Alliance Agitator",
                 "Xenoarchaeologist",
                 "Wookiee Bounty Hunter",
                 "Whiphid Collector",
                 "Svivreni Mineralogist",
                 "Squib Trader",
                 "Spoiled Debutante",
                 "Speeder Racer",
                 "Snivvian Artist",
                 "Slicer",
                 "Rodian Dramatist",
                 "Quarren Swindler",
                 "Professional Bodyguard",
                 "Outlaw Tech",
                 "NewsNet Reporter",
                 "Mon Calamari Professor",
                 "Mon Calamari Courier",
                 "Jawa Trader",
                 "Interstellar Transient",
                 "Industrial Espionage Agent",
                 "Herglic Gambler",
                 "Galactic Big Game Hunter",
                 "Flamboyant Entertainer",
                 "Ewok Shaman",
                 "Devaronian Grifter",
                 "Court Fop",
                 "Con Artist",
                 "Bith Musician",
                 "Bimm Bard",
                 "Barabel Shockboxer",
                 "Arms Merchant",
                 "Annoying Squib",
                 "Wealthy Physician",
                 "Unemployed Imperial Bureaucrat",
                 "TIE Fighter Pilot",
                 "Space Rescue Corps Officer",
                 "ISB Protocol Officer",
                 "ISB Investigations Specialist",
                 "Imperial Smuggler",
                 "Imperial Morale Officer",
                 "Imperial Intelligence Agent",
                 "Imperial Double Agent",
                 "Imperial Diplomat",
                 "Imperial Assassin-In-Training",
                 "Imperial Adjutant",
                 "Ground Assault Vehicle Commander",
                 "COMPNOR SAGroup Youth",
                 "CompForce Assault Trooper",
                 "Cautious First Mate",
                 "Freighter Captain",
                 "Weary Ships Tech",
                 "Co-Pilot",
                 "Engineer",
                 "Crate-Buster",
                 "Ships Gunner",
                 "Gunner",
                 "Pack Tracker",
                 "Spacer",
                 "Mercenary Trader",
                 "Roustabout",
                 "Hot-Shot Pilot",
                 "Gunrunner",
                 "Merchant",
                 "Cynical Free-Trader",
                 "Comm Slicker",
                 "Classy Smuggler",
                 "Privateer Captain",
                 "Alliance Observer",
                 "Boarder"
             ],
    "training":  [
                     "Novice",
                     "Trained",
                     "Experienced",
                     "Veteran",
                     "Elite",
                     "Minor Hero/Villan",
                     "Major Hero/Villan",
                     "Novice",
                     "Trained",
                     "Experienced",
                     "Veteran",
                     "Novice",
                     "Trained",
                     "Experienced"
                 ],
    "weapon1":  [
                    "Micro Blaster  2D+2  (1-5)",
                    "Merr-Sonn Q-2  3D  (3-4/8/12)",
                    "BlasTech 22T4 3D+1 (3-5/10/15)",
                    "Czerka 411  3D+1 (2-4/8/12)",
                    "Merr-Sonn J1  3D+1 (3-5/10/15)",
                    "Naboo Royal Pistol-S 3D+1 (3-4/8/12)",
                    "Naboo Royal Pistol-L 3D+1 (3-10/20/30)",
                    "SoroSuub Q-2  3D  (3-4/8/12)",
                    "SoroSuub Q-2s5  3D+2 (3-10/20/40)",
                    "Merr-Sonn Quickfire-4  4D  (3-4/8/12)",
                    "DDC Defender 3D+1 (3-10/30/60)",
                    "SoroSuub X-30 3D+1 (3-10/30/120)",
                    "Merr-Sonn Model 6 3D+2  (3-10/25/25)",
                    "Luxan Penatrator  5D  (5-20/40/60)",
                    "EA-SBP 200 3D (3-10/30/120)",
                    "Mer-Sonn IR5  3D  (3-7/25/50)",
                    "Galinolo XiX 4D (3-10/25/110)",
                    "Merr-Sonn 44  4D  (3-10/30/100)",
                    "SoroSuub ELG-3A  4D  (3-10/30/120)",
                    "SoroSuub SC4 4D (3-10/30/120)",
                    "Corellian Arms CR-2 4D (3-12/35/145)",
                    "BlasTech DL-18 4D (3-10/30/120)",
                    "BlasTech KK-5 4D (3-10/30/120)",
                    "BlasTech DH-17 4D (5-15/30/120)",
                    "BlasTech DH-23 4D+1 (3-10/20/80)",
                    "BlasTech DL-22 4D+1 (3-10/30/120)",
                    "Merr-Sonn DD6 4D+1 (3-10/25/90)",
                    "Caelli-Merced Series III  4D+2  (3-10/30/120)",
                    "Merr-Sonn 434  5D+1  (2-8/20/80)",
                    "BlasTech DL-6H 5D (3/10/30/120)",
                    "BlasTech DL-44  5D  (3-7/25/50)",
                    "BlasTech DY-225  5D  (3-5/20/40)",
                    "BlasTech T-6   6D+2  (3-7/25/50)",
                    "Caelli-Merced Sentinel IV 5D+2 (3-10/30/60)",
                    "Caliban Model X 5D+1 (2-5/15/35)",
                    "BlasTech HBP  5D+1  (3-7/25/50)",
                    "BP-19 4d+2 (3-8/20/60)",
                    "Merr-Sonn Flash 4  4D+2  (3-7-25-50)",
                    "SoroSuub Renegade  5D+2  (3-7/25/50)",
                    "SoroSuub Model Kylan-3  5D+2  (3-5/20/40)"
                ],
    "weapon2":  [
                    "BlasTech Starslasher  5D  (3-25/50/250*)",
                    "N\u0027gant-Zarvel 9118 5D+1 (3-25/50/200)",
                    "BlasTech Sharpshot V 4D+1  (3-30/80/350)",
                    "Trandoshan Slaver Stun 6D (3/10/30/120)****",
                    "SoroSuub 36T/i 4D+1 (3/25/50/250)",
                    "SoroSuub 36T 5D (3/25/50/250*)",
                    "SoroSuub Stormtrooper Two 5D+2 (3-30/50/200)**",
                    "BlasTech a280 5D+2 (4-40/120/300)",
                    "BlasTech A295 5D+1 (5-50/170/300)",
                    "BlasTech DC-15 5D+1 (10-40/130/350)",
                    "BlasTech DLT-19 5D (5-50/180/350)",
                    "BlasTech DLT-20A 5D+1 (4-35/110/280)",
                    "BlasTech E-11 5D (3-30/100/300)**",
                    "BlasTech EE-3 5D+2 (3-30/80/250)",
                    "BlasTech EKX-10 5D (5-50/150/350)",
                    "Czerka L-21 5D (3-50/200/450)",
                    "Greff-Timms AR-1 5D (4-40/120/350)********",
                    "Blastech StarAnvil HBR 5D+2 (3-25/50/250)**",
                    "Merr-Sonn G8 5D+1 (4-40/120/350)",
                    "SoroSuub Firelance 5D 3-30/100/300",
                    "SoroSuub 16 5D (3-30/100/300)",
                    "SoroSuub Stormtrooper One 5D (3-30/100/300)**",
                    "Czerka FS-1 Farshot 3d+2 (3-50/150/430)**",
                    "DDC Light Sport Hunter 4d+1 (3-40/120/350)**",
                    "Siang Lance 4D+1 (3/40/120/350)**",
                    "SoroSuub X-45 5D (1-25/100/250)**",
                    "Merr-Sonn LD-1 5D (2-50/150/500)*********",
                    "Exotac Arms EXP-7a Predator 7D (3-30/80/350)**"
                ],
    "weapon3":  [
                    "Prax Arms AXM-50 5D (3-25/50/75)**",
                    "BlasTech Lt Rptr 5D+1 (3-30/100/300)**",
                    "Merr-Sonn Rptr 3Z 6D (3-30/100/250)",
                    "BlasTech T-21 6D (3-50/120/300)",
                    "BlasTech Med Rptr 7D (3-60/150/400)",
                    "Merr-Sonn Mark ii Rptr 7D+2 (3-50/200/400)**",
                    "SoroSuub Hvy Rptr 8D (3-50/150/400)****",
                    "BlasTech E-Web 8D (3-75/200/500)****",
                    "BlasTech E-Web(15) 8D (3-75/200/500)****",
                    "BlasTech F-Web 8D (3-75/200/500)****"
                ],
    "comms":  [
                  "Comlink",
                  "Comlink",
                  "Comlink",
                  "Comlink",
                  "Comlink",
                  "Comlink",
                  "Comlink",
                  "Headset Comlink",
                  "Implant Comlink",
                  "Military-Grade Comlink",
                  "Secure Comlink",
                  "Secure Comlink",
                  "Secure Comlink"
              ],
    "credits":  [
                    "27",
                    "35",
                    "43",
                    "67",
                    "122",
                    "250",
                    "500",
                    "175",
                    "15",
                    "5",
                    "85",
                    "100",
                    "141",
                    "144",
                    "147",
                    "151",
                    "154",
                    "157",
                    "160",
                    "163",
                    "166",
                    "172",
                    "176",
                    "179",
                    "182",
                    "185",
                    "188",
                    "191",
                    "194",
                    "198",
                    "204",
                    "206",
                    "209",
                    "213",
                    "216",
                    "219",
                    "222",
                    "450",
                    "600",
                    "700",
                    "800",
                    "850",
                    "900",
                    "1000",
                    "2000",
                    "2500",
                    "3000",
                    "3500",
                    "4000",
                    "5000"
                ],
    "jetpack":  [
                    "Jet Pack! 100H 70V 10 charges",
                    "Jet Pack! 100H 70V 10 charges"
                ],
    "sec1":  [
                 "Computer Spike",
                 "Computer Spike",
                 "DataPad",
                 "DataPad",
                 "DataPad",
                 "DataPad",
                 "Pocket Secretary",
                 "Pocket Secretary",
                 "Recording Rod",
                 "Recording Rod",
                 "Recording Rod",
                 "Code Slicer",
                 "Scomp Spike",
                 "Scomp Spike"
             ],
    "sec2":  [
                 "Computer Spike",
                 "Computer Spike",
                 "Binders",
                 "Binders",
                 "Binders",
                 "Slave Collar/Rem",
                 "Stun Cuffs",
                 "Stun Cuffs",
                 "Magna Cuffs",
                 "Magna Cuffs",
                 "Scomp Spike",
                 "Scomp Spike",
                 "Code Slicer",
                 "Code Slicer",
                 "Code Slicer"
             ],
    "booster":  [
                    "Servo Slipper Arms",
                    "Servo Slipper Legs",
                    "Servo Slipper Arms \u0026 Legs",
                    "Zero-G harness"
                ],
    "med":  [
                "Medpac",
                "Med Kit",
                "Medpac",
                "3 Medpacs",
                "Medpac",
                "Med Kit",
                "3 Medpacs",
                "Medpac",
                "Bacta Geltabs \u0026 5 Medpac",
                "Bacta Geltabs \u0026 5 Medpac",
                "Trauma Kit",
                "Medpac",
                "Custom Medical Backpack**"
            ],
    "armor":  [
                  "Blast Helmet +1Dphys +1 energy (head)",
                  "Koromondain Half-Vest +1D+2 phys, +2 energy",
                  "Blast Vest +1D phys, +1energy (Torso)",
                  "Blast helmet \u0026 Vest +1D phys , +1 energy (Head,Torso)",
                  "Koromondain Half-Vest +1D+2 phys, +2 energy",
                  "Blast Helmet +1Dphys +1 energy (head)",
                  "CV14-B Concussion Vest +1D phys works for crashes and falls",
                  "Blast helmet \u0026 Vest +1D phys , +1 energy (Head,Torso)",
                  "Blast Vest +1D phys, +1energy (Torso)",
                  "Blast Helmet +1Dphys +1 energy (head)",
                  "Blast Helmet +1Dphys +1 energy (head)",
                  "Blast Vest +1D phys, +1energy (Torso)",
                  "Blast helmet \u0026 Vest +1D phys , +1 energy (Head,Torso)",
                  "Trackers Utility Vest +1phys and 28 pockets!",
                  "Koromondain Half-Vest +1D+2 phys, +2 energy",
                  "CV14-B Concussion Vest +1D phys works for crashes and falls",
                  "Bulk Exploratory Armor**",
                  "Bulk Exploratory Armor**",
                  "Bulk Exploratory Armor**",
                  "Space Suit",
                  "Space Suit",
                  "Vacuum Suit",
                  "Vacuum Suit",
                  "Vacuum Suit",
                  "Camo Armor  +1D phys +2 energy",
                  "Combat Jumpsuit  +1D phys +2 energy",
                  "Cresh Luck Armor +2D phys; +1D energy , IR sensor **",
                  "Primative Armor +1 phys",
                  "Ubese Raider Armor +2D phys +1D energy, **"
              ],
    "camo":  [
                 "Camo Fatigues",
                 "Camo Poncho",
                 "Shadowsuit",
                 "Camo Fatigues",
                 "Camo Poncho",
                 "Camo Poncho",
                 "Shadowsuit",
                 "Camo Fatigues",
                 "Camo Poncho",
                 "Camo Poncho",
                 "Camo Poncho",
                 "Shadowsuit",
                 "Camo Fatigues",
                 "Camo Poncho",
                 "Shadowsuit"
             ],
    "powersuit":  [

                  ],
    "shield":  [
                   "PD Dampener Aerosol -1D blaster  Dmg**",
                   "Portable Shield Generator 6D**",
                   "Primative Shield 3D",
                   "Riot Shield 4D, can Stun 4D **",
                   "Personal Energy Sheild 5D**",
                   "PD Dampener Aerosol -1D blaster  Dmg**",
                   "Primative Shield 3D",
                   "Personal Energy Sheild 5D**",
                   "Portable Shield Generator 6D**",
                   "Primative Shield 3D",
                   "Riot Shield 4D, can Stun 4D **",
                   "Personal Energy Sheild 5D**"
               ],
    "surveil1":  [
                     "Wide Scan Binoculars(Lenses) +1D**",
                     "Ziko 1000 Macrobinoculars +3D**",
                     "Macrobinoculars +3D**",
                     "Ziko 1125 Heads-Up Macrobinoculars **",
                     "Neuro-Saav  TT4 Holorecording Macrobinoculars +2D**",
                     "Drolan Plasteel Infra-goggles Reduce Dark Pen by 2D**",
                     "Snooper Goggles+2D works in Low Light**",
                     "Wide Scan Binoculars(Lenses) +1D**",
                     "Ziko 1000 Macrobinoculars +3D**",
                     "Peer Snooper Goggles+2D Low Light, +3D macromode**",
                     "Wide Scan Binoculars(Lenses) +1D**",
                     "Ziko 1000 Macrobinoculars +3D**",
                     "Macrobinoculars +3D**",
                     "Macrobinoculars +3D**",
                     "Peer Snooper Goggles+2D Low Light, +3D macromode**",
                     "Ziko 1125 Heads-Up Macrobinoculars **",
                     "Neuro-Saav  TT4 Holorecording Macrobinoculars +2D**",
                     "Drolan Plasteel Infra-goggles Reduce Dark Pen by 2D**",
                     "Snooper Goggles+2D works in Low Light**"
                 ],
    "surveil2":  [
                     "NeuroSaav 9320/B Sensor Pack**",
                     "Motion Sensor Pack 100m**",
                     "Gotal Electromagnetic Scanner**",
                     "Fabritech A-11 Cargo Scanner*",
                     "Cryoncorp Lifedetec Bioscanner*****",
                     "NeuroSaav 8932/D Sensor Pack**",
                     "NeuroSaav 4100/Mil Sensor Pack****",
                     "NeuroSaav TeleSonic Audio Pickup",
                     "Courier Communications Scanner**",
                     "Arantha  OTM-900 Orbital Comms**",
                     "Chandriltech PX-7 Heat Sensor****",
                     "SuriTech Foodstuffs Ez1 Analyzer**",
                     "SuriTech Disposable Toximeter Patch**",
                     "Culcanis MicroInstruments Tagger***",
                     "Astroserver Trailmaster**",
                     "Astroserver Industries Rover**",
                     "Dalabar Micro-Electronics SDS-632***",
                     "GFBS SFX Smoke Generator**",
                     "SVC-700 Voice Scrambler***",
                     "SNS-600 Sound Bubble***",
                     "Heat Pod***"
                 ],
    "survival":  [
                     "Basic Survival Gear",
                     "Breathing Mask",
                     "Shelter",
                     "Shelter and Survival Gear",
                     "Breathing Mask, Shelter, Survival Gear"
                 ],
    "tools":  [
                  "Tools for Tech skill",
                  "Tools for Tech skill",
                  "Tools for Tech skill"
              ],
    "melee":  [
                  "Force Pike STR+2D",
                  "Power Sword STR+3D",
                  "Power Cane 1D-5D(shock), or STR+1D(stiletto)*",
                  "Electrostaff Str+3D",
                  "Axe Str+2D max 5D",
                  "Bayonet Str+1D",
                  "Club Str+1D",
                  "Combat Knife Str+1D max 6D",
                  "Stun Baton Str+2d+2(Str+1D no charge)",
                  "Sword Str+2d max 6D",
                  "Stun Baton Str+2d+2(Str+1D no charge)",
                  "Gaffi Stick Str+1D",
                  "Garotte Str+1D**",
                  "Stun Baton Str+2d+2(Str+1D no charge)",
                  "Hatchet Str+2 or 1D+2 if thrown (3-6/10/15)",
                  "Knife Str+1D max 6D",
                  "Stun Baton Str+2d+2(Str+1D no charge)",
                  "Vibro-Ax STR+3D+1 max 7D",
                  "Vibro-Blade Str+3D max 6D",
                  "Vibro-shiv Str+1D",
                  "Vibro-Ax STR+3D+1 max 7D",
                  "Vibro-Blade Str+3D max 6D",
                  "Vibro-Blade Str+3D max 6D",
                  "Vibro-Blade Str+3D max 6D"
              ],
    "saber":  [
                  "Light Saber 5D",
                  "Short Light Saber 4D",
                  "Light Saber 5D",
                  "Double Bladed light Saber 5D (VD)",
                  "Light Saber 5D",
                  "Training light Saber 4D*",
                  "Light Saber 5D"
              ],
    "near_human_subtypes":  [
                                "Near-Human: Aquar",
                                "Near-Human: Arhan",
                                "Near-Human: Arkanian",
                                "Near-Human: Bimm",
                                "Near-Human: Boltrunian",
                                "Near-Human: Borneck",
                                "Near-Human: Brosin",
                                "Near-Human: Chev",
                                "Near-Human: Chiss",
                                "Near-Human: Emmerian",
                                "Near-Human: Enso",
                                "Near-Human: Enu",
                                "Near-Human: Epicanthix",
                                "Near-Human: Etti",
                                "Near-Human: Firrerreo",
                                "Near-Human: Galandan",
                                "Near-Human: Ganathan",
                                "Near-Human: Hapan",
                                "Near-Human: Kalzerians",
                                "Near-Human: Keeds",
                                "Near-Human: Keshiri",
                                "Near-Human: Khommite",
                                "Near-Human: Kiffar",
                                "Near-Human: Locan",
                                "Near-Human: Lorrdian",
                                "Near-Human: Lowen",
                                "Near-Human: Miraluka",
                                "Near-Human: Mirialan",
                                "Near-Human: Morellian",
                                "Near-Human: Nagai",
                                "Near-Human: Nish",
                                "Near-Human: Ocsinin",
                                "Near-Human: Ogemite",
                                "Near-Human: Omwati",
                                "Near-Human: O\u0027reenian",
                                "Near-Human: Pantoran",
                                "Near-Human: Pau\u0027an",
                                "Near-Human: Qiraash",
                                "Near-Human: Reussi",
                                "Near-Human: Ropagu",
                                "Near-Human: Ruusanian",
                                "Near-Human: Samuac",
                                "Near-Human: Sernpidalian",
                                "Near-Human: Shownarri",
                                "Near-Human: Skups",
                                "Near-Human: S\u0027kytri",
                                "Near-Human: Stennes",
                                "Near-Human: Taung",
                                "Near-Human: Theelin",
                                "Near-Human: Torine",
                                "Near-Human: Utai",
                                "Near-Human: Vendaran",
                                "Near-Human: Vodran",
                                "Near-Human: Vorzydiak",
                                "Near-Human: Vultan",
                                "Near-Human: Wroonian",
                                "Near-Human: Yaka",
                                "Near-Human: Ysanna Nomad",
                                "Near-Human: Zanibar",
                                "Near-Human: Zelosian",
                                "Near-Human: Zeltron",
                                "Near-Human: Zisian",
                                "Near-Human: Zhell"
                            ],
    "weapon1_blank":  0.11,
    "weapon2_blank":  0.22,
    "weapon3_blank":  0.44,
    "comms_blank":  0.24,
    "credits_blank":  0.35,
    "jetpack_blank":  0.9,
    "sec1_blank":  0.18,
    "sec2_blank":  0.42,
    "booster_blank":  0.78,
    "med_blank":  0.35,
    "armor_blank":  0.37,
    "camo_blank":  0.25,
    "powersuit_blank":  1,
    "shield_blank":  0.67,
    "surveil1_blank":  0.21,
    "surveil2_blank":  0.43,
    "survival_blank":  0,
    "tools_blank":  0.4,
    "melee_blank":  0.38,
    "saber_blank":  0.5
// --- END OF NPC_DATA ---
};