const PLANETS_DATA = [
  {
    name: "Celanon",
    system: "Nairas",
    star: "Nairas (yellow)",
    grid: "O-6",
    region: "Outer Rim Territories",
    type: "Agricultural plains",
    temperature: "Temperate",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Moderate",
    gravity: "Standard",
    terrain: "Plains, forest, urban",
    lengthOfDay: "32 standard hours",
    lengthOfYear: "187 local days",
    sapientSpecies: "Bith, Duros, Humans, Nalroni (N)",
    starport: "1 Imperial class",
    population: "26 million permanent + 40 million transients",
    function: "Homeworld, trade",
    government: "Trade guilds",
    techLevel: "Space",
    majorExports: "Foodstuffs, bulk trade goods",
    majorImports: "Luxury goods",
    source: "WEG40100 The Planets Collection p.35",
    summary: "Celanon is a major galactic trade world controlled by the Nalroni, a cunning species of trade representatives. The entire planet's economy revolves around Celanon City, a massive 200 sq km circular metropolis surrounded by a 10-meter wall and divided into 9 distinct districts. Nalroni Trade Reps are notorious for extorting 100–1,000 credit bribes from visitors. The planet maintains a delicate neutrality, with the Nalroni playing the Empire against the Alliance in what they call 'being in the hunt.' Six continents support agricultural production, and the Imperial class starport features a 140-story control tower.",
    locations: "Celanon City (only city, 200 sq km, 50M+ beings, circular with 10m wall, 9 districts: Spaceport, Diplomatic, Spacers, Transient, Trade Guilds, Imperial Military, Market, Corporate, Governing). Spaceport has economy bays at 150 cr/day and trader bays at 250 cr/day. 6 continents: Cekbar, Arradi, Holvi, Runnor, Jelldar, Desetur. 5 Imperial army battlegroups stationed in city.",
    ofNote: "Nalroni Trade Reps extort 100–1,000 cr bribes from all visitors. The Nalroni play the Empire vs the Alliance — 'being in the hunt.' Imperial class starport with 140-story control tower. All trade on Celanon flows through the guilds."
  },
  {
    name: "Essowyn",
    system: "Saurton",
    star: "Saurton (yellow)",
    grid: "Q-10",
    region: "Mid Rim",
    type: "Cratered plains",
    temperature: "Temperate",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Dry",
    gravity: "Standard",
    terrain: "Cratered plains, hills",
    lengthOfDay: "39 standard hours",
    lengthOfYear: "401 local days",
    sapientSpecies: "Humans, Saurton (N), Sullustans, Verpine",
    starport: "1 standard class",
    population: "80 million",
    function: "Homeworld, mining",
    government: "Elitist council",
    techLevel: "Feudal",
    majorExports: "Metals, minerals, foodstuffs",
    majorImports: "Technology",
    source: "WEG40100 The Planets Collection p.41",
    summary: "Essowyn is the Saurton homeworld, a cratered landscape honeycombed with underground cities extending 100+ meters deep. The planet is dominated by six powerful mining megacorporations that hold absolute authority over their territories. A simmering civil war brews between the Quenno (traditionalists) and Des'mar (pro-corporate) factions. The Saurton government is a 35-member trashur council selected from Elders, with Protectors serving as combined judge/police/soldier. Twin asteroid belts (Kanawyn and Greawyn) support additional mining. Dangerous underground bacteria require decontamination booths at all city entrances.",
    locations: "Underground Saurton cities (100m+ deep, multi-layered tunnels). Corporate mining complexes (6 megacorps with absolute territorial authority). Twin asteroid belts: Kanawyn and Greawyn. Quadrillium mining operations.",
    ofNote: "Underground cities require decon booths due to dangerous bacteria. Civil war brewing between Quenno traditionalists and Des'mar pro-corporate factions. 35-member trashur government. Protectors serve as combined judge/police/soldier. Quadrillium mining is primary industry."
  },
  {
    name: "Garnib",
    system: "Garnib",
    star: "Garnib (blue)",
    grid: "L-18",
    region: "Outer Rim Territories",
    type: "Glacier covered",
    temperature: "Cool",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Saturated",
    gravity: "Standard",
    terrain: "Frigid oceans, glaciers, islands",
    lengthOfDay: "35 standard hours",
    lengthOfYear: "432 local days",
    sapientSpecies: "Balinaka (N), Humans, Kubaz, Vernols",
    starport: "1 limited services",
    population: "100 million",
    function: "Homeworld, crystal production",
    government: "GCC corporate",
    techLevel: "Space",
    majorExports: "Garnib Crystals, fish",
    majorImports: "Technology, foodstuffs",
    source: "WEG40100 The Planets Collection p.47",
    summary: "Garnib is a frozen world famous for its Garnib Crystals — beautiful, borderline addictive gemstones banned on some worlds. The Balinaka natives carve their Sewfes settlements from ice, powered by geothermal energy. Crystal factories are modular structures built near volcanoes and ocean fissures. The annual Wallarand festival lasts 50 days, combining town meeting, stockholders meeting, and celebration — all work stops planet-wide. The reclusive Imperial Governor Verus Carbinol hates the cold and rarely leaves his quarters. An Imperial garrison of 3 battalions (Garnib Station) rarely patrols.",
    locations: "Sewfes (Balinaka ice-carved settlements, geothermal powered). Crystal Factories (modular, near volcanoes/ocean fissures). Fishing Harbors. Artist Communities. Garnib Station (Imperial, 3 battalions, rarely patrol).",
    ofNote: "Garnib Crystals are borderline addictive and banned on some worlds. The Wallarand is a 50-day annual festival where all work stops — it's a combined town meeting, stockholders meeting, and party. Imperial Governor Verus Carbinol is reclusive and hates the cold."
  },
  {
    name: "Isen IV",
    system: "Isen",
    star: "Isen",
    grid: "N-5",
    region: "Outer Rim Territories",
    type: "Airless planetoid",
    temperature: "Frigid",
    atmosphere: "None",
    hydrosphere: "Dry",
    gravity: "Light",
    terrain: "Airless rock",
    lengthOfDay: "N/A",
    lengthOfYear: "740 local days",
    sapientSpecies: "Humans",
    starport: "Standard (pirate)",
    population: "500",
    function: "Pirate base",
    government: "Abav Ghart (Gotal pirate lord)",
    techLevel: "Space",
    majorExports: "Stolen goods",
    majorImports: "Supplies, weapons",
    source: "WEG40100 The Planets Collection p.60",
    summary: "Isen IV is a barren, airless planetoid serving as the hidden base of the Void Demons pirate gang, led by the Gotal pirate Abav Ghart (300K credit bounty, 500K alive). The base is heavily fortified with 8 laser cannons, 3 turbolaser batteries, 8 tractor beams, 36 starfighters, 47 pilots, and 320 boarding troops. The Broken Hulls spaceship graveyard contains salvageable computer banks. The Morvak Tunnels are a deadly 3D maze of 1-meter-diameter passages in zero gravity and zero atmosphere.",
    locations: "Void Demon Base (8 laser cannons, 3 turbolaser batteries, 8 tractor beams, 36 starfighters, 47 pilots, 320 boarding troops). Broken Hulls (spaceship graveyard, accessible computer banks). Morvak Tunnels (1m diameter, zero-g, zero-atmo, 3D maze).",
    ofNote: "Abav Ghart: Gotal pirate lord with cybernetic repulse-hand + motion interface. 300K cr bounty (500K alive). Burnal Terrup (Devaronian) is second-in-command. The Morvak Tunnels are a lethal zero-g maze used for ambushes."
  },
  {
    name: "Coyn",
    system: "Coynek",
    star: "Coynek (orange)",
    grid: "M-20",
    region: "Outer Rim Territories",
    type: "Terrestrial forest",
    temperature: "Temperate",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Moderate",
    gravity: "Standard",
    terrain: "Forest, plains, mountains, marshes",
    lengthOfDay: "20 standard hours",
    lengthOfYear: "380 local days",
    sapientSpecies: "Coynites (N)",
    starport: "5 stellar class",
    population: "800 million",
    function: "Homeworld, trade",
    government: "Feudal garrison-state",
    techLevel: "Space",
    majorExports: "Lumber, weaponry, mercenaries",
    majorImports: "Technology, luxury goods",
    source: "WEG40100 The Planets Collection p.135",
    summary: "Coyn is the warrior homeworld of the Coynites, governed by the En'Tra'Sol code of honor — a strict warrior code emphasizing combat, honor, and no deception. Touching a Coynite without permission or deceiving one earns the label af'harl (cowardly deceiver), stripping all rights. The planet has 5 starports and is ruled by King Im'Toral XV from the capital En'Tra'Tal, which features the Rols'Kus — a 250,000-seat gladiatorial arena. 29 noble families (Ag'Tra) control governance. Ekkar Arms produces premium weapons at +10% cost. The Mercenary Guild of Coyn is galaxy-renowned.",
    locations: "En'Tra'Tal (capital, King Im'Toral XV, Rols'Kus 250K-seat arena, Arquas'Tais cemetery). Skraj'Tais (orbiting station, prime starport). En'Tra'Tais (largest surface port). Im'Tra'Tais (most luxurious). Ah'Kra (best medical/repair). Kroyn'Tais (Imperial base). Kra'Tais (standard class).",
    ofNote: "En'Tra'Sol warrior code: honor/combat/no deception/no touching without permission. af'harl = cowardly deceiver, loses all rights. Coynite weapons: coyn'skar (pole, STR+2D), sat'skar (sword, STR+3D+1), d'skar (dagger, STR+1D+1). Battle armor +2D protection. Ekkar Arms: premium weapons +10% cost. Mercenary Guild of Coyn is galaxy-renowned. Tris = bonded war-mounts."
  },
  {
    name: "Merisee",
    system: "Maris",
    star: "Maris (yellow)",
    grid: "M-19",
    region: "Outer Rim Territories",
    type: "Agricultural plains",
    temperature: "Temperate",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Moderate",
    gravity: "Standard",
    terrain: "Plains",
    lengthOfDay: "24 standard hours",
    lengthOfYear: "315 local days",
    sapientSpecies: "Meris (N), Teltiors (N)",
    starport: "3 standard class",
    population: "310 million",
    function: "Agriculture, homeworld",
    government: "Participatory democracy",
    techLevel: "Space",
    majorExports: "Grain, alcohol, pharmaceuticals",
    majorImports: "Technology, luxury goods",
    source: "WEG40100 The Planets Collection p.156",
    summary: "Merisee is the shared homeworld of the Meris and Teltiors, two species that once warred for a thousand years before achieving peace through 'The Joining' — a cataclysmic land bridge formation. The planet is known for agriculture (collective farms of 24–120 people), pharmaceuticals from the Meris III plant, and the secret Loag assassin cult (min 5,000 cr contracts) operating from a hollowed-out volcano citadel. The Cult of Those Who Redeem secretly worships the Jedi. Caronath is the only major city (5M+ pop), featuring Thinking Gardens (5 cr/hr) and the renowned Merisee Grand Medical Facility (double cost, -1 difficulty, 2/3 healing time).",
    locations: "Caronath (capital, 5M+, only major city, Thinking Gardens 5 cr/hr, counselors, Utoz Houses). Merisee Prime Starport + Merisee Dispatch (outside Caronath). Merisee Agra (bulk cargo). Merisee Grand Medical Facility (double cost, -1 difficulty, 2/3 healing time). Merisee Asylum (adjoining). Loag Citadel (secret, hollowed volcano, assassin cult). Utozz Prime Brewery.",
    ofNote: "Loag assassins: thought destroyed by Jedi, secretly rebuilt in hollowed volcano. Min 5,000 cr contracts. Cult of Those Who Redeem: secret Jedi-worshippers. Meris III pharmaceutical plant is key export. 'The Joining' land bridge ended 1,000-year war between Meris and Teltiors."
  },
  {
    name: "Derilyn",
    system: "Deril",
    star: "Deril (medium yellow)",
    grid: "M-19",
    region: "Outer Rim Territories",
    type: "Occupied urban police-state",
    temperature: "Temperate",
    atmosphere: "Type I (breathable)",
    hydrosphere: "Moderate",
    gravity: "Standard",
    terrain: "Urban, plains, forest, mountains, desert",
    lengthOfDay: "27 standard hours",
    lengthOfYear: "350 local days",
    sapientSpecies: "Coynites, Gamorreans, Humans, Meris, Teltiors",
    starport: "2 Imperial class + 2 stellar class",
    population: "2 billion",
    function: "Trade, manufacturing",
    government: "Imperial police state",
    techLevel: "Space",
    majorExports: "High technology",
    majorImports: "Raw materials, foodstuffs",
    source: "WEG40100 The Planets Collection p.164",
    summary: "Derilyn is a conquered Imperial police state, taken during the brutal 'Sixty Hour War.' Under martial law by General Afren Hul (a brutal, alien-hating commander), the planet is heavily militarized. Moff Villis Andal is lazy and leaves governance entirely to Hul. The city of Paran was bombarded from 512K to just 3K residents, and its underground repulsor train tunnels now serve as HQ for the Friends of Paran resistance (~420 active members). The Derilyn Space Defense Platform is massive: 4,225m long, 8,750 crew, 80 turbolaser batteries, 2 TIE wings. Travel requires a 100 cr Imperial waiver per trip.",
    locations: "Derilysa (capital, Moff's Palace + Gov Palace, Base Derilysa). Tekar (largest city, Derilyn Space Central starport, 36 TIEs, harsh checkpoints, heavy industry). Paran (ruins, 512K→3K after bombardment, Friends of Paran resistance HQ in underground repulsor train tunnels). Dorrak + Palpatine (military bases). Derilyn Space Defense Platform (4,225m, 8,750 crew, 80 turbolaser batteries, 2 TIE wings).",
    ofNote: "'Sixty Hour War' conquest. Martial law under General Afren Hul (brutal, alien-hating). Moff Villis Andal (lazy). Friends of Paran resistance (~420 active members). IML (Imperial Mining Ltd) uses slave labor. Travel Waiver required 100 cr/trip. Imperial Interdicted Space around system."
  },
  {
    name: "Gacerlan",
    system: "Klozar",
    star: "Klozar (orange)",
    grid: "N-15",
    region: "Expansion Region",
    type: "Desert",
    temperature: "Hot",
    atmosphere: "Type II (breath mask required)",
    hydrosphere: "Dry",
    gravity: "Light",
    terrain: "Desert, mountains",
    lengthOfDay: "36 standard hours",
    lengthOfYear: "375 local days",
    sapientSpecies: "Gacerites (N)",
    starport: "1 stellar class",
    population: "27 million",
    function: "Trade, homeworld",
    government: "Imperial governor",
    techLevel: "Space",
    majorExports: "Musical entertainment, gemstones",
    majorImports: "Technology, foodstuffs",
    source: "WEG40100 The Planets Collection p.230",
    summary: "Gacerlan is the homeworld of the Gacerites — 2.5m tall, hairless beings with a third lung in their neck 'gills' that allows them to sing while breathing. Music and etiquette define their culture; silence is considered equivalent to death. The only city, Harmonia (520 sq km), features crystal spires that resonate in the wind, glowing with orange light through translucent crystal. The Musical Rocks (Oueee-ha) and Singing Forest (Keee-s'ae) are cultural shrines. The Gacerites are rabidly pro-Imperial. A secret Imperial moon base (Tempay) houses 40 stormtroopers, 32 TIE pilots, and 12 TIEs + 12 TIE/rc.",
    locations: "Harmonia (only city, 520 sq km, crystal spires that resonate in wind, orange light through translucent crystal). Musical Rocks (Oueee-ha, Plateau of Dreams, wind-music shrine). Singing Forest (Keee-s'ae, s'ae trees 100m tall, seismic resonance, spring lake). Gem Mines (110 Gacerites + 20 stormtroopers each). Tempay Imperial Base (secret moon base, 40 stormtroopers, 32 TIE pilots, 12 TIEs + 12 TIE/rc).",
    ofNote: "Gacerites: 2.5m tall, hairless, third lung in neck 'gills' for singing while breathing. Music + etiquette = culture. Silence = death. Rabidly pro-Imperial. Sound-based weapons. Imperial Governor Ulbrek Gostech (fair but loyal). Captain Engar Ret (moon base, scheming against Gostech). Two moons always in opposition."
  }
];
