const FORCE_POWERS_DATA = [
 {
  "number": 1,
  "name": "Absorb/Dissipate Energy",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for sunburn/minor energy; Easy for intense sun; Moderate for solar wind/modest energy; Difficult for radiation storms/intense energy. For blaster bolts and Force lightning: Moderate plus attack damage roll.",
  "timeToUse": "One round",
  "keepUp": "Yes (constant sources only, not blaster bolts/lightning)",
  "effect": "Allows the Jedi to absorb or dissipate energy, including light, heat, radiation and blaster bolts. A successful control roll means the energy is dissipated. If the user fails the roll, she takes full damage. May be used to ward off sunburn, heat-stroke and radiation exposure, as well as withstand intense heat. May also absorb blaster bolts (as Darth Vader did on Cloud City). Must activate in the same round to absorb blaster bolt or Force lightning \u2014 must roll before the attack lands. Cannot be used after the attack has hit.",
  "source": "R&E (page 142-143)"
 },
 {
  "number": 2,
  "name": "Accelerate Healing",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy for wounded; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "A Jedi who uses this power successfully may make two natural healing rolls for the current day (12 hours apart) regardless of the severity of the injury. The Jedi gets a +2 modifier to both Strength rolls to heal. Accelerate healing may only be attempted once per day.",
  "source": "R&E (page 143)"
 },
 {
  "number": 3,
  "name": "Concentration",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy if relaxed and at peace; Difficult if filled with aggression, fear or other negative emotions; Very Difficult if acting on those negative emotions.",
  "timeToUse": "One round",
  "keepUp": "No",
  "effect": "The Jedi clears all negative thoughts from her mind, concentrating on one specific task. If successful, the Jedi may add +4D to any one action in that round. The Jedi may do nothing other than using concentration and that one skill for one action. No bonus if anything else is done in that round, including duplicate uses of the same skill or dodges or parries. May be used in conjunction with Force Points or Character Points. Only in effect for one round.",
  "source": "R&E (page 143)"
 },
 {
  "number": 4,
  "name": "Contort/Escape",
  "category": "Control",
  "prereqs": "3,6,9",
  "darkSide": false,
  "difficulty": "Very Easy for loose bonds; Easy for hand binder; Moderate for serious restraints; Difficult to Heroic for maximum security (varies at GM discretion).",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The character may escape bonds by contorting in painful and difficult (but still physically possible) ways. By stretching, twisting, and dislocating joints a Jedi can escape almost any physical restraining device. Jedi are trained to block out the pain and focus on the task at hand.",
  "source": "Tales of the Jedi Companion (page 41), Jedi Academy Sourcebook (page 42)"
 },
 {
  "number": 5,
  "name": "Control Disease",
  "category": "Control",
  "prereqs": "2",
  "darkSide": false,
  "difficulty": "Very Easy for mild infection (cold); Easy for modest infection (high fever, severe flu); Moderate for severe illness (gangrene, hive virus); Difficult for life-threatening disease; Very Difficult for massive long-standing disease; Heroic for rapid-acting life-threatening disease.",
  "timeToUse": "30 minutes to several uses over weeks",
  "keepUp": "No",
  "effect": "Allows the Jedi to direct and control the anti-bodies and healing resources of her body to throw off an infection or resist diseases. Requires 30 minutes of meditation. If the disease is life-threatening or long-standing, the Jedi must make repeated skill attempts over several weeks or months to cure entirely (GM discretion on how many rolls and how often).",
  "source": "R&E (page 143)"
 },
 {
  "number": 6,
  "name": "Control Pain",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for wounded or stunned; Easy for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round",
  "keepUp": "Yes (new roll required when injured again at new injury level)",
  "effect": "A wounded Jedi who controls pain can act as if she has not been wounded, starting the round after the power roll. The wound is not healed, but the character doesn't suffer the penalties of being wounded: wounded Jedi has no die code penalties; incapacitated or mortally wounded can act normally. Can shrug off stun results. However, the character is still injured and prone to getting worse. Mortally wounded Jedi may still die from injuries even if not feeling pain.",
  "source": "R&E (page 143-144)"
 },
 {
  "number": 7,
  "name": "Detoxify Poison",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for very mild poison (alcohol); Easy for mild poison; Moderate for average poison; Difficult for virulent poison; Very Difficult to Heroic for neurotoxin.",
  "timeToUse": "Five minutes",
  "keepUp": "No",
  "effect": "Allows a Jedi to detoxify or eject poisons that have entered her body. If the Jedi makes the power roll, the poison doesn't affect her.",
  "source": "R&E (page 144)"
 },
 {
  "number": 8,
  "name": "Emptiness",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Moderate. Note: Characters consumed by the dark side may not use this power.",
  "timeToUse": "",
  "keepUp": "Yes (see description)",
  "effect": "The user empties her mind and allows the Force to flow through her. The character falls into deep meditation, unconscious and oblivious to surroundings. Difficult to sense or affect with Force \u2014 add the emptiness roll to the difficulty for another character's sense roll (or control roll if power doesn't use sense). After coming out: +6 bonus to all Force skill rolls for a period equal to time spent in emptiness, reduced by -1 per Dark Side Point. Characters dehydrate and hunger normally \u2014 some initiates have died in emptiness. Difficult control roll to bring herself out. Player must declare duration when entering. May attempt to exit: when stated time passes, once each hour beyond the limit, or when body takes damage more serious than stun.",
  "source": "R&E (page 144)"
 },
 {
  "number": 9,
  "name": "Enhance Attribute",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One round",
  "keepUp": "No (duration determined by roll, extendable with Character Points)",
  "effect": "Increases a single attribute for a limited time. All skills controlled by the enhanced attribute increase by the same amount. Only one attribute at a time \u2014 enhancing a second drops the first. Duration extendable by spending Character Points (+1 round per point, spent any time before power fades). Beat difficulty by 0-13: +1D for 3 rounds. Beat by 14-25: +2D for 2 rounds. Beat by 26+: +3D for 1 round.",
  "source": "Tales of the Jedi Companion (page 44-45)"
 },
 {
  "number": 10,
  "name": "Force of Will",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy.",
  "timeToUse": "One round",
  "keepUp": "Yes",
  "effect": "The character uses Willpower skill to fight hostile mind-based Force powers. Add Willpower to Control or Perception to create a 'protection number.' If attack roll < Control/Perception: no effect. If attack roll > protection number: full effects. If attack roll between the two: protected, but Willpower is 'battered' (-1D to Willpower, reroll protection number). If Willpower reaches 0D, power drops automatically. Recovery: 1 day per 1D, or 1 hour in emptiness/rage per 1D. Does NOT protect against Force lightning, Force storms, or telekinetically hurled objects (external powers). DOES work against injure/kill, telekinetic kill, inflict pain, and other powers that directly use the Force on the target.",
  "source": "Tales of the Jedi Companion (page 45), Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 11,
  "name": "Hibernation Trance",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Places the Jedi into a deep trance, slowing all body functions. Heartbeat slows, breathing barely perceivable, falls unconscious. Can heal while in trance but can do nothing else. Appears dead unless specifically tested. Another Jedi with sense or life detection can detect Force within the character. Player must declare wake conditions (time or stimuli). Another Jedi can use 'place another in hibernation trance' to bring user out. Uses about 1/10th normal air. Survives: 1 week dry climate / 1 month wet climate without water (IV drip = indefinite); up to 3 months without food (IV sugar = 1 year).",
  "source": "R&E (page 144)"
 },
 {
  "number": 12,
  "name": "Instinctive Astrogation",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Difficult. Modified by astrogation difficulty: Very Easy +0, Easy +5, Moderate +10, Difficult +15, Very Difficult +20, Heroic +30.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "The Jedi calculates hyperspace equations mentally rather than feeling them through the Force (the sense-based version). If control roll succeeds, a Very Easy astrogation roll enters the routes into the nav computer. If the roll fails, the Jedi overlooks an obstacle \u2014 astrogation difficulty increases to Very Difficult. If missed by 5+, astrogation difficulty increases to Heroic. A largely unknown and rarely studied application \u2014 little more than a curiosity among Jedi theoreticians.",
  "source": "Tales of the Jedi Companion (page 46)"
 },
 {
  "number": 13,
  "name": "Rage",
  "category": "Control",
  "prereqs": "11",
  "darkSide": true,
  "difficulty": "Difficult. Note: Can only be used by characters consumed by the Dark Side. Use gives a Dark Side Point.",
  "timeToUse": "",
  "keepUp": "No (see description)",
  "effect": "Dark side counterpart to Emptiness. Character enters a trance, appearing lifeless, face clenched in horror. Must declare duration. Difficult control roll every 4 hours to stay in trance. After exiting: +10 modifier to all Force skill rolls for a period equal to time in rage. Then takes 1D damage per 2 hours spent in rage. Adds rage control roll to difficulty of Force powers targeting the user. Dehydrates twice as fast. -1D to Strength vs physical/energy damage while in rage. Physical contact by a living being may revive (Moderate control roll) and provoke instant berserker attack \u2014 Difficult control roll to stop before killing the person. Can anticipate a foe's arrival with Difficult sense roll (life sense) when entering rage \u2014 Easy control roll to awaken instantly when expected person comes within 5 meters. Can be used as preparation for transfer life \u2014 original body consumed by dark side (blue flames), 1D damage per 3 points over difficulty (3m blast radius).",
  "source": "Dark Empire Sourcebook (page 68), Tales of the Jedi Companion (page 46)"
 },
 {
  "number": 14,
  "name": "Reduce Injury",
  "category": "Control",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "Moderate for incapacitated; Difficult for mortally wounded; Very Difficult for dead.",
  "timeToUse": "Must be used same round as injury or immediately following round",
  "keepUp": "No",
  "effect": "Reduces injury suffered to wounded. Costs a Force Point. If the original injury would have killed the character, the GM inflicts a relevant permanent injury. Note: Not always a 'selfish' act to save one's life \u2014 character might get the Force Point back if fighting to save friends from certain doom (could be considered heroic).",
  "source": "R&E (page 144)"
 },
 {
  "number": 15,
  "name": "Remain Conscious",
  "category": "Control",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "Easy for stunned; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round (must be first action of round)",
  "keepUp": "No",
  "effect": "Allows a Jedi to remain conscious after injuries that would cause unconsciousness. When suffering such injury, loses all other actions for the rest of the round but stays conscious. At the beginning of next round, must attempt to activate as first action (cannot dodge or parry). If unsuccessful, passes out immediately. If successful, may perform one other action that round (often control pain). After that action, lapses into unconsciousness unless control pain or similar power is activated.",
  "source": "R&E (page 144-145)"
 },
 {
  "number": 16,
  "name": "Remove Fatigue",
  "category": "Control",
  "prereqs": "2,6",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Combats the effects of strenuous work by manipulating the Force to eject bodily toxins more efficiently, allowing greater stamina. While kept up, must make a stamina check once per day. Must fail two stamina checks before becoming fatigued. Still must eat and drink normally. If fatigued (two failed checks): -1D penalty to all attributes and skills for 1D hours. Note: Cannot be used for Lifting \u2014 use Enhance Attribute instead.",
  "source": "Tales of the Jedi Companion (page 47), Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 17,
  "name": "Resist Stun",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One minute",
  "keepUp": "Yes",
  "effect": "Prepares the Jedi's body to resist stun damage. Must be activated before suffering any damage. Successful roll allows the Jedi to resist all stun results except unconscious. An unconscious result forces the Jedi to drop the power (considered stunned instead). Other injuries (wounded, incapacitated, mortally wounded, killed) are treated normally.",
  "source": "R&E (page 145)"
 },
 {
  "number": 18,
  "name": "Short-Term Memory Enhancement",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The Jedi can replay recent events to examine images and peripheral occurrences more carefully. Can freeze images and scan memory tracks to recall details that were seen but didn't register consciously. Can alert the Jedi to information, items, characters, or anything that passed before their senses. If the GM provided clues that players missed, this power can recall them. How far back: beat difficulty by 0-8 = current episode; 9-20 = last episode; 21+ = last two episodes.",
  "source": "Tales of the Jedi Companion (page 47)"
 },
 {
  "number": 19,
  "name": "Beast Languages",
  "category": "Sense",
  "prereqs": "24,29,34,43",
  "darkSide": false,
  "difficulty": "Easy for domesticated/friendly animals (bantha); Moderate to Difficult for wild non-predatory (undomesticated tauntaun); Very Difficult to Heroic for ferocious/predatory (wild rancor).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Allows the Jedi to translate beast-language and speak it. The Jedi reads differences in surface emotions within grunts, growls, and body language cues. Creatures rarely have 'true' languages. For beasts that can be ridden, subtract 2D from their orneriness code while in effect (minimum 0D).",
  "source": "Tales of the Jedi Companion (page 48), Jedi Academy Sourcebook (page 45-46)"
 },
 {
  "number": 20,
  "name": "Combat Sense",
  "category": "Sense",
  "prereqs": "21,23,42",
  "darkSide": false,
  "difficulty": "Moderate for one opponent, +3 for each additional opponent the Jedi wants to defend against.",
  "timeToUse": "",
  "keepUp": "No (lasts 10 combat rounds)",
  "effect": "The Jedi focuses entirely on combat. All targets become mentally highlighted. Advantages: 1) The Jedi decides when to act during a round \u2014 no initiative rolls needed. If multiple Jedi use this, highest roll determines order. 2) Attack and defense rolls increased by +2D. Lasts 10 combat rounds. Does not count as a 'skill use' for determining die code penalties.",
  "source": "Tales of the Jedi Companion (page 47)"
 },
 {
  "number": 21,
  "name": "Danger Sense",
  "category": "Sense",
  "prereqs": "23,42",
  "darkSide": false,
  "difficulty": "Moderate or attacker's control roll (whichever is higher).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "The Jedi extends senses like protective sensors, creating an early warning system. When active, the Jedi detects any attacks the round before they are made, giving one round to decide how to react. Any character planning to attack the Jedi on the next round must declare their action the round before. Attackers may roll their control skill to increase the difficulty of this power.",
  "source": "Tales of the Jedi Companion (page 48)"
 },
 {
  "number": 22,
  "name": "Instinctive Astrogation (Sense Variation)",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "Moderate, modified by journey difficulty: Very Easy/Easy/Moderate +0, Difficult +5, Very Difficult +10, Heroic +15.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The better-known ability to calculate hyperspace routes without a nav computer. The Jedi uses sense to feel through the myriad possible routes to determine the safest path. If successful, only an Easy astrogation roll is needed to plot the route. If the sense roll fails, astrogation difficulty becomes Very Difficult. If missed by 5+, astrogation difficulty becomes Heroic.",
  "source": "Tales of the Jedi Companion (page 48-49)"
 },
 {
  "number": 23,
  "name": "Life Detection",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy if subject has Force skills or is Force-sensitive; Moderate if not. Modified by relationship.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Detects live sentient beings who might otherwise remain hidden. When activated, the Jedi knows the location of all sentients within 10 meters. If kept up, the Jedi knows whenever a sentient approaches within 10 meters. Each creature makes an opposed control or Perception roll to avoid detection (these rolls don't count as actions). If the Jedi beats the target's roll by 10+, she is aware if the person has Force skills, is Force-sensitive, if she has met them before, and their identity.",
  "source": "R&E (page 146)"
 },
 {
  "number": 24,
  "name": "Life Sense",
  "category": "Sense",
  "prereqs": "23",
  "darkSide": false,
  "difficulty": "Very Easy. Modified by proximity and relationship.",
  "timeToUse": "",
  "keepUp": "Yes (to track a target)",
  "effect": "The user can sense the presence and identity of a specific person for whom she searches. The user can sense how badly wounded, diseased, or otherwise physically disturbed the target is. A target may hide identity from the Jedi by rolling control skill and adding it to the difficulty.",
  "source": "R&E (page 146)"
 },
 {
  "number": 25,
  "name": "Life Web",
  "category": "Sense",
  "prereqs": "23,24,30",
  "darkSide": false,
  "difficulty": "Depends on nearest population size: Very Easy for tens of billions; Easy for billions; Moderate for hundreds of millions; Difficult for tens of millions; Very Difficult for millions; Heroic for hundreds of thousands. Cannot detect populations under 100,000. Modified by proximity.",
  "timeToUse": "Two days (each additional 2 days adds +1D to sense roll)",
  "keepUp": "No",
  "effect": "Detects large concentrations of a specific species. The Jedi senses general direction toward the population. Beat difficulty by 10+: approximate distance (hundreds/thousands of km, or tens/hundreds/thousands of light-years). Force-user must choose one specific species as specialization when selecting this power. Additional species cost 3 Character Points each. Must be familiar with the species (spent time with a member). Requires at least 2 days continuous concentration.",
  "source": "Tales of the Jedi Companion (page 49)"
 },
 {
  "number": 26,
  "name": "Magnify Senses",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy. Modified by proximity.",
  "timeToUse": "Three rounds",
  "keepUp": "No",
  "effect": "Increases the effectiveness of normal senses to perceive things that would otherwise require artificial aids. Can hear noises beyond normal hearing due to distance or softness (not beyond normal frequencies). Can see normally visible things over distances requiring macrobinoculars. Can identify scents and odors normally too faint for human olfactory senses.",
  "source": "R&E (page 146)"
 },
 {
  "number": 27,
  "name": "Postcognition",
  "category": "Sense",
  "prereqs": "11,23,30",
  "darkSide": false,
  "difficulty": "Easy for less than 2 hours; Moderate for 2 hours to 1 week; Difficult for 1 week to 6 months; Very Difficult for 6 months to 1 year; Heroic for 1-2 years; +10 per additional year.",
  "timeToUse": "Five minutes (+10 difficulty per minute cut, minimum 1 minute)",
  "keepUp": "No",
  "effect": "Investigates Force imprints left on objects by living beings. Must handle the target object. Must declare how far back to look before rolling. Roll vs 3x difficulty: witness events as if present (crystal clear). Roll vs 2x difficulty: good impression but primary sense is wavery/obscured, other senses clear. Roll vs 1x difficulty: all senses muffled, vague impressions of who handled the object and what transpired.",
  "source": "R&E (page 146-147)"
 },
 {
  "number": 28,
  "name": "Predict Natural Disaster",
  "category": "Sense",
  "prereqs": "21,23,26,35",
  "darkSide": false,
  "difficulty": "Easy if lived in area 1+ year; Moderate for 6-12 months; Difficult for 1-6 months; Very Difficult for less than 1 month. Modified by disaster severity (larger = easier) and predictability.",
  "timeToUse": "15 minutes (may reduce in 5-min increments by increasing difficulty one level per increment, minimum 1 minute)",
  "keepUp": "No",
  "effect": "Senses local meteorological and geological conditions to predict imminent disasters: earthquakes, volcanic eruptions, floods, landslides, avalanches, cave-ins, tornadoes, hurricanes, etc. Similar to how animals sense earthquakes hours or days before. Takes weeks to learn local patterns. Prediction effective for 12 hours; difficulty increases one level per additional 12-hour extension.",
  "source": "Jedi Academy Sourcebook (page 45)"
 },
 {
  "number": 29,
  "name": "Receptive Telepathy",
  "category": "Sense",
  "prereqs": "23,24",
  "darkSide": false,
  "difficulty": "Very Easy for friendly, non-resisting targets. Resisting target makes Perception or control roll as difficulty. Modified by proximity and relationship.",
  "timeToUse": "",
  "keepUp": "Yes (if target willing and proximity modifier doesn't increase)",
  "effect": "Reads surface thoughts and emotions of the target \u2014 'hears' what the target is thinking but cannot probe deeper. If sense roll doubles the difficulty, can sift through memories up to 24 hours old (takes a full round, cannot be done in the same round as contact). Can read multiple minds simultaneously but each additional target requires a new roll. Works on creatures and sentient species but not droids.",
  "source": "R&E (page 146)"
 },
 {
  "number": 30,
  "name": "Sense Force",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate for an area; Difficult for sensing details or specific objects/Force-users within the area. Modified by proximity.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Senses the ambient Force within a place. Cannot specifically detect sentient beings. Tells the character: rough magnitude of the Force (rich, moderate, or poor), rough type and quantity of life-forms, and whether the area tends toward dark or light side (e.g., the dark side tree on Dagobah). An area rich in negative or positive energies may indicate past events or activities of past inhabitants. The Jedi may also receive vague premonitions ('I sense something wrong,' 'I sense a great impending tragedy').",
  "source": "Tales of the Jedi Companion (page 50)"
 },
 {
  "number": 31,
  "name": "Sense Force Potential",
  "category": "Sense",
  "prereqs": "23,24,29,30",
  "darkSide": false,
  "difficulty": "Moderate for friendly, non-resisting targets. Moderate plus target's Perception or control roll (whichever is higher) for unwilling subjects.",
  "timeToUse": "Six rounds",
  "keepUp": "No",
  "effect": "Probes the mind of a target to determine Force potential. Force-sensitive people have an involuntary subconscious shield that pushes back against intruders. The magnitude of the backlash indicates Force strength: merely Force-sensitive = shoved back several feet; actual Force skills with little training = sent reeling across the room; well-trained or great raw talent = sent flying across the room.",
  "source": "Tales of the Jedi Companion (page 50)"
 },
 {
  "number": 32,
  "name": "Sense Path",
  "category": "Sense",
  "prereqs": "8,11",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Informs the character of the 'path' he travels: whether current actions lead toward the dark side, and whether specified future actions are likely to do so. Like farseeing without control \u2014 the Jedi cannot choose to see past, present, or future; visions are allegorical rather than specific. Can tell a Jedi with Dark Side Points how successful atonement has been. Can be used consciously or as a GM plot device \u2014 to warn, encourage, provide hints, or foreshadow events. Different Jedi receive different renditions of the same scene. The path of darkness may be clear but the light may be elusive. A skilled Dark Jedi can twist the readings to suit their own ends.",
  "source": "Tales of the Jedi Companion (page 50-51)"
 },
 {
  "number": 33,
  "name": "Shift Sense",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "Moderate for simple phenomena (heat, simple scents); Difficult for uncommon phenomena (comm frequencies, infrared); Very Difficult for specific complex phenomena (detecting Tibanna gas by scent).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "The character may shift senses to detect phenomena of a different type than normal \u2014 infrared vision, frequencies above or below normal range, etc. This power counts as a 'skill use' for determining die code penalties. Note: useful but limited. For example, a Jedi may detect comm frequencies but cannot listen in on the transmission. Can detect a transmission is present but may not locate the source, and certainly cannot decode the information.",
  "source": "Tales of the Jedi Companion (page 51-52)"
 },
 {
  "number": 34,
  "name": "Translation",
  "category": "Sense",
  "prereqs": "24,29,43",
  "darkSide": false,
  "difficulty": "Moderate for humans or aliens; Difficult for droids. +5 if target is being purposely cryptic; +20 if the language is written.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Translates a language and allows the Jedi to speak it. Can decipher body language, spoken words, or ancient texts. Must first hear the target speak or see written form. One application to 'understand' a language \u2014 as long as all speakers use the same language and the power is kept up, no additional rolls needed. Droids can be communicated with since they 'speak' using beeps and whistles. Note: the character does not truly know the language \u2014 once the power drops, the Jedi cannot understand or speak it again.",
  "source": "Tales of the Jedi Companion (page 52)"
 },
 {
  "number": 35,
  "name": "Weather Sense",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy if lived in area 1+ year; Moderate for 6-12 months; Difficult for 1-6 months; Very Difficult for less than 1 month. Modified by proximity and local meteorological conditions.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Attunes the Jedi to local weather patterns by sensing movements of clouds, winds, tides, and solar bodies. Can discern patterns and make limited predictions about atmospheric phenomena. Usually takes weeks to become accustomed to local patterns and topography for accurate readings. Prediction effective for 4 hours; difficulty increases for more extended forecasts.",
  "source": "Tales of the Jedi Companion (page 52)"
 },
 {
  "number": 36,
  "name": "Bolt of Hatred",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 37,
  "name": "Dark Side Web",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 38,
  "name": "Injure/Kill",
  "category": "Alter",
  "prereqs": "23,24",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 39,
  "name": "Telekinesis",
  "category": "Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 40,
  "name": "Farseeing",
  "category": "Control+Sense",
  "prereqs": "24",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 41,
  "name": "Life Bond",
  "category": "Control+Sense",
  "prereqs": "23,24,26,29",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 42,
  "name": "Lightsaber Combat",
  "category": "Control+Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 43,
  "name": "Projective Telepathy",
  "category": "Control+Sense",
  "prereqs": "23,24,29",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 44,
  "name": "Accelerate Another's Healing",
  "category": "Control+Alter",
  "prereqs": "6,47",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 45,
  "name": "Aura of Uneasiness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 46,
  "name": "Control Another's Disease",
  "category": "Control+Alter",
  "prereqs": "2,5",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 47,
  "name": "Control Another's Pain",
  "category": "Control+Alter",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 48,
  "name": "Control Breathing",
  "category": "Control+Alter",
  "prereqs": "3,11,39",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 49,
  "name": "Detoxify Poison in Another",
  "category": "Control+Alter",
  "prereqs": "2,6,7,44,47",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 50,
  "name": "Electronic Manipulation",
  "category": "Control+Alter",
  "prereqs": "1,62",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 51,
  "name": "Feed on Dark Side",
  "category": "Control+Alter",
  "prereqs": "30",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 52,
  "name": "Force Lightning",
  "category": "Control+Alter",
  "prereqs": "1,38,53",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 53,
  "name": "Inflict Pain",
  "category": "Control+Alter",
  "prereqs": "6,24",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 54,
  "name": "Place Another in Hibernation Trance",
  "category": "Control+Alter",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 55,
  "name": "Remove Another's Fatigue",
  "category": "Control+Alter",
  "prereqs": "2,6,16,44,47",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 56,
  "name": "Return Another to Consciousness",
  "category": "Control+Alter",
  "prereqs": "6,15",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 57,
  "name": "Transfer Force",
  "category": "Control+Alter",
  "prereqs": "6,47",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 58,
  "name": "Waves of Darkness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 59,
  "name": "Dim Other's Senses",
  "category": "Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 60,
  "name": "Lesser Force Shield",
  "category": "Sense+Alter",
  "prereqs": "1,3,26,39",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 61,
  "name": "Force Wind",
  "category": "Sense+Alter",
  "prereqs": "26,33,39",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 62,
  "name": "Affect Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 63,
  "name": "Battle Meditation",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 64,
  "name": "Control Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 29,39,62",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 65,
  "name": "Create Force Storms",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 11,12,13,23,24,26,29,30,39,40,43",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 66,
  "name": "Doppleganger",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,8,23,24,26,29,30,39,43,47,57,59,62",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 67,
  "name": "Drain Life Energy",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,16,23,24,26,30,47",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 68,
  "name": "Drain Life Essence",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,11,23,24,26,29,30,39,40,43,47,57,59,62,64",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 69,
  "name": "Enhance Coordination",
  "category": "Control+Sense+Alter",
  "prereqs": "24,62",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 70,
  "name": "Force Harmony",
  "category": "Control+Sense+Alter",
  "prereqs": "23,24,29,43",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 71,
  "name": "Memory Wipe",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,11,23,24,26,29,30,39,40,43,59,62,64",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 72,
  "name": "Projected Fighting",
  "category": "Control+Sense+Alter",
  "prereqs": "3,39",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 73,
  "name": "Telekinetic Kill",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,24,38,53",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 74,
  "name": "Transfer Life",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 1,2,6,7,8,11,14,15,17,23,24,26,29,30,38,39,40,43,44,47,51,53,56,57,59,62,64",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 75,
  "name": "Force Scream",
  "category": "Special",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 76,
  "name": "Lifemerge",
  "category": "Special",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 }
];
