const LIBRARY_DATA = {
  categories: [
    {
      id: "core-rulebooks",
      name: "Core Rulebooks",
      items: [
        { wegNum: "40001", title: "Star Wars: The Roleplaying Game", edition: "1st", year: 1987, pages: 144, format: "Hardcover" },
        { wegNum: "40043", title: "The Star Wars Rules Companion", edition: "1st", year: 1989, pages: 80, format: "Softcover" },
        { wegNum: "40055", title: "Star Wars: The Roleplaying Game, Second Edition", edition: "2nd", year: 1992, pages: 176, format: "Hardcover" },
        { wegNum: "40064", title: "Gamemaster Screen (Second Edition)", edition: "2nd", year: 1992, pages: 48, format: "Screen" },
        { wegNum: "40065", title: "Gamemaster Handbook", edition: "2nd", year: 1993, pages: 144, format: "Softcover" },
        { wegNum: "40120", title: "Star Wars: The Roleplaying Game, Second Edition, Revised and Expanded", edition: "2nd R&E", year: 1996, pages: 288, format: "Hardcover" },
        { wegNum: "40135", title: "Gamemaster Screen, Revised", edition: "2nd R&E", year: 1996, format: "Screen" },
        { wegNum: "40602", title: "Star Wars Introductory Adventure Game", year: 1997, format: "Boxed Set" }
      ]
    },
    {
      id: "sourcebooks",
      name: "Sourcebooks",
      items: [
        { wegNum: "40002", title: "The Star Wars Sourcebook", edition: "1st", year: 1987, pages: 144, format: "Hardcover" },
        { wegNum: "40006", title: "Imperial Sourcebook", edition: "1st", year: 1989, pages: 144, format: "Hardcover" },
        { wegNum: "40007", title: "Rebel Alliance Sourcebook", edition: "1st", year: 1990, pages: 144, format: "Hardcover" },
        { wegNum: "40008", title: "Death Star Technical Companion", edition: "1st", year: 1991, pages: 96, format: "Softcover" },
        { wegNum: "40042", title: "Han Solo and the Corporate Sector Sourcebook", edition: "1st", year: 1993, pages: 128, format: "Softcover" },
        { wegNum: "40046", title: "Cracken's Rebel Field Guide", edition: "1st", year: 1991, pages: 80, format: "Softcover" },
        { wegNum: "40050", title: "Planets of the Galaxy, Volume One", edition: "1st", year: 1991, pages: 80, format: "Softcover" },
        { wegNum: "40054", title: "Rebel Alliance Sourcebook (softcover reprint)", edition: "1st", year: 1990, pages: 144, format: "Softcover", notes: "Reprint of 1st ed" },
        { wegNum: "40056", title: "Heir to the Empire Sourcebook", edition: "2nd", year: 1992, pages: 144, format: "Hardcover" },
        { wegNum: "40057", title: "Planets of the Galaxy, Volume Two", edition: "2nd", year: 1992, pages: 80, format: "Softcover" },
        { wegNum: "40058", title: "Dark Force Rising Sourcebook", edition: "2nd", year: 1992, pages: 142, format: "Hardcover" },
        { wegNum: "40059", title: "The Last Command Sourcebook", edition: "2nd", year: 1994, pages: 142, format: "Hardcover" },
        { wegNum: "40068", title: "Heir to the Empire Sourcebook (softcover)", edition: "2nd", year: 1992, pages: 144, format: "Softcover", notes: "Softcover reprint" },
        { wegNum: "40071", title: "Dark Empire Sourcebook", edition: "2nd", year: 1993, pages: 128, format: "Hardcover" },
        { wegNum: "40072", title: "Planets of the Galaxy, Volume Three", edition: "2nd", year: 1993, pages: 96, format: "Softcover" },
        { wegNum: "40074", title: "Dark Force Rising Sourcebook (softcover)", edition: "2nd", year: 1993, pages: 144, format: "Softcover", notes: "Softcover reprint" },
        { wegNum: "40076", title: "Movie Trilogy Sourcebook", edition: "2nd", year: 1993, pages: 160, format: "Hardcover" },
        { wegNum: "40080", title: "Creatures of the Galaxy", edition: "2nd", year: 1994, pages: 96, format: "Softcover" },
        { wegNum: "40082", title: "Tales of the Jedi Companion", edition: "2nd R&E", year: 1996, pages: 144, format: "Hardcover" },
        { wegNum: "40084", title: "Cracken's Rebel Operatives", edition: "2nd", year: 1994, pages: 96, format: "Softcover" },
        { wegNum: "40085", title: "The Truce at Bakura Sourcebook", edition: "2nd R&E", year: 1996, pages: 150, format: "Hardcover" },
        { wegNum: "40086", title: "Heroes & Rogues", edition: "2nd", year: 1995, pages: 128, format: "Softcover" },
        { wegNum: "40089", title: "Star Wars Trilogy Sourcebook, Special Edition", edition: "2nd R&E", year: 1997, pages: 192, format: "Hardcover" },
        { wegNum: "40091", title: "Rebel Alliance Sourcebook, Second Edition", edition: "2nd", year: 1994, pages: 144, format: "Hardcover" },
        { wegNum: "40092", title: "Imperial Sourcebook, Second Edition", edition: "2nd", year: 1994, pages: 144, format: "Hardcover" },
        { wegNum: "40093", title: "The Star Wars Sourcebook, Second Edition", edition: "2nd", year: 1994, pages: 144, format: "Hardcover" },
        { wegNum: "40098", title: "Goroth: Slave of the Empire", edition: "2nd", year: 1995, pages: 96, format: "Softcover" },
        { wegNum: "40100", title: "The Star Wars Planets Collection", edition: "2nd", year: 1994, pages: 128, format: "Softcover" },
        { wegNum: "40107", title: "Platt's Starport Guide", edition: "2nd", year: 1995, pages: 160, format: "Softcover" },
        { wegNum: "40109", title: "Alliance Intelligence Reports", edition: "2nd", year: 1995, pages: 96, format: "Softcover" },
        { wegNum: "40111", title: "Hideouts & Strongholds", edition: "2nd R&E", year: 1998, pages: 112, format: "Softcover" },
        { wegNum: "40113", title: "Rules of Engagement: The Rebel SpecForce Handbook", edition: "2nd R&E", year: 1997, pages: 128, format: "Softcover" },
        { wegNum: "40114", title: "The Jedi Academy Sourcebook", edition: "2nd R&E", year: 1996, pages: 144, format: "Hardcover" },
        { wegNum: "40116", title: "Cynabar's Fantastic Technology: Droids", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40122", title: "Shadows of the Empire Sourcebook", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40123", title: "Shadows of the Empire Sourcebook (Hardcover)", edition: "2nd R&E", year: 1996, pages: 128, format: "Hardcover" },
        { wegNum: "40131", title: "The Thrawn Trilogy Sourcebook", edition: "2nd R&E", year: 1996, pages: 248, format: "Softcover" },
        { wegNum: "40134", title: "Shadows of the Empire Planets Guide", edition: "2nd R&E", year: 1996, pages: 96, format: "Softcover" },
        { wegNum: "40139", title: "Cracken's Threat Dossier", edition: "2nd R&E", year: 1997, pages: 144, format: "Softcover" },
        { wegNum: "40141", title: "Platt's Smugglers Guide", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40143", title: "Pirates & Privateers", edition: "2nd R&E", year: 1997, pages: 128, format: "Softcover" },
        { wegNum: "40148", title: "X-wing Rogue Squadron Sourcebook", edition: "2nd R&E", year: 1997, pages: 144, format: "Softcover" },
        { wegNum: "40150", title: "Stock Ships", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40153", title: "Wretched Hives of Scum and Villainy", edition: "2nd R&E", year: 1997, pages: 128, format: "Softcover" },
        { wegNum: "40154", title: "The Black Sands of Socorro", edition: "2nd R&E", year: 1997, pages: 128, format: "Softcover" },
        { wegNum: "40155", title: "The Player's Guide to Tapani", edition: "2nd R&E", year: 1997, pages: 64, format: "Softcover" },
        { wegNum: "40158", title: "Gundark's Fantastic Technology: Personal Gear", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40166", title: "Alien Encounters", edition: "2nd R&E", year: 1998, pages: 128, format: "Softcover" },
        { wegNum: "40025", title: "Galladinium's Fantastic Technology", edition: "2nd", year: 1995, pages: 96, format: "Softcover" }
      ]
    },
    {
      id: "galaxy-guides",
      name: "Galaxy Guides",
      items: [
        { wegNum: "40038", title: "Galaxy Guide 1: A New Hope", edition: "1st", year: 1989, pages: 80, format: "Softcover" },
        { wegNum: "40023", title: "Galaxy Guide 2: Yavin and Bespin", edition: "1st", year: 1989, pages: 80, format: "Softcover" },
        { wegNum: "40039", title: "Galaxy Guide 3: The Empire Strikes Back", edition: "1st", year: 1989, pages: 80, format: "Softcover" },
        { wegNum: "40041", title: "Galaxy Guide 4: Alien Races", edition: "1st", year: 1989, pages: 80, format: "Softcover" },
        { wegNum: "40040", title: "Galaxy Guide 5: Return of the Jedi", edition: "1st", year: 1990, pages: 80, format: "Softcover" },
        { wegNum: "40027", title: "Galaxy Guide 6: Tramp Freighters", edition: "1st", year: 1990, pages: 80, format: "Softcover" },
        { wegNum: "40069", title: "Galaxy Guide 7: Mos Eisley", edition: "2nd", year: 1993, pages: 96, format: "Softcover" },
        { wegNum: "40061", title: "Galaxy Guide 8: Scouts", edition: "2nd", year: 1993, pages: 96, format: "Softcover" },
        { wegNum: "40063", title: "Galaxy Guide 9: Fragments from the Rim", edition: "2nd", year: 1993, pages: 96, format: "Softcover" },
        { wegNum: "40073", title: "Galaxy Guide 10: Bounty Hunters", edition: "2nd", year: 1993, pages: 128, format: "Softcover" },
        { wegNum: "40075", title: "Galaxy Guide 11: Criminal Organizations", edition: "2nd", year: 1994, pages: 96, format: "Softcover" },
        { wegNum: "40087", title: "Galaxy Guide 12: Aliens — Enemies and Allies", edition: "2nd", year: 1995, pages: 96, format: "Softcover" },
        { wegNum: "40094", title: "Galaxy Guide 4: Alien Races, Second Edition", edition: "2nd", year: 1994, pages: 96, format: "Softcover", notes: "Expanded reprint" },
        { wegNum: "40095", title: "Galaxy Guide 6: Tramp Freighters, Second Edition", edition: "2nd", year: 1994, pages: 96, format: "Softcover", notes: "Expanded reprint" },
        { wegNum: "40119", title: "Galaxy Guide 2: Yavin and Bespin, Second Edition", edition: "2nd", year: 1995, pages: 96, format: "Softcover", notes: "Expanded reprint" },
        { wegNum: "40124", title: "Galaxy Guide 1: A New Hope, Second Edition", edition: "2nd", year: 1995, pages: 96, format: "Softcover", notes: "Expanded reprint" },
        { wegNum: "40125", title: "Galaxy Guide 3: The Empire Strikes Back, Second Edition", edition: "2nd", year: 1995, pages: 96, format: "Softcover", notes: "Expanded reprint" },
        { wegNum: "40126", title: "Galaxy Guide 5: Return of the Jedi, Second Edition", edition: "2nd", year: 1995, pages: 96, format: "Softcover", notes: "Expanded reprint" }
      ]
    },
    {
      id: "adventures-1st",
      name: "Adventures (1st Edition)",
      items: [
        { wegNum: "40003", title: "Campaign Pack", edition: "1st", year: 1988, pages: 32, format: "Softcover" },
        { wegNum: "40005", title: "Tatooine Manhunt", edition: "1st", year: 1988, pages: 32, format: "Softcover" },
        { wegNum: "40009", title: "Strike Force: Shantipole", edition: "1st", year: 1988, pages: 32, format: "Softcover" },
        { wegNum: "40010", title: "Lightsaber Dueling Pack", edition: "1st", year: 1988, pages: 40, format: "Softcover" },
        { wegNum: "40011", title: "Starfighter Battle Book", edition: "1st", year: 1989, format: "Softcover" },
        { wegNum: "40016", title: "Starfall", edition: "1st", year: 1989, pages: 40, format: "Softcover" },
        { wegNum: "40017", title: "Battle for the Golden Sun", edition: "1st", year: 1988, pages: 40, format: "Softcover" },
        { wegNum: "40018", title: "Otherspace", edition: "1st", year: 1989, pages: 40, format: "Softcover" },
        { wegNum: "40019", title: "Graveyard of Alderaan", edition: "1st", year: 1991, pages: 64, format: "Softcover" },
        { wegNum: "40020", title: "Scavenger Hunt", edition: "1st", year: 1989, pages: 40, format: "Softcover" },
        { wegNum: "40029", title: "Riders of the Maelstrom", edition: "1st", year: 1989, pages: 40, format: "Softcover" },
        { wegNum: "40022", title: "Crisis on Cloud City", edition: "1st", year: 1989, pages: 40, format: "Softcover" },
        { wegNum: "40024", title: "Otherspace II: Invasion", edition: "1st", year: 1990, pages: 40, format: "Softcover" },
        { wegNum: "40030", title: "Black Ice", edition: "1st", year: 1990, pages: 40, format: "Softcover" },
        { wegNum: "40033", title: "The Game Chambers of Questal", edition: "1st", year: 1990, pages: 40, format: "Softcover" },
        { wegNum: "40034", title: "Domain of Evil", edition: "1st", year: 1991, pages: 64, format: "Softcover" },
        { wegNum: "40036", title: "The Isis Coordinates", edition: "1st", year: 1990, pages: 48, format: "Softcover" },
        { wegNum: "40037", title: "Death in the Undercity", edition: "1st", year: 1990, pages: 48, format: "Softcover" },
        { wegNum: "40048", title: "Gamemaster Kit", edition: "1st", year: 1991, pages: 64, format: "Softcover" },
        { wegNum: "40049", title: "Planet of the Mists", edition: "1st", year: 1991, pages: 48, format: "Softcover" },
        { wegNum: "40102", title: "Scoundrel's Luck", edition: "1st", year: 1990, pages: 80, format: "Softcover", notes: "Solo adventure book" },
        { wegNum: "40103", title: "Jedi's Honor", edition: "1st", year: 1990, pages: 80, format: "Softcover", notes: "Solo adventure book" }
      ]
    },
    {
      id: "adventures-2nd",
      name: "Adventures (2nd Edition)",
      items: [
        { wegNum: "40052", title: "Mission to Lianna", edition: "2nd", year: 1992, pages: 48, format: "Softcover" },
        { wegNum: "40053", title: "The Abduction", edition: "2nd", year: 1992, pages: 64, format: "Softcover" },
        { wegNum: "40060", title: "Twin Stars of Kira", edition: "2nd", year: 1993, pages: 64, format: "Softcover" },
        { wegNum: "40062", title: "Wanted by Cracken", edition: "2nd", year: 1993, pages: 96, format: "Softcover" },
        { wegNum: "40066", title: "Supernova", edition: "2nd", year: 1993, pages: 64, format: "Softcover" },
        { wegNum: "40067", title: "The Politics of Contraband", edition: "2nd", year: 1992, pages: 48, format: "Softcover" },
        { wegNum: "40077", title: "Flashpoint! Brak Sector", edition: "2nd", year: 1995, pages: 96, format: "Softcover" },
        { wegNum: "40083", title: "Classic Adventures", edition: "2nd", year: 1995, pages: 128, format: "Softcover" },
        { wegNum: "40108", title: "Classic Campaigns", edition: "2nd", year: 1995, pages: 128, format: "Softcover" },
        { wegNum: "40127", title: "Imperial Entanglements", edition: "2nd R&E", year: 1996, pages: 96, format: "Softcover" },
        { wegNum: "40128", title: "Classic Adventures, Volume Two", edition: "2nd", year: 1995, pages: 96, format: "Softcover" },
        { wegNum: "40129", title: "The Best of the Star Wars Adventure Journal, Volume 1", edition: "2nd R&E", year: 1996, format: "Hardcover" },
        { wegNum: "40130", title: "Live-Action Adventures", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40132", title: "Operation: Elrood", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40133", title: "Classic Adventures, Volume Three", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40136", title: "Secrets of the Sisar Run", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40137", title: "Instant Adventures", edition: "2nd R&E", year: 1997, pages: 68, format: "Softcover" },
        { wegNum: "40138", title: "Classic Adventures, Volume Four: The Best of the Adventure Journal", edition: "2nd R&E", year: 1997, pages: 144, format: "Softcover" },
        { wegNum: "40147", title: "Tapani Sector Instant Adventures", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40151", title: "No Disintegrations", edition: "2nd R&E", year: 1997, pages: 96, format: "Softcover" },
        { wegNum: "40152", title: "Live-Action Adventures Gamemaster Toolkit", edition: "2nd R&E", year: 1996, pages: 96, format: "Softcover" },
        { wegNum: "40165", title: "Classic Adventures, Volume Five", edition: "2nd R&E", year: 1998, pages: 128, format: "Softcover" },
        { wegNum: "40601", title: "Imperial Double-Cross", edition: "2nd R&E", year: 1997, format: "Softcover" }
      ]
    },
    {
      id: "adventure-journals",
      name: "Adventure Journals",
      items: [
        { wegNum: "41001", title: "Star Wars Adventure Journal #1", year: 1994, format: "Magazine" },
        { wegNum: "41002", title: "Star Wars Adventure Journal #2", year: 1994, format: "Magazine" },
        { wegNum: "41003", title: "Star Wars Adventure Journal #3", year: 1994, format: "Magazine" },
        { wegNum: "41004", title: "Star Wars Adventure Journal #4", year: 1994, format: "Magazine" },
        { wegNum: "41005", title: "Star Wars Adventure Journal #5", year: 1995, format: "Magazine" },
        { wegNum: "41006", title: "Star Wars Adventure Journal #6", year: 1995, format: "Magazine" },
        { wegNum: "41007", title: "Star Wars Adventure Journal #7", year: 1995, format: "Magazine" },
        { wegNum: "41008", title: "Star Wars Adventure Journal #8", year: 1995, format: "Magazine" },
        { wegNum: "41009", title: "Star Wars Adventure Journal #9", year: 1996, format: "Magazine" },
        { wegNum: "41010", title: "Star Wars Adventure Journal #10", year: 1996, format: "Magazine" },
        { wegNum: "41011", title: "Star Wars Adventure Journal #11", year: 1996, format: "Magazine" },
        { wegNum: "41012", title: "Star Wars Adventure Journal #12", year: 1997, format: "Magazine" },
        { wegNum: "41013", title: "Star Wars Adventure Journal #13", year: 1997, format: "Magazine" },
        { wegNum: "41014", title: "Star Wars Adventure Journal #14", year: 1997, format: "Magazine" },
        { wegNum: "41015", title: "Star Wars Adventure Journal #15", year: 1997, format: "Magazine" },
        { wegNum: "41016", title: "Star Wars Adventure Journal #16", year: 1998, format: "Magazine" },
        { wegNum: "41017", title: "Star Wars Adventure Journal #17", year: 1998, format: "Magazine", notes: "Final published issue" }
      ]
    },
    {
      id: "boxed-sets",
      name: "Boxed Sets & Campaigns",
      items: [
        { wegNum: "40209", title: "The DarkStryder Campaign", edition: "2nd", year: 1995, format: "Boxed Set" },
        { wegNum: "40118", title: "The DarkStryder Campaign: The Kathol Outback", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40121", title: "The DarkStryder Campaign: The Kathol Rift", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40112", title: "The DarkStryder Campaign: Endgame", edition: "2nd R&E", year: 1996, pages: 128, format: "Softcover" },
        { wegNum: "40215", title: "Lords of the Expanse", edition: "2nd R&E", year: 1997, format: "Boxed Set" },
        { wegNum: "40212", title: "Mos Eisley Adventure Set", edition: "2nd R&E", year: 1997, format: "Boxed Set" },
        { wegNum: "40044", title: "Star Wars Miniatures Battles", edition: "1st", year: 1991, pages: 116, format: "Softcover" },
        { wegNum: "40070", title: "Star Wars Miniatures Companion", edition: "2nd", year: 1994, pages: 96, format: "Softcover" },
        { wegNum: "40090", title: "Star Wars Miniatures Battles, Second Edition", edition: "2nd", year: 1993, format: "Softcover" }
      ]
    }
  ]
};
