const WEAPONS_DATA = [
 {
  "name": "Anti-Orbital Ion Cannon",
  "category": "Artillery",
  "skill": "\u2014",
  "cost": "\u2014",
  "availability": "X",
  "damage": "Variable",
  "range": "Surface to orbit",
  "ammo": "Power generator",
  "game_notes": "Planetary defense ion cannon. Capital scale. Like the v-150 Planet Defender on Hoth.",
  "source": ""
 },
 {
  "name": "Atgar 1.4 FD P-Tower",
  "category": "Artillery",
  "skill": "Blaster artillery: anti-vehicle",
  "cost": "10,000 (2,000 used)",
  "availability": "2, R or X",
  "damage": "2D+2 (Speeder scale)",
  "range": "10-500/2/10km",
  "ammo": "Power generator",
  "game_notes": "Crew: 4 (skeleton 2/+10). FC 1D. Body 2D. Light anti-vehicle laser cannon.",
  "source": "Rulebook (page 233)"
 },
 {
  "name": "Golan Arms DF.9 Anti-Infantry Battery",
  "category": "Artillery",
  "skill": "Blaster artillery: anti-infantry",
  "cost": "15,000 (9,500 used)",
  "availability": "2, R or X",
  "damage": "4D (Speeder scale)",
  "range": "20-600/3/16km",
  "ammo": "Power generator",
  "game_notes": "Crew: 3. FC 2D. Body 3D. Fire Rate 2. 8m blast radius.",
  "source": "Imperial Sourcebook (page 118)"
 },
 {
  "name": "Repeating Blaster Turret",
  "category": "Artillery",
  "skill": "Vehicle blasters: repeating",
  "cost": "8,000 (5,000 used)",
  "availability": "R or X",
  "damage": "6D",
  "range": "3-50/120/300",
  "ammo": "Power generator",
  "game_notes": "Crew: 1 or automated. FC 2D (-1D automated). Body 4D. Character scale.",
  "source": "Hideouts & Strongholds (page 78)"
 },
 {
  "name": "Shoulder-Launched Ion Cannon",
  "category": "Artillery",
  "skill": "Missile weapons",
  "cost": "\u2014",
  "availability": "2, R",
  "damage": "4D ionization (Speeder scale)",
  "range": "\u2014",
  "ammo": "\u2014",
  "game_notes": "Portable anti-vehicle ion weapon.",
  "source": ""
 },
 {
  "name": "Speizoc v-188 Penetrator",
  "category": "Artillery",
  "skill": "Blaster artillery: anti-vehicle",
  "cost": "120,000 (60,000 used)",
  "availability": "3, X",
  "damage": "7D/5D+2/3D+2 (Speeder scale)",
  "range": "50-600/5/25km",
  "ammo": "6 cells / 50 trailer / generator",
  "game_notes": "Crew: 8. FC 1D. Body 3D+1. Fire Rate 1/3. 20m blast radius. Heavy anti-vehicle gun.",
  "source": "Imperial Sourcebook (page 119)"
 },
 {
  "name": "Turbolaser Battery",
  "category": "Artillery",
  "skill": "Blaster artillery",
  "cost": "\u2014",
  "availability": "X",
  "damage": "7D (Speeder scale)",
  "range": "",
  "ammo": "Power generator",
  "game_notes": "Heavy ground-based turbolaser emplacement.",
  "source": ""
 },
 {
  "name": "BlasTech Sharpshooter V",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "1,200",
  "availability": "2, X",
  "damage": "4D+1",
  "range": "3-30/80/350",
  "ammo": "100",
  "game_notes": "",
  "source": "Imperial Sourcebook (page 129)"
 },
 {
  "name": "E-5 Droid Blaster",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "900",
  "availability": "1, R",
  "damage": "5D",
  "range": "3-20/60/210",
  "ammo": "100",
  "game_notes": "Baktoid Armor Workshop. Standard battle droid weapon.",
  "source": "Arms and Equipment Guide (page 15)"
 },
 {
  "name": "N'gant-Zarvel 9118",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "1,000",
  "availability": "2",
  "damage": "5D+1",
  "range": "3-25/50/200",
  "ammo": "100",
  "game_notes": "Heavy carbine.",
  "source": "Rules of Engagement (page 62)"
 },
 {
  "name": "Slavemaster Stun Carbine",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "4,000",
  "availability": "3, R",
  "damage": "6D stun",
  "range": "3-10/30/120",
  "ammo": "100",
  "game_notes": "Trandoshan. Pulse can widen to 2 targets (multi-action penalties apply).",
  "source": "Ultimate Alien Anthology (page 167)"
 },
 {
  "name": "SoroSuub QuickSnap 36T",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "900",
  "availability": "2, F/R/X",
  "damage": "5D",
  "range": "3-25/50/250",
  "ammo": "100",
  "game_notes": "+5 difficulty at long range.",
  "source": "Rulebook (page 231)"
 },
 {
  "name": "Stormtrooper Two Carbine",
  "category": "Blaster Carbines",
  "skill": "Blaster: blaster carbine",
  "cost": "2,400",
  "availability": "2, R or X",
  "damage": "6D+2",
  "range": "3-30/50/200",
  "ammo": "100",
  "game_notes": "",
  "source": "Galaxy Guide 9 (page 27)"
 },
 {
  "name": "BlasTech DC-15s Sidearm",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "1,300",
  "availability": "3, R or X",
  "damage": "3D",
  "range": "3-10/30/120",
  "ammo": "20",
  "game_notes": "Dynamic power cell adds 2 charges/round not fired (up to max).",
  "source": ""
 },
 {
  "name": "BlasTech DH-17",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "800",
  "availability": "2, R",
  "damage": "4D",
  "range": "5-15/30/120",
  "ammo": "100",
  "game_notes": "FC 1D. Difficult repair to modify for burst fire (+3D blaster but can't dodge, 20sec burst then useless).",
  "source": "Star Wars Trilogy Sourcebook SE (pages 153-154)"
 },
 {
  "name": "BlasTech DL-18",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "500",
  "availability": "1, F/R/X",
  "damage": "4D",
  "range": "3-10/30/120",
  "ammo": "100",
  "game_notes": "Standard blaster pistol.",
  "source": "Rulebook (pages 229/231)"
 },
 {
  "name": "BlasTech DL-22",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "500",
  "availability": "1, F/R/X",
  "damage": "4D+1",
  "range": "3-10/30/120",
  "ammo": "100",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 26)"
 },
 {
  "name": "Bryar Pistol",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "1,000",
  "availability": "4, R",
  "damage": "3D",
  "range": "3-20/50/200",
  "ammo": "100",
  "game_notes": "Sawed-off blaster rifle.",
  "source": "Wizards Website"
 },
 {
  "name": "Caelli-Merced Series III",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "900",
  "availability": "4, R",
  "damage": "4D+2",
  "range": "3-10/30/120",
  "ammo": "100",
  "game_notes": "Precision weapon. +5 difficulty if blaster <4D, +1D to hit if blaster 6D+.",
  "source": "Black Sands of Socorro (page 75)"
 },
 {
  "name": "EA SBP-200",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "300",
  "availability": "1, F",
  "damage": "3D",
  "range": "3-10/30/120",
  "ammo": "100",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 8)"
 },
 {
  "name": "Merr-Sonn 434 DeathHammer",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "850",
  "availability": "1, F or R",
  "damage": "5D+1",
  "range": "2-8/20/80",
  "ammo": "100",
  "game_notes": "",
  "source": "Galaxy Guide 9 (page 11)"
 },
 {
  "name": "Merr-Sonn Intimidator IR-5",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "1,250",
  "availability": "3, X",
  "damage": "3D",
  "range": "3-7/25/50",
  "ammo": "50",
  "game_notes": "Rapid-fire. FC 2D (multiple targets in 90\u00b0 arc only). Retractable stock (+1D aiming 1 round, +200cr).",
  "source": "Galladinium's Fantastic Technology (page 71)"
 },
 {
  "name": "Merr-Sonn Model 44",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "500",
  "availability": "1, F or R",
  "damage": "4D",
  "range": "3-10/30/100",
  "ammo": "100",
  "game_notes": "",
  "source": "Galaxy Guide 9 (page 14)"
 },
 {
  "name": "SoroSuub ELG-3A Diplomat's Blaster",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "500",
  "availability": "1, F",
  "damage": "4D",
  "range": "3-10/30/120",
  "ammo": "50",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 10)"
 },
 {
  "name": "Westar-34",
  "category": "Blaster Pistols",
  "skill": "Blaster: blaster pistol",
  "cost": "750",
  "availability": "3, R",
  "damage": "4D",
  "range": "3-10/20/100",
  "ammo": "100",
  "game_notes": "+1D to quickdraw. Highly heat-resistant.",
  "source": ""
 },
 {
  "name": "BlasTech DL-68 Cutting Blaster",
  "category": "Blaster Pistols",
  "skill": "Blaster: cutting blaster (-1D due to inaccuracy)",
  "cost": "",
  "availability": "",
  "damage": "5D",
  "range": "2-4/7/10",
  "ammo": "50",
  "game_notes": "Used for clearing brush or making a trail. 4-hour recharge time.",
  "source": "WEG40061 Galaxy Guide 8: Scouts"
 },
 {
  "name": "BlasTech A280",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,400",
  "availability": "1, R",
  "damage": "5D+2",
  "range": "4-40/120/300",
  "ammo": "100",
  "game_notes": "Rebel Alliance standard issue.",
  "source": "Rebel Alliance Sourcebook (pages 99-100)"
 },
 {
  "name": "BlasTech A295",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,500",
  "availability": "1, R",
  "damage": "5D+1",
  "range": "5-50/170/380",
  "ammo": "100",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "BlasTech DC-15 Clone Rifle",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,500",
  "availability": "3, R or X",
  "damage": "5D+1",
  "range": "10-40/130/350",
  "ammo": "100",
  "game_notes": "Assault blaster rifle.",
  "source": ""
 },
 {
  "name": "BlasTech DC-17m ICWS",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle / Missile weapons",
  "cost": "1,900",
  "availability": "3, R or X",
  "damage": "5D (blaster) / 5D (sniper) / 7D/5D/3D (anti-armor)",
  "range": "Varies by attachment",
  "ammo": "60/20/4",
  "game_notes": "Interchangeable: blaster, sniper (FC 1D), anti-armor grenade launcher. 1 action to swap.",
  "source": ""
 },
 {
  "name": "BlasTech DLT-19",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,300",
  "availability": "1, R",
  "damage": "5D",
  "range": "5-50/180/350",
  "ammo": "100",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "BlasTech DLT-20A",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,300",
  "availability": "1, R",
  "damage": "5D+1",
  "range": "4-35/110/280",
  "ammo": "100",
  "game_notes": "",
  "source": "Arms and Equipment Guide (pages 15-16)"
 },
 {
  "name": "BlasTech E-11",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,000",
  "availability": "1, R",
  "damage": "5D",
  "range": "3-30/100/300",
  "ammo": "100",
  "game_notes": "Retractable stock + scope: +1D blaster with 1 round aiming. Standard Imperial issue.",
  "source": "Gundark's Fantastic Technology (page 31)"
 },
 {
  "name": "Modified BlasTech E-11/S",
  "category": "Blaster Rifles",
  "skill": "Blaster (blaster mode), Firearms (slug-thrower mode)",
  "cost": "7,000",
  "availability": "X, 4",
  "damage": "5D (blaster) / 4D (slug-thrower)",
  "range": "3-30/100/300 (blaster), 3-30/150/400 (slug-thrower)",
  "ammo": "25 (blaster), 6 (slug-thrower)",
  "game_notes": "Modified blaster/slug-thrower combo weapon. Dual firing modes with separate ammo supplies.",
  "source": "WEG40075 Galaxy Guide 11: Criminal Organizations p.81"
 },
 {
  "name": "BlasTech EE-3",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,300",
  "availability": "2, R",
  "damage": "5D+2",
  "range": "3-30/80/250",
  "ammo": "50",
  "game_notes": "Boba Fett's base model.",
  "source": ""
 },
 {
  "name": "Boba Fett's Blaster Rifle",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "Not for sale",
  "availability": "2, R",
  "damage": "6D",
  "range": "3-30/120/350",
  "ammo": "30",
  "game_notes": "Pistol grip (one-hand, no penalty). Scomp-link to helmet (+1D blaster, cumulative). Night-scope (-1 level at night with 1 round aim). Motion sensor (+1D search).",
  "source": "Star Wars Trilogy Sourcebook SE (page 152)"
 },
 {
  "name": "Espo Riot Gun",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,500",
  "availability": "2, R",
  "damage": "5D+1",
  "range": "3-30/100/300",
  "ammo": "300",
  "game_notes": "Constant-fire: 5 blasts/shot, 6 shots/round. Once hit established, following shots vs adjacent targets -1 difficulty.",
  "source": "Gundark's Fantastic Technology (page 32)"
 },
 {
  "name": "Exotac Arms Predator",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "7,000",
  "availability": "4, X",
  "damage": "7D",
  "range": "3-30/80/350",
  "ammo": "8",
  "game_notes": "FC 2D (dual-laser targeting). Moderate STR to control recoil each shot.",
  "source": "Gundark's Fantastic Technology (page 33)"
 },
 {
  "name": "Merr-Sonn G8",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,250",
  "availability": "1, R",
  "damage": "5D+1",
  "range": "4-40/120/350",
  "ammo": "100",
  "game_notes": "",
  "source": "Rebel Alliance Sourcebook (pages 99-100)"
 },
 {
  "name": "SoroSuub Heavy Tracker 16",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,000",
  "availability": "1, R",
  "damage": "5D",
  "range": "3-30/100/300",
  "ammo": "100",
  "game_notes": "",
  "source": "Rebel Alliance Sourcebook (pages 99-100)"
 },
 {
  "name": "Stormtrooper One / Freedom One",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,000",
  "availability": "2, X",
  "damage": "5D",
  "range": "3-30/100/300",
  "ammo": "100",
  "game_notes": "Stock + scope: +1D with 1 round aiming.",
  "source": "Rulebook (page 231)"
 },
 {
  "name": "Prax Arms AXM-50 \"Blast and Smash\"",
  "category": "Blaster Rifles",
  "skill": "Blaster: blaster rifle / Missile weapons: micro-grenade launcher",
  "cost": "4,500 (250/bi-pod, 1,000/grenade magazine, 100/power pack, 500/backpack generator)",
  "availability": "3, F or R",
  "damage": "5D (blaster) / 4D/3D/2D (micro-grenade)",
  "range": "3-25/50/75 (blaster), 5-25/100/200 (grenade)",
  "ammo": "250 (blaster), 30 (micro-grenade magazine)",
  "game_notes": "Combined blaster rifle and micro-grenade launcher. Fire rate 7 (blaster), 1 (grenade). Grenade blast radius 0-2/4/6. Computerized grenade fire control: Moderate Perception roll (free action) adds +1D to hit; automatic +1D for 2nd and following shots at same target. Bi-pod adds +1D to blaster roll.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.83"
 },
 {
  "name": "Combat Gloves",
  "category": "Brawling Weapons",
  "skill": "Brawling",
  "cost": "200",
  "availability": "1, F",
  "damage": "STR+2",
  "range": "",
  "ammo": "",
  "game_notes": "Heavy weighted gloves that add more impact to unarmed attacks.",
  "source": "d20 Core Rulebook (pages 131/133)"
 },
 {
  "name": "Fighting Claws",
  "category": "Brawling Weapons",
  "skill": "Brawling",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "STR+1D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Yuuzhan Vong retractable bone spurs implanted in knuckles, elbows, knees. Easy willpower to extend.",
  "source": "New Jedi Order Sourcebook (page 103)"
 },
 {
  "name": "Juggernaut Droid Arm",
  "category": "Brawling Weapons",
  "skill": "Brawling/Blaster",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "STR+2D+1 (max 6D) / 5D (blaster)",
  "range": "3-7/25/50 (blaster)",
  "ammo": "25 (blaster)",
  "game_notes": "Custom cybernetic. Arm has 6D body to resist damage. Includes built-in blaster.",
  "source": "Gamer Magazine"
 },
 {
  "name": "Neuro-Shock Hand",
  "category": "Brawling Weapons",
  "skill": "Brawling",
  "cost": "1,000 + 300/pip",
  "availability": "\u2014",
  "damage": "Replaces STR for brawling",
  "range": "",
  "ammo": "",
  "game_notes": "Cybernetic prosthetic. Damage replaces user's STR code. Must buy at least enough to match STR. Shock released on heavy impact.",
  "source": "Cracken's Rebel Field Guide (page 40)"
 },
 {
  "name": "Repulse-Hand",
  "category": "Brawling Weapons",
  "skill": "Repulse-hand",
  "cost": "1,500 min + 300/pip",
  "availability": "\u2014",
  "damage": "Repulse-hand skill + 1D",
  "range": "",
  "ammo": "",
  "game_notes": "Cybernetic. Gains repulse-hand skill at 0D. Replaces brawling/brawling parry. Skill and damage set at purchase, cannot be improved.",
  "source": "Cracken's Rebel Field Guide (page 41)"
 },
 {
  "name": "Shockboxing Gloves",
  "category": "Brawling Weapons",
  "skill": "Brawling",
  "cost": "500/pair",
  "availability": "2, F",
  "damage": "STR+1D stun",
  "range": "",
  "ammo": "",
  "game_notes": "Three power settings: Low (STR+1D stun), Medium (STR+2D stun), High (STR+3D stun). After-market mods can make lethal (up to 1,500cr/pair).",
  "source": ""
 },
 {
  "name": "Stun Gauntlets",
  "category": "Brawling Weapons",
  "skill": "Brawling",
  "cost": "300",
  "availability": "2",
  "damage": "STR+2D stun",
  "range": "",
  "ammo": "10 charges",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (pages 12-13)"
 },
 {
  "name": "Concussion Rifle",
  "category": "Concussion Weapons",
  "skill": "Concussion weapons: rifle",
  "cost": "1,000",
  "availability": "2, X",
  "damage": "5D",
  "range": "3-50/150/450",
  "ammo": "25",
  "game_notes": "",
  "source": "Gamer Magazine"
 },
 {
  "name": "LJ-50 Concussion Rifle",
  "category": "Concussion Weapons",
  "skill": "Concussion weapons: rifle",
  "cost": "1,250",
  "availability": "2, X",
  "damage": "5D+1/4D+1/3D",
  "range": "3-30/100/300",
  "ammo": "5",
  "game_notes": "Blast Radius: 0-1/2/3.",
  "source": ""
 },
 {
  "name": "Stouker Concussion Rifle",
  "category": "Concussion Weapons",
  "skill": "Concussion weapons: rifle",
  "cost": "3,500",
  "availability": "4, R",
  "damage": "6D/4D/2D",
  "range": "5-20/60/110",
  "ammo": "100",
  "game_notes": "Blast Radius: 0-2/6/10. Deadly to user at close range (roll 1D, 4-6 = safe).",
  "source": ""
 },
 {
  "name": "Dart Shooter",
  "category": "Dart Shooters",
  "skill": "Missile weapons: dart shooter",
  "cost": "350",
  "availability": "1, F",
  "damage": "2D-6D (varies by toxin)",
  "range": "2-4/8/10",
  "ammo": "30",
  "game_notes": "Fire Rate 4. Damage varies by loaded toxin \u2014 stun or normal.",
  "source": "Gundark's Fantastic Technology (page 17)"
 },
 {
  "name": "Prax Stealth Palm Shooter",
  "category": "Dart Shooters",
  "skill": "Missile weapons: dart shooter",
  "cost": "360",
  "availability": "2, F or R",
  "damage": "1D + 3-5D chemical",
  "range": "1-3/10/15",
  "ammo": "3",
  "game_notes": "Ineffective in non-oxygenated atmospheres. Wristband stores 6 extra darts. +1D+1 to hide.",
  "source": "Arms and Equipment Guide (pages 24-25)"
 },
 {
  "name": "Saberdart Launcher",
  "category": "Dart Shooters",
  "skill": "Missile weapons: dart launcher",
  "cost": "1,500",
  "availability": "4, R",
  "damage": "Kouhun venom (Moderate stamina or death)",
  "range": "3-10/30/120",
  "ammo": "4",
  "game_notes": "Kamino saberdarts (150cr each). No damage vs armor +1D physical or better. Success = -2D STR penalty.",
  "source": "d20 Core Rulebook (page 316)"
 },
 {
  "name": "Wrist-Caster",
  "category": "Dart Shooters",
  "skill": "Missile weapons: wrist launcher",
  "cost": "500",
  "availability": "3",
  "damage": "2D+2",
  "range": "1-4/10/20",
  "ammo": "2 quarrels",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 18)"
 },
 {
  "name": "Detonite",
  "category": "Demolitions",
  "skill": "Demolitions",
  "cost": "500/cube",
  "availability": "2, R",
  "damage": "1D (Speeder scale)",
  "range": "",
  "ammo": "",
  "game_notes": "Common explosive. Damage is per cube.",
  "source": "Rules of Engagement (page 68)"
 },
 {
  "name": "Detonite Tape",
  "category": "Demolitions",
  "skill": "Demolitions",
  "cost": "1,500/5m",
  "availability": "X",
  "damage": "3D",
  "range": "",
  "ammo": "",
  "game_notes": "Adhesive explosive strip. 0.5m blast radius.",
  "source": "Gundark's Fantastic Technology (page 44)"
 },
 {
  "name": "Plasticine Thermite Gel",
  "category": "Demolitions",
  "skill": "Demolitions",
  "cost": "1,000/kg",
  "availability": "2, X",
  "damage": "20D/kg/round (3 rounds)",
  "range": "",
  "ammo": "",
  "game_notes": "Can be shaped/molded. 1kg covers 20 sq meters. Demolitions roll based on target reinforcement.",
  "source": "Galaxy Guide 11 (page 84)"
 },
 {
  "name": "Thermal Well",
  "category": "Demolitions",
  "skill": "Demolitions",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "10D",
  "range": "",
  "ammo": "",
  "game_notes": "Baradium meltdown device. Blast Radius: 0-1. Wild die 1 = premature explosion.",
  "source": "Rules of Engagement (page 70)"
 },
 {
  "name": "Disruptor Pistol (Standard)",
  "category": "Disruptor Blasters",
  "skill": "Blaster: disruptor",
  "cost": "3,000",
  "availability": "4, X",
  "damage": "6D+2",
  "range": "0-3/5/7",
  "ammo": "5",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (pages 26-27)"
 },
 {
  "name": "Merr-Sonn MSD-32 Disruptor",
  "category": "Disruptor Blasters",
  "skill": "Blaster: disruptor",
  "cost": "4,000",
  "availability": "4, X",
  "damage": "5D+2",
  "range": "0-3/5/7",
  "ammo": "10",
  "game_notes": "Fire Rate 2.",
  "source": "Galladinium's Fantastic Technology (page 76)"
 },
 {
  "name": "MSD-36 Heavy Disruptor Pistol",
  "category": "Disruptor Blasters",
  "skill": "Blaster: heavy disruptor",
  "cost": "6,000",
  "availability": "4, X",
  "damage": "6D",
  "range": "0-3/5/7",
  "ammo": "10",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (pages 28-29)"
 },
 {
  "name": "Tenloss DX-2 Disruptor Pistol",
  "category": "Disruptor Blasters",
  "skill": "Blaster: disruptor",
  "cost": "2,250",
  "availability": "4, X",
  "damage": "4D+2",
  "range": "0-3/5/7",
  "ammo": "8",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 21)"
 },
 {
  "name": "Tenloss DXR-6 Disruptor Rifle",
  "category": "Disruptor Blasters",
  "skill": "Blaster: disruptor",
  "cost": "3,500",
  "availability": "4, X",
  "damage": "5D+2",
  "range": "0-3/5/7",
  "ammo": "15",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 21)"
 },
 {
  "name": "Beam Tube",
  "category": "Energy Weapons",
  "skill": "Archaic weapons: beam tube",
  "cost": "3,900",
  "availability": "3, R or X",
  "damage": "4D",
  "range": "3-10/20/50",
  "ammo": "90 (backpack)",
  "game_notes": "Fire Rate 1/2. Two-handed, -2 Move. Each shot roll 1D: 1-2 = tubes misalign (1D hours repair), 3-6 = normal fire.",
  "source": ""
 },
 {
  "name": "Blast-Rifle",
  "category": "Energy Weapons",
  "skill": "Blast-rifle",
  "cost": "1,500",
  "availability": "4, R or X",
  "damage": "5D",
  "range": "3-15/30/150",
  "ammo": "50",
  "game_notes": "+5 difficulty at long range.",
  "source": "Gundark's Fantastic Technology (page 22)"
 },
 {
  "name": "Pulse-Wave Blaster",
  "category": "Energy Weapons",
  "skill": "Pulse-wave weapons: blaster",
  "cost": "600",
  "availability": "4, X",
  "damage": "4D",
  "range": "3-8/20/100",
  "ammo": "50",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 22)"
 },
 {
  "name": "Pulse-Wave Rifle",
  "category": "Energy Weapons",
  "skill": "Pulse-wave weapons: rifle",
  "cost": "2,000",
  "availability": "4, X",
  "damage": "5D",
  "range": "3-20/75/150",
  "ammo": "50",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (pages 22-23)"
 },
 {
  "name": "Corondexx VES-700 Pulse Rifle",
  "category": "Energy Weapons",
  "skill": "Blaster: pulse rifle",
  "cost": "5,000 (200/power pack, 300/filaments)",
  "availability": "4, X",
  "damage": "6D/5D/3D",
  "range": "1-10/20/30",
  "ammo": "15 (power pack); filaments replaced every 20 shots",
  "game_notes": "Cone-of-fire weapon. Target and all within 1m radius take full 6D. All within 15° of target take 5D. All within 30° take 3D. Unlimited ammo with power generator. If filaments aren't changed on schedule: roll 2D for first overdue shot, +1 per additional shot. On 7+, overload circuits shut weapon down (250cr damage, Moderate blaster repair to fix). On 11+, overload circuits fail and weapon explodes in user's hands: 9D damage, 2m blast radius.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.84"
 },
 {
  "name": "Mandroxan Droid Disabler (EDWX-843)",
  "category": "Energy Weapons",
  "skill": "Blaster",
  "cost": "10,000 (black market)",
  "availability": "4, X",
  "damage": "6D stun; +1D for each hit after the first",
  "range": "5-10/30/50",
  "ammo": "10 (power pack)",
  "game_notes": "Anti-droid weapon. Fires phased energy particles that cling to a droid's exterior and disrupt neural pattern flow. When hit, droids suffer -1D to skill and attribute rolls for 3 rounds if stunned; otherwise rendered 'unconscious' per Stun Damage rules. No permanent damage, but a diagnostic overhaul and power-up is required to reactivate the droid.",
  "source": "WEG40075 Galaxy Guide 11: Criminal Organizations p.81"
 },
 {
  "name": "8-Gauge Shotgun",
  "category": "Firearms",
  "skill": "Firearms: shotgun",
  "cost": "500",
  "availability": "3, R",
  "damage": "5D",
  "range": "3-5/10/25",
  "ammo": "2",
  "game_notes": "-1D vs body armor.",
  "source": "Cracken's Rebel Operatives (page 46)"
 },
 {
  "name": "Bowcaster",
  "category": "Firearms",
  "skill": "Bowcaster",
  "cost": "900",
  "availability": "3, R",
  "damage": "4D",
  "range": "3-10/30/50",
  "ammo": "6 quarrels",
  "game_notes": "Easy STR to fire more than once/round. Moderate STR to reload. Not sold to non-Wookiees.",
  "source": "Rulebook (page 233)"
 },
 {
  "name": "Czerka Adjudicator",
  "category": "Firearms",
  "skill": "Firearms",
  "cost": "300",
  "availability": "2, F or R",
  "damage": "3D+1",
  "range": "1-5/10/25",
  "ammo": "4",
  "game_notes": "Fire Rate 2. Optional spring clamp: +1D quickdraw.",
  "source": "Galladinium's Fantastic Technology (page 73)"
 },
 {
  "name": "Czerka Adventurer",
  "category": "Firearms",
  "skill": "Firearms",
  "cost": "360",
  "availability": "1, F",
  "damage": "4D",
  "range": "3-30/100/300",
  "ammo": "15",
  "game_notes": "Slugthrower rifle.",
  "source": "Arms and Equipment Guide (page 23)"
 },
 {
  "name": "Dagger Combat Pistol",
  "category": "Firearms",
  "skill": "Firearms: slugthrower pistol",
  "cost": "300",
  "availability": "2, F",
  "damage": "3D",
  "range": "3-10/30/60",
  "ammo": "16",
  "game_notes": "-1D damage vs body armor.",
  "source": "Rulebook (page 229)"
 },
 {
  "name": "Dresselian Projectile Rifle",
  "category": "Firearms",
  "skill": "Firearms",
  "cost": "300",
  "availability": "1, F",
  "damage": "4D",
  "range": "3-25/50/200",
  "ammo": "12",
  "game_notes": "",
  "source": "Arms and Equipment Guide (pages 23-24)"
 },
 {
  "name": "Kashyyyk Long Gun",
  "category": "Firearms",
  "skill": "Firearms: heavy rifle",
  "cost": "2,000",
  "availability": "3, R",
  "damage": "6D+2",
  "range": "3-10/30/120",
  "ammo": "10",
  "game_notes": "Wookiee heavy slugthrower. -1D penalty if STR < 4D.",
  "source": "Wizards Website"
 },
 {
  "name": "Morellian .48 Enforcer",
  "category": "Firearms",
  "skill": "Firearms: Enforcer",
  "cost": "6,000+ (black market)",
  "availability": "4, R",
  "damage": "6D+1",
  "range": "1-25/75/150",
  "ammo": "4",
  "game_notes": "Heavy caliber. 2nd shot +1 difficulty level, 3rd +2 levels, etc.",
  "source": "Alliance Intelligence Reports (page 18)"
 },
 {
  "name": "Silenced Slugthrower",
  "category": "Firearms",
  "skill": "Firearms: pistol",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "3D+2",
  "range": "3-10/30/60",
  "ammo": "10",
  "game_notes": "+1 to opponent's search to detect (very quiet).",
  "source": "Rules of Engagement (page 63)"
 },
 {
  "name": "Verpine Shatter Gun",
  "category": "Firearms",
  "skill": "Firearms: Verpine shatter gun",
  "cost": "30,000",
  "availability": "4, F/R/X",
  "damage": "6D",
  "range": "50-400/900/1.5km",
  "ammo": "100",
  "game_notes": "Magnetic accelerator. Body 1D \u2014 if dropped/jarred, roll damage vs weapon body.",
  "source": "Galladinium's Fantastic Technology (pages 91-92)"
 },
 {
  "name": "Flame Carbine",
  "category": "Flame Projectors",
  "skill": "Flame-thrower",
  "cost": "500",
  "availability": "4, X",
  "damage": "5D (3D for 5 rounds)",
  "range": "3-4/5/7",
  "ammo": "10",
  "game_notes": "Fire Rate 1/2. First round 5D, then 3D for 5 more rounds unless extinguished.",
  "source": "Gundark's Fantastic Technology (page 23)"
 },
 {
  "name": "Flame Rifle",
  "category": "Flame Projectors",
  "skill": "Flame-thrower",
  "cost": "700",
  "availability": "4, X",
  "damage": "5D+1 (4D for 10 rounds)",
  "range": "3-5/7/10",
  "ammo": "25",
  "game_notes": "Fire Rate 1/2. First round 5D+1, then 4D for 10 more rounds unless extinguished.",
  "source": "Gundark's Fantastic Technology (pages 23-24)"
 },
 {
  "name": "Wrist-Mounted Flame Projector",
  "category": "Flame Projectors",
  "skill": "Flame-thrower",
  "cost": "800",
  "availability": "2, X",
  "damage": "3D (for 5 rounds)",
  "range": "3-4/5/7",
  "ammo": "5",
  "game_notes": "Fire Rate 1/2.",
  "source": "Arms and Equipment Guide (page 35)"
 },
 {
  "name": "Handheld Grenade Launcher",
  "category": "Grenade Launchers",
  "skill": "Missile weapons: grenade launcher",
  "cost": "2,000",
  "availability": "2, X",
  "damage": "Per grenade type",
  "range": "3-20/60/210",
  "ammo": "4",
  "game_notes": "GL-11 fires C016 grenades; GL-11sa fires C-10 grenades.",
  "source": "Arms and Equipment Guide (page 34)"
 },
 {
  "name": "Micro-Grenade Launcher",
  "category": "Grenade Launchers",
  "skill": "Missile weapons: grenade launcher",
  "cost": "2,500",
  "availability": "3, F",
  "damage": "4D/3D/2D (frag)",
  "range": "3-25/100/200",
  "ammo": "30",
  "game_notes": "Blast Radius: 0-2/4/6. Computerized FC: Moderate PER (free action) = +1D to hit. Auto +1D on repeat shots at same target.",
  "source": "Galaxy Guide 10 (page 84)"
 },
 {
  "name": "Relby-v10 Micro Grenade Launcher",
  "category": "Grenade Launchers",
  "skill": "Missile weapons: grenade launcher",
  "cost": "3,000",
  "availability": "4, X",
  "damage": "5D/4D/3D/2D",
  "range": "3-30/100/300",
  "ammo": "8",
  "game_notes": "Blast Radius: 0-2/4/6/8. Stun or normal depending on grenade.",
  "source": "Wizards Website"
 },
 {
  "name": "Viper Grenade Launcher",
  "category": "Grenade Launchers",
  "skill": "Missile weapons",
  "cost": "500",
  "availability": "R",
  "damage": "Per grenade type",
  "range": "1-250/350/500",
  "ammo": "5",
  "game_notes": "2 rounds to reload.",
  "source": "Cracken's Rebel Field Guide (page 72)"
 },
 {
  "name": "Locris Syndicates MGL-1 Micro-Grenade Launcher",
  "category": "Grenade Launchers",
  "skill": "Missile weapons: micro-grenade launcher",
  "cost": "2,500 (1,000/magazine)",
  "availability": "3, F",
  "damage": "4D/3D/2D (fragmentation; other micro-grenades available)",
  "range": "5-25/100/200",
  "ammo": "30 (magazine)",
  "game_notes": "Blast radius 0-2/4/6. Fire rate 1. Computerized fire control: Moderate Perception roll (free action, no penalties) adds +1D to hit. If firing at the same target repeatedly, +1D is automatic for 2nd and following shots.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.83"
 },
 {
  "name": "Anti-Vehicle Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "750",
  "availability": "R, X",
  "damage": "7D",
  "range": "",
  "ammo": "",
  "game_notes": "No Scale Comparison reduction vs Speeder-scale or smaller.",
  "source": "Gundark's Fantastic Technology (page 41)"
 },
 {
  "name": "C-10 Stun Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "600",
  "availability": "2, R or X",
  "damage": "6D+1/5D+1/3D+1/2D+1 stun",
  "range": "0-10/20/40",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/8.",
  "source": "Arms and Equipment Guide (page 33)"
 },
 {
  "name": "C-14A Stun Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "450",
  "availability": "2, R or X",
  "damage": "6D/5D/3D/2D stun",
  "range": "0-8/16/25",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/8. Rechargeable.",
  "source": "Gundark's Fantastic Technology (pages 42-43)"
 },
 {
  "name": "C-16 Fragmentation Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "200",
  "availability": "1, R",
  "damage": "5D/4D/3D/2D",
  "range": "3-7/20/40",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/10.",
  "source": "Rulebook (page 233)"
 },
 {
  "name": "C-22 Fragmentation Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "300",
  "availability": "1, R",
  "damage": "5D/4D/3D/2D",
  "range": "3-7/20/40",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/10. Timer (up to 20 rounds). Deactivate: Difficult demolitions or special code. Weak magnetic grapple.",
  "source": "Arms and Equipment Guide (page 33)"
 },
 {
  "name": "Cryoban Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "800",
  "availability": "2, X",
  "damage": "3D+2 freezing",
  "range": "0-5/10/20",
  "ammo": "",
  "game_notes": "4m blast radius. Heavy clothing +1D resist. Sealed suits negate all.",
  "source": "Arms and Equipment Guide (page 34)"
 },
 {
  "name": "Glop Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "275",
  "availability": "2, R or X",
  "damage": "6D/5D/3D (STR of glop)",
  "range": "3-7/30/60",
  "ammo": "",
  "game_notes": "Blast Radius: 0-1/3/5. Opposed STR to break free. No actual damage \u2014 restraint only.",
  "source": "Gundark's Fantastic Technology (page 42)"
 },
 {
  "name": "Ion Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "250",
  "availability": "2, R",
  "damage": "7D/5D/3D/2D ionization",
  "range": "3-7/20/40",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/10.",
  "source": "Ultimate Alien Anthology (page 81)"
 },
 {
  "name": "Plasma Eel",
  "category": "Grenades",
  "skill": "Thrown weapons: plasma eel",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "10D/5D",
  "range": "3-20/40/80",
  "ammo": "1",
  "game_notes": "Yuuzhan Vong. Thrown like spear, explodes on contact. Blast Radius: 0-2/8.",
  "source": "New Jedi Order Sourcebook (pages 20-21)"
 },
 {
  "name": "Smoke Grenade",
  "category": "Grenades",
  "skill": "Grenade",
  "cost": "25",
  "availability": "2, R",
  "damage": "\u2014",
  "range": "3-7/20/40",
  "ammo": "",
  "game_notes": "3m smoke radius. +2 to shooter difficulty.",
  "source": "Rules of Engagement (page 69)"
 },
 {
  "name": "Thermal Detonator",
  "category": "Grenades",
  "skill": "Demolitions / Grenade",
  "cost": "2,000",
  "availability": "2, X",
  "damage": "10D/8D/5D/2D",
  "range": "3-4/7/12",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/8/12/20. Wild die 1 = premature explosion.",
  "source": "Rulebook (pages 233-234)"
 },
 {
  "name": "BlasTech DL-44",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "750",
  "availability": "1, F/R/X",
  "damage": "5D",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "The iconic heavy blaster pistol.",
  "source": "Rulebook (page 231)"
 },
 {
  "name": "BlasTech DT-12",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "900",
  "availability": "1, R",
  "damage": "5D+1",
  "range": "2-5/20/35",
  "ammo": "25",
  "game_notes": "Large trigger preferred by non-human hands.",
  "source": "Arms and Equipment Guide (page 10)"
 },
 {
  "name": "BlasTech DT-57 \"Annihilator\"",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "850",
  "availability": "2, R",
  "damage": "6D+1",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "",
  "source": "Wizards Website"
 },
 {
  "name": "BlasTech DY-225",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "750",
  "availability": "2, R or X",
  "damage": "5D",
  "range": "3-5/20/40",
  "ammo": "30",
  "game_notes": "",
  "source": "Galaxy Guide 9 (page 9)"
 },
 {
  "name": "BlasTech T-6 \"Thunderer\"",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "750",
  "availability": "2, R or X",
  "damage": "6D+2",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 28)"
 },
 {
  "name": "Caelli-Merced Sentinel IV",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "1,200",
  "availability": "4, R",
  "damage": "5D+2",
  "range": "3-10/30/60",
  "ammo": "100",
  "game_notes": "Precision weapon. +5 difficulty if blaster <4D, +1D to hit if blaster 6D+.",
  "source": "Black Sands of Socorro (page 75)"
 },
 {
  "name": "Han Solo's DL-44",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "Not for sale",
  "availability": "Unique",
  "damage": "5D",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "Night-scope (-1 level difficulty at night, 1 round aim). Motion sensor (+1D search). Modified front sight (+2 initiative on draw round). Palm-tingler warns low power.",
  "source": "Star Wars Trilogy Sourcebook SE (page 153)"
 },
 {
  "name": "Merr-Sonn \"Power\" 5",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "825",
  "availability": "1, R",
  "damage": "5D",
  "range": "3-7/25/50",
  "ammo": "30",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 11)"
 },
 {
  "name": "Merr-Sonn Flash 4",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "750",
  "availability": "1, F/R/X",
  "damage": "4D+2",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "",
  "source": "Rebel Alliance Sourcebook (pages 99-100)"
 },
 {
  "name": "SoroSuub \"Renegade\"",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster: heavy blaster pistol",
  "cost": "750",
  "availability": "2, R or X",
  "damage": "5D+2",
  "range": "3-7/25/50",
  "ammo": "25",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 29)"
 },
 {
  "name": "SoroSuub S-5 Ascension Gun",
  "category": "Heavy Blaster Pistols",
  "skill": "Blaster / Firearms",
  "cost": "1,000",
  "availability": "3, F/R/X",
  "damage": "5D / paralysis / entangle",
  "range": "3-10/30/60",
  "ammo": "20 blast / 10 darts / 2 cables",
  "game_notes": "Three modes: blaster (5D), poison microdarts (Moderate STR or paralyzed 2D min), liquid cable (4D entangle vs DEX).",
  "source": "Secrets of Naboo (page 41)"
 },
 {
  "name": "BlasTech HSB-200",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "360",
  "availability": "2, R",
  "damage": "3D+1",
  "range": "3-4/8/12",
  "ammo": "12",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 12)"
 },
 {
  "name": "Czerka 411",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "300",
  "availability": "1, R",
  "damage": "3D+1",
  "range": "2-4/8/12",
  "ammo": "10",
  "game_notes": "",
  "source": "Rebel Alliance Sourcebook (page 100)"
 },
 {
  "name": "Merr-Sonn \"Happy Surprise\"",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "325",
  "availability": "2, R",
  "damage": "3D+1",
  "range": "3-5/10/15",
  "ammo": "8",
  "game_notes": "",
  "source": "Galaxy Guide 9 (page 9)"
 },
 {
  "name": "Merr-Sonn Q-2",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "275",
  "availability": "2, R or X",
  "damage": "3D",
  "range": "3-4/8/12",
  "ammo": "6",
  "game_notes": "",
  "source": "Rulebook (page 229)"
 },
 {
  "name": "Merr-Sonn Quickfire-4",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "300",
  "availability": "2, R or X",
  "damage": "4D",
  "range": "3-4/8/12",
  "ammo": "10",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (page 25)"
 },
 {
  "name": "Micro Blaster",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "400",
  "availability": "2, R or X",
  "damage": "2D+2",
  "range": "1-5/\u2014/\u2014",
  "ammo": "2",
  "game_notes": "VD search to find. Cannot be reloaded. No effect beyond 5m.",
  "source": "Gundark's Fantastic Technology (page 25)"
 },
 {
  "name": "Naboo Royal Pistol",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: royal pistol",
  "cost": "Not for sale",
  "availability": "4, R or X",
  "damage": "3D+1",
  "range": "3-4/8/12 (short) or 3-10/20/30 (long)",
  "ammo": "50",
  "game_notes": "Custom-made. +1D blaster when used by intended owner. Two barrel lengths (1 action to switch).",
  "source": "Secrets of Naboo (page 41)"
 },
 {
  "name": "Palm Blaster",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "200",
  "availability": "2",
  "damage": "2D",
  "range": "2-3/5/10",
  "ammo": "3",
  "game_notes": "",
  "source": "Cracken's Rebel Operatives (page 79)"
 },
 {
  "name": "Scout Pistol",
  "category": "Hold-Out Blasters",
  "skill": "Blaster: hold-out",
  "cost": "Not for sale",
  "availability": "3, X",
  "damage": "3D+2",
  "range": "3-10/20/40",
  "ammo": "15",
  "game_notes": "Biker scout sidearm.",
  "source": "Galaxy Guide 5 (page 65)"
 },
 {
  "name": "DEMP Gun",
  "category": "Ion Weapons",
  "skill": "Blaster",
  "cost": "500",
  "availability": "2, R",
  "damage": "2D/3D/4D (3 settings)",
  "range": "3-10/30/120",
  "ammo": "10",
  "game_notes": "Anti-droid electromagnetic pulse weapon.",
  "source": "Imperial Sourcebook (pages 122-123)"
 },
 {
  "name": "Ion Gun Pistol",
  "category": "Ion Weapons",
  "skill": "Blaster: ion pistol",
  "cost": "250",
  "availability": "2, R",
  "damage": "4D ionization",
  "range": "3-8/16/24",
  "ammo": "30",
  "game_notes": "Wreaks havoc on electrical systems. Lethal to droids, stun setting available (out 2D min). No effect on organics (unless cybernetic).",
  "source": "d20 Core Rulebook (page 137)"
 },
 {
  "name": "Jawa Ionization Gun",
  "category": "Ion Weapons",
  "skill": "Blaster: ionization gun",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "3D (droids only)",
  "range": "3-4/8/12",
  "ammo": "\u2014",
  "game_notes": "Affects droids only. Knockout only, no permanent damage. +1D to blaster skill.",
  "source": "Cracken's Rebel Field Guide (page 73)"
 },
 {
  "name": "E-Mag Mine",
  "category": "Mines",
  "skill": "Demolitions",
  "cost": "200",
  "availability": "2, R or X",
  "damage": "7D",
  "range": "",
  "ammo": "",
  "game_notes": "Anti-repulsorlift. Sensors 6D. Cannot detect above 25m. Can be calibrated for foot traffic.",
  "source": "Gundark's Fantastic Technology (page 44)"
 },
 {
  "name": "Laser Trip Mine",
  "category": "Mines",
  "skill": "Demolitions",
  "cost": "300",
  "availability": "2, R or X",
  "damage": "6D/5D/4D",
  "range": "",
  "ammo": "",
  "game_notes": "Blast Radius: 1/3/5. Thin laser beam triggers on disruption. Moderate difficulty.",
  "source": ""
 },
 {
  "name": "Proton Mine",
  "category": "Mines",
  "skill": "Demolitions",
  "cost": "750",
  "availability": "2, X",
  "damage": "6D/5D/4D/3D",
  "range": "",
  "ammo": "",
  "game_notes": "Blast Radius: 5/8/12/20. Self-detonating perimeter mine.",
  "source": "Imperial Sourcebook (page 129)"
 },
 {
  "name": "Singularity Mine",
  "category": "Mines",
  "skill": "\u2014",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "Instant death",
  "range": "",
  "ammo": "",
  "game_notes": "Yuuzhan Vong. Creates miniature black hole. Within 2m: VD dodge or sucked in and lost forever.",
  "source": "New Jedi Order Sourcebook (page 155)"
 },
 {
  "name": "Standard Anti-Vehicle Mine",
  "category": "Mines",
  "skill": "Demolitions",
  "cost": "750",
  "availability": "2, X",
  "damage": "5D/4D/3D/2D (Speeder scale)",
  "range": "",
  "ammo": "",
  "game_notes": "Blast Radius: 0-2/4/6/10.",
  "source": "Rulebook (page 234)"
 },
 {
  "name": "Deck-Clearing Blaster",
  "category": "Misc Blasters",
  "skill": "Blaster: deck clearer",
  "cost": "100",
  "availability": "2, X",
  "damage": "5D",
  "range": "1/5/10",
  "ammo": "10",
  "game_notes": "45\u00b0 arc hits all in front. Within 5m: no dodge. 6-10m: dodge at -1D. Fire Rate 1/2.",
  "source": "Gundark's Fantastic Technology (page 30)"
 },
 {
  "name": "Pulse Rifle",
  "category": "Misc Blasters",
  "skill": "Blaster: pulse rifle",
  "cost": "5,000",
  "availability": "4, X",
  "damage": "6D/5D/3D",
  "range": "1-10/20/30",
  "ammo": "15",
  "game_notes": "Target + 1m radius take full damage. 15\u00b0 either side take 3D. Filaments must be replaced every 20 shots or risk overload/explosion (9D, 2m).",
  "source": "Galaxy Guide 10 (pages 84/86)"
 },
 {
  "name": "Sound Pistol",
  "category": "Misc Blasters",
  "skill": "Blaster: sound pistol",
  "cost": "Not for sale",
  "availability": "\u2014",
  "damage": "6D/5D/4D or stun 5D/4D/3D",
  "range": "0-3/10/20",
  "ammo": "20",
  "game_notes": "Damage by range. Cone widens with range. Fire Rate 2.",
  "source": "Gundark's Fantastic Technology (page 24)"
 },
 {
  "name": "Wrist Lasers",
  "category": "Misc Blasters",
  "skill": "Blaster: wrist lasers",
  "cost": "2,000",
  "availability": "2, F",
  "damage": "4D (8D/5D/3D overload)",
  "range": "0-2",
  "ammo": "15",
  "game_notes": "Overload: non-reversible, 15sec charge, blast radius 1-2/4/6.",
  "source": "Galaxy Guide 10 (page 86)"
 },
 {
  "name": "E-60R Missile Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons: missile launcher",
  "cost": "2,000",
  "availability": "2, X",
  "damage": "6D (typical)",
  "range": "5-50/150/400",
  "ammo": "4",
  "game_notes": "Damage varies by missile type.",
  "source": ""
 },
 {
  "name": "Flechette Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons",
  "cost": "800",
  "availability": "2, F/R/X",
  "damage": "6D/5D/3D (anti-pers) or 5D/4D/3D (Speeder, anti-veh)",
  "range": "5-25/100/250",
  "ammo": "6",
  "game_notes": "Blast Radius: 1/3/5.",
  "source": "Gundark's Fantastic Technology (page 18)"
 },
 {
  "name": "Mini-Missile Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons",
  "cost": "1,500",
  "availability": "3, R or X",
  "damage": "5D/4D/3D/2D",
  "range": "3-40/120/400",
  "ammo": "3",
  "game_notes": "Blast Radius: 0-2/8/12/20.",
  "source": "Gundark's Fantastic Technology (pages 63-64)"
 },
 {
  "name": "MM9 Wrist Rocket System",
  "category": "Missile Launchers",
  "skill": "Missile weapons: wrist weapons",
  "cost": "2,500",
  "availability": "2, R",
  "damage": "Varies by rocket type",
  "range": "2-6/20/80",
  "ammo": "1",
  "game_notes": "Multiple rocket types: Explosive (5D/4D/3D/2D), Anti-vehicle (Speeder 5D/4D), Nerve toxin (3D + Difficult stamina or -2D STR), Stun gas (3D stun + Difficult stamina or -1D DEX), DEMP (4D ion), Lumablast (Difficult stamina or blind 1D rounds).",
  "source": "Arms and Equipment Guide (pages 27-28)"
 },
 {
  "name": "PLX-2 Portable Missile Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons: Plex",
  "cost": "4,000",
  "availability": "2, X",
  "damage": "6D",
  "range": "25-100/300/500 (dumb); GAM: 25-500/1/2km",
  "ammo": "2",
  "game_notes": "GAM mode: target lock, 4D tracking ability, 550m/round, 40km max range.",
  "source": "Imperial Sourcebook (pages 121-122)"
 },
 {
  "name": "PLX-4 Portable Missile Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons: Plex",
  "cost": "6,000",
  "availability": "R",
  "damage": "6D (Speeder scale)",
  "range": "100-500/3/10km",
  "ammo": "4",
  "game_notes": "Savant rockets: Moderate missile weapons to tag, then 4D skill to hit. Dumb/smart/savant options (200/600/1,000cr each).",
  "source": "Last Command Sourcebook (page 125)"
 },
 {
  "name": "RPS-8 Rocket Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons: rocket launcher",
  "cost": "1,500",
  "availability": "3, F or R",
  "damage": "6D",
  "range": "3-30/100/300",
  "ammo": "4 (20 external)",
  "game_notes": "Blast Radius: 0-1.",
  "source": "Rules of Engagement (page 65)"
 },
 {
  "name": "Locris Syndicates RDP-12 Rocket Launcher",
  "category": "Missile Launchers",
  "skill": "Missile weapons: rocket launcher",
  "cost": "1,500 (200/Type-12A clip, 250/Type-12B clip, 12/single 12A, 15/single 12B)",
  "availability": "3, F or R",
  "damage": "4D (Type-12A) / 5D stun (Type-12B)",
  "range": "3-30/100/300",
  "ammo": "4 (internal, individually loaded) or 20 (external clip)",
  "game_notes": "Blast radius 0-1. Type-12B capsules: in addition to stun damage from kinetic impact, target must make Difficult stamina roll or be incapacitated by FGA-583 nerve agent. Success still results in -1D to all actions for 6 rounds (cumulative for multiple hits).",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.84"
 },
 {
  "name": "Thalassian Corodex Snare Gun",
  "category": "Missile Launchers",
  "skill": "Missile weapons: Thalassian snare gun",
  "cost": "1,200 (black market)",
  "availability": "3, F or X",
  "damage": "2D stun",
  "range": "5-10/25/50",
  "ammo": "6",
  "game_notes": "Shoulder-mounted tube-launched restraint weapon. Emits a cone of chemically treated wire filaments that coil around the target. Upon contact, target must make an opposed Strength roll vs. the snare's beginning Strength of 3D to avoid entanglement. The snare's Strength increases by +1D each additional round as filaments constrict and harden. Filaments cause no physical damage. A special dissolving agent can degrade the filaments.",
  "source": "WEG40075 Galaxy Guide 11: Criminal Organizations p.81"
 },
 {
  "name": "ACP Array Gun",
  "category": "Particle Weapons",
  "skill": "Particle weapons: repeater",
  "cost": "1,150",
  "availability": "3, X",
  "damage": "5D+1",
  "range": "2-10/40/80",
  "ammo": "64",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "ACP Heavy Repeater",
  "category": "Particle Weapons",
  "skill": "Particle weapons: heavy repeater",
  "cost": "3,200",
  "availability": "3, X",
  "damage": "7D+1",
  "range": "3-50/150/400",
  "ammo": "200",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "ACP Repeater Gun",
  "category": "Particle Weapons",
  "skill": "Particle weapons: repeater",
  "cost": "950",
  "availability": "3, X",
  "damage": "4D+2",
  "range": "3-20/70/150",
  "ammo": "40",
  "game_notes": "Accelerated Charged Particle weapon.",
  "source": ""
 },
 {
  "name": "Charric",
  "category": "Particle Weapons",
  "skill": "Charric",
  "cost": "500 (Chiss)",
  "availability": "3, X",
  "damage": "4D",
  "range": "3-8/30/60",
  "ammo": "40",
  "game_notes": "Maser-guided particle discharge. Ceramic/polymer armor useless. Metal armor: treat as stun. Some have stun setting.",
  "source": "Ultimate Alien Anthology (page 38)"
 },
 {
  "name": "Imperial Heavy Repeater & Concussion Launcher",
  "category": "Particle Weapons",
  "skill": "Particle weapons / Concussion",
  "cost": "3,000",
  "availability": "3, X",
  "damage": "6D (repeater) / 5D/3D+2/2D (concussion)",
  "range": "3-40/100/260",
  "ammo": "100",
  "game_notes": "Two modes: repeating or concussion. Concussion blast radius: 0-1/2/3.",
  "source": ""
 },
 {
  "name": "Malkite Poisoner's Kit",
  "category": "Poisons",
  "skill": "Various",
  "cost": "800,000",
  "availability": "4, X",
  "damage": "Death (2 rounds)",
  "range": "Contact/0.5m (aerosol)",
  "ammo": "",
  "game_notes": "H'gartha neurotoxin: death on contact in 2 rounds. No antidote except bacta immersion (resumes on removal). Includes aerosol spray, needles, disruption field generator, pheromone zone generator, scanner jammer, heat sealer. +1D hide. +2 difficulty levels to detect.",
  "source": "Gundark's Fantastic Technology (page 109)"
 },
 {
  "name": "Millaflower Extract",
  "category": "Poisons",
  "skill": "\u2014",
  "cost": "15-30 (30 doses)",
  "availability": "3, R",
  "damage": "Variable",
  "range": "",
  "ammo": "",
  "game_notes": "Tranquilizer. Dose 1: Relaxed. Dose 2: Uninhibited. Dose 3: Drunken (-2 all). Dose 4: Unconscious. Dose 5: Paralysis (death in 1hr without care). Dose 6: Heart failure (immediate death without care). Duration: 10hrs minus STR dice.",
  "source": "Secrets of Naboo (page 54)"
 },
 {
  "name": "Sith Poison",
  "category": "Poisons",
  "skill": "\u2014",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "2D + Dark Side corruption",
  "range": "",
  "ammo": "",
  "game_notes": "Ingested or injected. VD STR or 2D damage. Feeds anger: VD willpower/Control when spending FP or calls on Dark Side (gaining DSP). 5 successful resists to purge. Created via Alchemy (Heroic Alter).",
  "source": "Dark Side Sourcebook (page 65)"
 },
 {
  "name": "Adumari Blastsword",
  "category": "Powered Melee",
  "skill": "Melee combat: vibroblade",
  "cost": "600",
  "availability": "3, R",
  "damage": "STR+2D (max 4D+1) + 4D energy",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Discharges blaster bolt on contact.",
  "source": "Hero's Guide (page 122)"
 },
 {
  "name": "Archaic Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "1,600",
  "availability": "4, X",
  "damage": "5D",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. Belt-worn power pack + cable, 3kg. +5 difficulty to parry. Miss by 10+ = self-damage.",
  "source": "Power of the Jedi Sourcebook (page 62)"
 },
 {
  "name": "Double-Bladed Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber: double-bladed",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "5D",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult (VD without specialization). +5 parry with both blades extended. Single blade = normal lightsaber. Miss by 10+ = self-damage.",
  "source": "d20 Core Rulebook (page 134)"
 },
 {
  "name": "Dual-Phase Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "6,000",
  "availability": "4, X",
  "damage": "5D",
  "range": "up to 4m reach",
  "ammo": "",
  "game_notes": "Difficult. Adjustable blade 130cm or 300cm. +5 to construction difficulty. Miss by 10+ = self-damage.",
  "source": "Power of the Jedi Sourcebook (page 55)"
 },
 {
  "name": "Electrostaff",
  "category": "Powered Melee",
  "skill": "Melee combat: electrostaff",
  "cost": "5,750",
  "availability": "3",
  "damage": "STR+3D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. +5 parry with specialization. Can parry lightsabers without damage.",
  "source": "Wizards Website"
 },
 {
  "name": "Force Pike",
  "category": "Powered Melee",
  "skill": "Melee combat: force pike",
  "cost": "500",
  "availability": "2, R",
  "damage": "STR+2D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "Imperial Sourcebook (pages 124-125)"
 },
 {
  "name": "Great Force Pike",
  "category": "Powered Melee",
  "skill": "Melee combat: force pike",
  "cost": "1,000",
  "availability": "2",
  "damage": "STR+3D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "Arms and Equipment Guide (page 30)"
 },
 {
  "name": "Great Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "5,200",
  "availability": "4, X",
  "damage": "5D",
  "range": "4m reach",
  "ammo": "",
  "game_notes": "Difficult. Blade up to 300cm. Miss by 10+ = self-damage.",
  "source": "Power of the Jedi Sourcebook (pages 54-55)"
 },
 {
  "name": "Lightfoil",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "10,000",
  "availability": "4, X",
  "damage": "3D-4D",
  "range": "",
  "ammo": "",
  "game_notes": "On wild die 1, beam flickers and fades. 2hr repair (Moderate lightsaber repair).",
  "source": "Lord of the Expanse (page 47)"
 },
 {
  "name": "Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "5D",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. Miss by 10+ = self-damage.",
  "source": "Rulebook (page 228)"
 },
 {
  "name": "Lightwhip",
  "category": "Powered Melee",
  "skill": "Lightwhip",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "STR+3D+2 (max 7D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Kaiburr crystal shard + Mandalorian iron. +1D to trip/disarm.",
  "source": "Gamer Magazine"
 },
 {
  "name": "Power Sword",
  "category": "Powered Melee",
  "skill": "Melee combat: power sword",
  "cost": "600",
  "availability": "2, R",
  "damage": "STR+3D",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult difficulty.",
  "source": "Dark Empire Sourcebook (page 42)"
 },
 {
  "name": "Shock Whip",
  "category": "Powered Melee",
  "skill": "Melee combat: whip",
  "cost": "1,200",
  "availability": "2, X",
  "damage": "STR+2D+2 (max 6D)",
  "range": "4m reach",
  "ammo": "",
  "game_notes": "Moderate difficulty. Can trip. +1D to disarm.",
  "source": "Hero's Guide (page 123)"
 },
 {
  "name": "Short Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "4D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Miss by 10+ = self-damage.",
  "source": "Gamer Magazine"
 },
 {
  "name": "Training Lightsaber",
  "category": "Powered Melee",
  "skill": "Lightsaber",
  "cost": "1,500",
  "availability": "4, X",
  "damage": "5D",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. Max result = Wounded. Can block but not deflect bolts. 2D vs inanimate objects. Miss by 10+ = self-damage.",
  "source": "Power of the Jedi Sourcebook (page 54)"
 },
 {
  "name": "Duo-Flechette Rifle",
  "category": "Projectile Shooters",
  "skill": "Armor/Missile weapons",
  "cost": "1,000",
  "availability": "3, R or X",
  "damage": "5D",
  "range": "3-10/30/60",
  "ammo": "5",
  "game_notes": "",
  "source": "Gundark's Fantastic Technology (pages 17-18)"
 },
 {
  "name": "Flechette Smart Pistol",
  "category": "Projectile Shooters",
  "skill": "Missile weapons",
  "cost": "500",
  "availability": "3, F or R",
  "damage": "3D/5D/4D/3D (by range)",
  "range": "10-20/50/100",
  "ammo": "8",
  "game_notes": "Fire Rate 2. Damage varies: point-blank 3D, short 5D, medium 4D, long 3D.",
  "source": "Galladinium's Fantastic Technology (page 72)"
 },
 {
  "name": "Magna Caster",
  "category": "Projectile Shooters",
  "skill": "Missile weapons: magna caster",
  "cost": "2,000",
  "availability": "3, F",
  "damage": "6D/5D/4D",
  "range": "5-50/75/100",
  "ammo": "10",
  "game_notes": "Fire Rate 2. Body 2D. Magnetically-enhanced.",
  "source": "Galladinium's Fantastic Technology (pages 75-76)"
 },
 {
  "name": "Bolt-Thrower",
  "category": "Projectile Weapons",
  "skill": "Bow: mechanical bow",
  "cost": "300",
  "availability": "2-3",
  "damage": "4D",
  "range": "3-25/100/200",
  "ammo": "1",
  "game_notes": "Alliance mechanical bow.",
  "source": "Rules of Engagement (page 63)"
 },
 {
  "name": "Drolan Plasteel Repeating Crossbow",
  "category": "Projectile Weapons",
  "skill": "Crossbow",
  "cost": "400",
  "availability": "3",
  "damage": "2D+2",
  "range": "3-12/35/130",
  "ammo": "10",
  "game_notes": "Full-round action to reload.",
  "source": "Arms and Equipment Guide (page 26)"
 },
 {
  "name": "EMRG-50 Rail Gun",
  "category": "Projectile Weapons",
  "skill": "Rail gun",
  "cost": "10,000",
  "availability": "3, X",
  "damage": "5D",
  "range": "100-1/2/4km",
  "ammo": "4",
  "game_notes": "Requires 5D STR to hold due to recoil.",
  "source": "Twin Star of Kira (page 63)"
 },
 {
  "name": "Sevari Flashpistol",
  "category": "Projectile Weapons",
  "skill": "Archaic guns: flashpistol",
  "cost": "50-500",
  "availability": "3",
  "damage": "4D+2",
  "range": "3-10/30/60",
  "ammo": "1",
  "game_notes": "Fire Rate 1/2. Wild die 1: misfire (1-2), barrel damaged (3-4), or explodes 4D+2 to user (5-6). Blade attachment: STR+1D melee.",
  "source": "Gundark's Fantastic Technology (page 19)"
 },
 {
  "name": "Tasari Crossbow",
  "category": "Projectile Weapons",
  "skill": "Projectile: crossbow",
  "cost": "Not for sale",
  "availability": "3",
  "damage": "3D (1D vs Space Age armor)",
  "range": "10/20/40",
  "ammo": "1",
  "game_notes": "10 rounds (1 min) to reload.",
  "source": "Adventure Journal 15 (page 191)"
 },
 {
  "name": "BlasTech Medium Repeater",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "3,500",
  "availability": "2, X",
  "damage": "7D",
  "range": "3-60/150/400",
  "ammo": "200",
  "game_notes": "",
  "source": "Heir to the Empire Sourcebook (page 105)"
 },
 {
  "name": "BlasTech T-21 Light Repeater",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "2,000",
  "availability": "2, X",
  "damage": "6D",
  "range": "3-50/120/300",
  "ammo": "25",
  "game_notes": "",
  "source": "Rulebook (page 231)"
 },
 {
  "name": "E-Web (15)",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "6,300",
  "availability": "X",
  "damage": "8D",
  "range": "3-75/200/500",
  "ammo": "Power generator",
  "game_notes": "Crew: 2 (skeleton: 1). FC 2D (0D skeleton). Body 2D, Shields 1D (weapon) / 2D (generator). Fire Rate 3. Generator explodes on severe damage (7D, 2m radius).",
  "source": "Last Command Sourcebook (pages 123-124)"
 },
 {
  "name": "E-Web Repeating Blaster",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "5,000",
  "availability": "2, X",
  "damage": "8D",
  "range": "3-75/200/500",
  "ammo": "Power generator",
  "game_notes": "Two-man weapon. Crew: 2.",
  "source": "Rulebook (pages 231-232)"
 },
 {
  "name": "Light Repeating Blaster",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "1,500",
  "availability": "2, R",
  "damage": "5D+1",
  "range": "3-30/100/300",
  "ammo": "300",
  "game_notes": "Constant-fire: 6 blasts/shot. Once hit, following shots vs adjacent (1m) targets -1 difficulty.",
  "source": "Rules of Engagement (page 64)"
 },
 {
  "name": "Merr-Sonn Mark II Heavy Repeater",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "3,500",
  "availability": "2, X",
  "damage": "7D+2",
  "range": "3-50/200/400",
  "ammo": "Power generator",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "Merr-Sonn Repeater 3Z",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "2,500",
  "availability": "2, X",
  "damage": "6D",
  "range": "3-30/100/250",
  "ammo": "100",
  "game_notes": "Light repeating blaster.",
  "source": "Heir to the Empire Sourcebook (page 105)"
 },
 {
  "name": "SoroSuub Heavy Repeater",
  "category": "Repeating Blasters",
  "skill": "Blaster: repeating blaster",
  "cost": "4,500",
  "availability": "2, X",
  "damage": "8D",
  "range": "3-50/150/400",
  "ammo": "Power generator",
  "game_notes": "",
  "source": "Heir to the Empire Sourcebook (page 105)"
 },
 {
  "name": "Sonic Blaster (Geonosian)",
  "category": "Sonic Weapons",
  "skill": "Sonic weapons: blaster",
  "cost": "Not for sale",
  "availability": "4, R",
  "damage": "3D+2",
  "range": "2-10/15/35",
  "ammo": "10",
  "game_notes": "",
  "source": ""
 },
 {
  "name": "Sonic Pistol",
  "category": "Sonic Weapons",
  "skill": "Sonic weapons: pistol",
  "cost": "1,000",
  "availability": "2, F",
  "damage": "4D",
  "range": "3-5/8/10",
  "ammo": "40",
  "game_notes": "",
  "source": "Arms and Equipment Guide (page 36)"
 },
 {
  "name": "Sonic Rifle",
  "category": "Sonic Weapons",
  "skill": "Sonic weapons: rifle",
  "cost": "2,000",
  "availability": "2, R",
  "damage": "5D",
  "range": "3-10/15/20",
  "ammo": "20",
  "game_notes": "Butt can be used as stun baton (4D stun).",
  "source": "Arms and Equipment Guide (pages 36-37)"
 },
 {
  "name": "Czerka FS-1 Farshot",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "880",
  "availability": "1, R",
  "damage": "3D+2",
  "range": "3-50/150/430",
  "ammo": "100",
  "game_notes": "Stock + scope: +1D with 1 round aiming.",
  "source": "Arms and Equipment Guide (page 18)"
 },
 {
  "name": "DDC \"Light Sport\" Hunter",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "900",
  "availability": "1, F",
  "damage": "4D+1",
  "range": "3-40/120/350",
  "ammo": "100",
  "game_notes": "Stock + scope: +1D with 1 round aiming.",
  "source": "Rulebook (page 231)"
 },
 {
  "name": "Herloss HBt-4 Hunting Blaster",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "880",
  "availability": "1, R",
  "damage": "4D+2",
  "range": "3-30/100/300",
  "ammo": "100",
  "game_notes": "FC +2.",
  "source": "Arms and Equipment Guide (pages 18-19)"
 },
 {
  "name": "Merr-Sonn LD-1 Sniper",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "3,000",
  "availability": "2, F/R/X",
  "damage": "5D",
  "range": "2-50/150/500",
  "ammo": "100",
  "game_notes": "FC 1D+2 (macroscopic sight + gyrogimbals).",
  "source": "Rules of Engagement (page 62)"
 },
 {
  "name": "SoroSuub X-45 Sniper Rifle",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "750",
  "availability": "2, R or X",
  "damage": "5D",
  "range": "1-25/100/250",
  "ammo": "25",
  "game_notes": "Targeting scope: Long range/precision shots reduced to Moderate difficulty.",
  "source": "Gundark's Fantastic Technology (page 33)"
 },
 {
  "name": "Xerrol Nightstinger",
  "category": "Sporting Blaster Rifles",
  "skill": "Blaster: blaster rifle",
  "cost": "1,500",
  "availability": "2, R",
  "damage": "4D",
  "range": "2-50/150/450",
  "ammo": "5",
  "game_notes": "FC 1D. Fires invisible blaster bolts. Custom gas canisters 1,000cr each (5 shots).",
  "source": "Arms and Equipment Guide (page 19)"
 },
 {
  "name": "DDC Defender",
  "category": "Sporting Blasters",
  "skill": "Blaster: sporting blaster",
  "cost": "350",
  "availability": "1, F",
  "damage": "3D+1",
  "range": "3-10/30/60",
  "ammo": "50",
  "game_notes": "",
  "source": "Rulebook (page 229)"
 },
 {
  "name": "KYD-21",
  "category": "Sporting Blasters",
  "skill": "Blaster: sporting blaster",
  "cost": "500",
  "availability": "1, F",
  "damage": "3D+2",
  "range": "3-10/40/60",
  "ammo": "75",
  "game_notes": "Improved silencer: +2D to difficulty to notice shot fired.",
  "source": ""
 },
 {
  "name": "Luxan Penetrator MB450",
  "category": "Sporting Blasters",
  "skill": "Blaster: sporting blaster",
  "cost": "600",
  "availability": "4, F or R",
  "damage": "5D",
  "range": "5-20/40/60",
  "ammo": "100",
  "game_notes": "+1 level to blaster difficulties due to focused beam precision.",
  "source": "Galladinium's Fantastic Technology (pages 70-71)"
 },
 {
  "name": "Merr-Sonn Quick-Six",
  "category": "Sporting Blasters",
  "skill": "Blaster: sporting blaster",
  "cost": "325",
  "availability": "1, F",
  "damage": "3D+2",
  "range": "3-10/25/50",
  "ammo": "50",
  "game_notes": "",
  "source": "Rebel Alliance Sourcebook (pages 99-100)"
 },
 {
  "name": "SoroSuub X-30 Lancer",
  "category": "Sporting Blasters",
  "skill": "Blaster: sporting blaster",
  "cost": "330",
  "availability": "1, F",
  "damage": "3D+1",
  "range": "3-10/30/120",
  "ammo": "50",
  "game_notes": "Target blaster pistol.",
  "source": "Arms and Equipment Guide (page 15)"
 },
 {
  "name": "Amphistaff",
  "category": "Standard Melee",
  "skill": "Melee combat: amphistaff",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "Varies by mode",
  "range": "1-3/10/20 (venom)",
  "ammo": "",
  "game_notes": "Quarterstaff (Easy, STR+1D+1 max 5D), Two-Headed Spear (Moderate, STR+2D max 7D, +1D parry), Whip (Moderate, STR+1D+2 max 6D, +1D disarm/entangle + venom). Venom: VD STR or -1D DEX (injected) or blindness (sprayed).",
  "source": "New Jedi Order Sourcebook (page 20)"
 },
 {
  "name": "Arg'garok",
  "category": "Standard Melee",
  "skill": "Melee combat: arg'garok",
  "cost": "1,000 (250 on Gamorr)",
  "availability": "3, R",
  "damage": "STR+2D+1 (max 5D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Gamorrean axe.",
  "source": "Ultimate Alien Anthology (page 62)"
 },
 {
  "name": "Axe",
  "category": "Standard Melee",
  "skill": "Melee combat: axe",
  "cost": "100",
  "availability": "1",
  "damage": "STR+2D (max 5D)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Tales of the Jedi Companion (pages 124-125)"
 },
 {
  "name": "Club",
  "category": "Standard Melee",
  "skill": "Melee combat: club",
  "cost": "15",
  "availability": "1",
  "damage": "STR+1D",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty.",
  "source": "Star Wars Sourcebook (page 100)"
 },
 {
  "name": "Combat Knife",
  "category": "Standard Melee",
  "skill": "Melee combat: knife",
  "cost": "30",
  "availability": "1",
  "damage": "STR+1D+1 (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Rules of Engagement (page 60)"
 },
 {
  "name": "Coufee",
  "category": "Standard Melee",
  "skill": "Melee combat",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "STR+1D+1",
  "range": "",
  "ammo": "",
  "game_notes": "Yuuzhan Vong double-edged chitin dagger. Default YV weapon. Very Easy difficulty.",
  "source": "New Jedi Order Sourcebook (page 20)"
 },
 {
  "name": "Gaffi Stick (Gaderffii)",
  "category": "Standard Melee",
  "skill": "Melee combat: gaderffii",
  "cost": "\u2014",
  "availability": "2, F",
  "damage": "STR+1D",
  "range": "",
  "ammo": "",
  "game_notes": "Homemade Tusken Raider weapon. Easy difficulty.",
  "source": "Star Wars Trilogy Sourcebook SE (pages 150-151)"
 },
 {
  "name": "Knife",
  "category": "Standard Melee",
  "skill": "Melee combat: knife",
  "cost": "25-35",
  "availability": "1",
  "damage": "STR+1D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty.",
  "source": "Rulebook (page 228)"
 },
 {
  "name": "Light Mace",
  "category": "Standard Melee",
  "skill": "Melee combat: mace",
  "cost": "50",
  "availability": "2, F or R",
  "damage": "STR+1D+1 (max 5D+1)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty. Short flanged stick or stick with heavy metal ball.",
  "source": "d20 Core Rulebook (page 134)"
 },
 {
  "name": "Longsword / Broadsword",
  "category": "Standard Melee",
  "skill": "Melee combat: longsword",
  "cost": "150",
  "availability": "2, F or R",
  "damage": "STR+2D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "d20 Core Rulebook (page 134)"
 },
 {
  "name": "Rodian Razor-Stick",
  "category": "Standard Melee",
  "skill": "Melee combat: razor-stick",
  "cost": "Not for sale",
  "availability": "3, R",
  "damage": "STR+1D+2",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Victim must make Difficult stamina or take 1D additional damage every other round for 3 min (blood loss).",
  "source": "Alliance Intelligence Reports (page 33)"
 },
 {
  "name": "Ryyk Blade",
  "category": "Standard Melee",
  "skill": "Melee combat",
  "cost": "250-500",
  "availability": "3, R",
  "damage": "STR+2D (max 7D)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty. Traditional Wookiee weapon.",
  "source": "Arms and Equipment Guide (page 29)"
 },
 {
  "name": "Sat'skar",
  "category": "Standard Melee",
  "skill": "Melee combat",
  "cost": "700",
  "availability": "3",
  "damage": "STR+3D+1 (one-hand: STR+1D)",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult (VD one-handed). Coynite sword.",
  "source": "Gundark's Fantastic Technology (page 10)"
 },
 {
  "name": "Scitrok",
  "category": "Standard Melee",
  "skill": "Melee combat: scitrok",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "STR+3D (max 6D+2)",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. If user rolls 10+ below weapon difficulty, damages self.",
  "source": "Galaxy Guide 8 (page 84)"
 },
 {
  "name": "Sith Sword",
  "category": "Standard Melee",
  "skill": "Melee combat: Sith sword",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "STR+2D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Indestructible \u2014 can parry lightsabers and blaster bolts. Wielder auto-loses a FP and gains a DSP.",
  "source": "Tales of the Jedi Companion (page 82)"
 },
 {
  "name": "Snap Baton",
  "category": "Standard Melee",
  "skill": "Melee combat: baton",
  "cost": "200",
  "availability": "2",
  "damage": "STR+1D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Modified personal defense baton.",
  "source": "Rules of Engagement (page 60)"
 },
 {
  "name": "Spear",
  "category": "Standard Melee",
  "skill": "Melee combat / Thrown weapons",
  "cost": "60",
  "availability": "1",
  "damage": "STR+1D+1 / 2D+1 (thrown)",
  "range": "3-10/20/30 (thrown)",
  "ammo": "",
  "game_notes": "Easy difficulty. Can be thrown.",
  "source": "Star Wars Sourcebook (page 100)"
 },
 {
  "name": "Staff",
  "category": "Standard Melee",
  "skill": "Melee combat: staff",
  "cost": "15",
  "availability": "1",
  "damage": "STR+1D",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty.",
  "source": "Star Wars Sourcebook (page 100)"
 },
 {
  "name": "Sword",
  "category": "Standard Melee",
  "skill": "Melee combat: sword",
  "cost": "200",
  "availability": "1",
  "damage": "STR+2D (max 4D)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Tales of the Jedi Companion (page 125)"
 },
 {
  "name": "Thogk",
  "category": "Standard Melee",
  "skill": "Melee combat: club",
  "cost": "30",
  "availability": "3",
  "damage": "STR+2D+1 (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty. Gamorrean spiked club.",
  "source": "Ultimate Adversaries (page 154)"
 },
 {
  "name": "Whip",
  "category": "Standard Melee",
  "skill": "Melee combat: whip",
  "cost": "100",
  "availability": "1",
  "damage": "STR+1",
  "range": "4m reach",
  "ammo": "",
  "game_notes": "Can't do more than one wound level per strike. Any armor negates damage. +1D to disarm.",
  "source": "Arms and Equipment Guide (page 29)"
 },
 {
  "name": "Deck-Sweeper",
  "category": "Stun Blasters",
  "skill": "Blaster: deck-sweeper",
  "cost": "500",
  "availability": "2, X",
  "damage": "6D stun",
  "range": "3/5/10",
  "ammo": "5",
  "game_notes": "45\u00b0 arc. Within 5m: no dodge. 6-10m: dodge at -1D. Fire Rate 1/2.",
  "source": "Gundark's Fantastic Technology (page 31)"
 },
 {
  "name": "Hapan Gun of Command",
  "category": "Stun Blasters",
  "skill": "Blaster: gun of command",
  "cost": "17,500",
  "availability": "4, R or X",
  "damage": "5D vs willpower",
  "range": "3-7/25/50",
  "ammo": "6",
  "game_notes": "Lowers willpower. Results: 0-3: -1D willpower 1 round. 4-8: -1D 1D rounds. 9-12: -2D 2D min. 13-15: -2D 2D hrs. 16+: -3D 3D hrs. If willpower reaches 0D, target accepts any non-suicidal command.",
  "source": "Cracken's Threat Dossier (page 54)"
 },
 {
  "name": "Stokhli Spray Stick",
  "category": "Stun Blasters",
  "skill": "Blaster: Stokhli spray stick",
  "cost": "14,000",
  "availability": "R",
  "damage": "6D stun + entangle",
  "range": "50/100/200",
  "ammo": "10 (500m spraynet each)",
  "game_notes": "Entangled targets: opposed STR vs 6D to break free.",
  "source": "Gundark's Fantastic Technology (page 73)"
 },
 {
  "name": "Bio-Tractant Repulsor",
  "category": "Stun Firearms",
  "skill": "Firearms",
  "cost": "200",
  "availability": "4",
  "damage": "Special",
  "range": "0-5",
  "ammo": "6",
  "game_notes": "Species-specific. Difficult willpower or target ceases hostile actions. If roll succeeds, unaffected.",
  "source": "Galladinium's Fantastic Technology (page 77)"
 },
 {
  "name": "GRS-1 Snare Rifle",
  "category": "Stun Firearms",
  "skill": "Firearms: GRS-1",
  "cost": "1,100",
  "availability": "2, F/R/X",
  "damage": "Special",
  "range": "3-10/30/60",
  "ammo": "12",
  "game_notes": "Fires shockstun mist + spraynet. Mist: Difficult STR or unconscious 5D min. Spraynet: -1D attack, -2D DEX, half Move. Spraynet STR 4D+2.",
  "source": "Gamer Magazine"
 },
 {
  "name": "Ionic Tingler",
  "category": "Stun Firearms",
  "skill": "Firearms",
  "cost": "300",
  "availability": "3, F or R",
  "damage": "2D + 1-5D stun",
  "range": "0-3/6/10",
  "ammo": "5",
  "game_notes": "Charged firearm. Hollow cavity for special 5-round clip. Stun damage variable by charge level.",
  "source": "Galladinium's Fantastic Technology (page 74)"
 },
 {
  "name": "Neural Inhibitor",
  "category": "Stun Firearms",
  "skill": "Firearms: rail gun",
  "cost": "5,000 (rifle) / 4,000 (pistol)",
  "availability": "4, R or X",
  "damage": "3D+1 + 6D stun",
  "range": "3-20/50/150 (rifle)",
  "ammo": "240",
  "game_notes": "Fire Rate 4. Neurotoxin: if unconscious, Difficult stamina at 5 min, Moderate at 10 min, Easy at 12 min to revive. Heavier targets revive faster.",
  "source": "Galaxy Guide 10 (pages 83-84)"
 },
 {
  "name": "Riot Suppression Gun",
  "category": "Stun Firearms",
  "skill": "Firearms",
  "cost": "800",
  "availability": "2, R",
  "damage": "6D/5D/4D stun",
  "range": "2-3/5/10",
  "ammo": "2",
  "game_notes": "Sonic stun. Moderate demolitions to load (fail = 6D explosion to loader). Both barrels at once: wild die 1 = explodes on shooter. Fire Rate 2.",
  "source": "Classic Adventures Vol. 4 (page 131)"
 },
 {
  "name": "Mennotor DAS-430 Neural Inhibitor (Rifle)",
  "category": "Stun Firearms",
  "skill": "Firearms: rail gun",
  "cost": "5,000 (750/ammo)",
  "availability": "4, R or X",
  "damage": "3D+1 impact + 6D stun (neurotoxin)",
  "range": "3-20/50/150",
  "ammo": "240",
  "game_notes": "Portable rail gun. Fire rate 4. If neurotoxin achieves unconscious result: Difficult stamina to revive after 5 min, Moderate after 10 min, Easy after 12 min. Targets over 150kg reduce difficulty by one level and revive at 4/3/1 min intervals. Targets over 300kg reduce by two levels and revive at 2/1/1 min intervals.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.82-83"
 },
 {
  "name": "Mennotor DAS-430 Neural Inhibitor (Pistol)",
  "category": "Stun Firearms",
  "skill": "Firearms: rail gun",
  "cost": "4,000 (750/ammo)",
  "availability": "4, R or X",
  "damage": "3D+1 impact + 6D stun (neurotoxin)",
  "range": "3-10/25/50",
  "ammo": "240",
  "game_notes": "Portable rail gun (pistol variant). Fire rate 4. If neurotoxin achieves unconscious result: Difficult stamina to revive after 5 min, Moderate after 10 min, Easy after 12 min. Targets over 150kg reduce difficulty by one level and revive at 4/3/1 min intervals. Targets over 300kg reduce by two levels and revive at 2/1/1 min intervals.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.82-83"
 },
 {
  "name": "Buzz-Knuck",
  "category": "Stun Melee",
  "skill": "Melee combat: buzz-knuck",
  "cost": "500",
  "availability": "2, R",
  "damage": "STR+1D, 6D stun",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult difficulty.",
  "source": "Dark Empire Sourcebook (page 42)"
 },
 {
  "name": "Electro-Jabber",
  "category": "Stun Melee",
  "skill": "Melee combat",
  "cost": "700",
  "availability": "2, R",
  "damage": "5D stun",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Geonosis and the Outer Rim Worlds (page 14)"
 },
 {
  "name": "Electropole",
  "category": "Stun Melee",
  "skill": "Melee combat",
  "cost": "Not for sale",
  "availability": "3, R",
  "damage": "STR+1D+1 (stun or killing)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Gungan weapon. Wielder chooses % stun vs real damage before each roll.",
  "source": "Secrets of Naboo (page 49)"
 },
 {
  "name": "Fear Stick",
  "category": "Stun Melee",
  "skill": "Melee combat: knife",
  "cost": "600; 50 (refills)",
  "availability": "4, F",
  "damage": "2D stun",
  "range": "",
  "ammo": "2",
  "game_notes": "Moderate difficulty. Bio-chemical injection. Difficult stamina/willpower or severe panic attack (flight). Lasts until Heroic roll or 1 hour.",
  "source": "Galladinium's Fantastic Technologies (pages 68-69)"
 },
 {
  "name": "Flashstick",
  "category": "Stun Melee",
  "skill": "Melee combat",
  "cost": "100",
  "availability": "3, F",
  "damage": "STR + blindness",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty. Drallish weapon. Flash blinds target for 1D+2 rounds.",
  "source": "Coruscant and the Core Worlds (page 81)"
 },
 {
  "name": "Gand Shockprod Staff",
  "category": "Stun Melee",
  "skill": "Melee combat: shockprod",
  "cost": "1,000 (500 on Gand)",
  "availability": "3, R",
  "damage": "3D electricity + 3D stun",
  "range": "3m reach",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Ultimate Alien Anthology (pages 63-64)"
 },
 {
  "name": "Hand-Held Contact Stunner",
  "category": "Stun Melee",
  "skill": "Melee combat: contact stunner",
  "cost": "575",
  "availability": "2, R",
  "damage": "4D+2 stun",
  "range": "",
  "ammo": "5",
  "game_notes": "Very Easy difficulty. 15cm cylinder. Easy to hide (+2D vs weapon detectors, +1D vs searches).",
  "source": "Gundark's Fantastic Technology (page 10)"
 },
 {
  "name": "Neuronic Whip",
  "category": "Stun Melee",
  "skill": "Melee combat: neuronic whip",
  "cost": "700",
  "availability": "4, X",
  "damage": "STR+1D or 5D (stun/normal)",
  "range": "",
  "ammo": "3hr power",
  "game_notes": "Moderate difficulty.",
  "source": "Gundark's Fantastic Technology (pages 10-11)"
 },
 {
  "name": "Stun Baton",
  "category": "Stun Melee",
  "skill": "Melee combat: stun baton",
  "cost": "300",
  "availability": "R",
  "damage": "STR+2D+2 (STR+1D unpowered)",
  "range": "",
  "ammo": "3hr power",
  "game_notes": "Easy difficulty.",
  "source": "Gundark's Fantastic Technology (pages 11-12)"
 },
 {
  "name": "Stun Cloak",
  "category": "Stun Melee",
  "skill": "Melee combat",
  "cost": "1,500",
  "availability": "2",
  "damage": "5D stun",
  "range": "",
  "ammo": "3 (recycles in 3 min, 8 total)",
  "game_notes": "Moderate (Easy if target attacking). Difficult melee/brawling parry to avoid contact. Rechargeable.",
  "source": "Galaxy Guide 10 (page 86)"
 },
 {
  "name": "Taser Staff",
  "category": "Stun Melee",
  "skill": "Melee combat: taser staff",
  "cost": "500",
  "availability": "2, R",
  "damage": "5D or 5D stun (STR+1D unpowered)",
  "range": "",
  "ammo": "50 charges",
  "game_notes": "Moderate difficulty. 10kg. Separates into 3 pieces. Body 2D.",
  "source": "Shadows of the Empire Sourcebook (page 113)"
 },
 {
  "name": "Z2 Stun Baton",
  "category": "Stun Melee",
  "skill": "Melee combat: stun baton",
  "cost": "400",
  "availability": "R",
  "damage": "STR+1D or 5D stun (two settings)",
  "range": "",
  "ammo": "3hr power",
  "game_notes": "Easy difficulty.",
  "source": "Gundark's Fantastic Technology (page 12)"
 },
 {
  "name": "Antipersonnel Net Gun",
  "category": "Stun Missiles",
  "skill": "Missile weapons",
  "cost": "750",
  "availability": "2, R or X",
  "damage": "5D stun + 5D electrical",
  "range": "3-10/19/25",
  "ammo": "1",
  "game_notes": "Opposed STR vs stun to break free. Often forearm-mounted. Net replacement 100cr.",
  "source": "Gundark's Fantastic Technology (page 63)"
 },
 {
  "name": "Slaver Snare Gun",
  "category": "Stun Missiles",
  "skill": "Missile weapons: snare gun",
  "cost": "1,200 (black market)",
  "availability": "3, F or X",
  "damage": "2D stun + entangle",
  "range": "5-10/25/50",
  "ammo": "6",
  "game_notes": "Snare STR starts 3D, increases +1D/round as filaments constrict. No physical damage. Special dissolving agent to remove.",
  "source": "Galaxy Guide 11 (pages 81/83)"
 },
 {
  "name": "Tangler Gun",
  "category": "Stun Missiles",
  "skill": "Missile weapons",
  "cost": "900",
  "availability": "3",
  "damage": "2D + 4D stun (durawire)",
  "range": "5-10/30/60",
  "ammo": "5",
  "game_notes": "Opposed STR vs stun damage to break free of tangler.",
  "source": "Gundark's Fantastic Technology (page 73)"
 },
 {
  "name": "Loronar ABX-110 ABC Scrambler",
  "category": "Stun Missiles",
  "skill": "Missile weapons: ABC scrambler",
  "cost": "3,000 (350/pod)",
  "availability": "2, R or X",
  "damage": "8D/5D/3D stun",
  "range": "50-200/350/500",
  "ammo": "1 (per pod)",
  "game_notes": "Antipersonnel sensory disorientation device. FC 1D+2. Blast radius 0-10/20/30. Launch tube is 1.2m long; each pod is a back-attached box (20x10x5 cm). Pod change takes 1 minute normally. Rush change requires Technical roll: Heroic = 1 round, Very Difficult = 2 rounds, Difficult = 3 rounds, Moderate = 4 rounds, Easy = 5 rounds.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.82"
 },
 {
  "name": "Golon Arms RGL-80 Electronet",
  "category": "Stun Missiles",
  "skill": "Missile weapons: grenade launcher",
  "cost": "2,000 (magazine)",
  "availability": "2, F",
  "damage": "1-10D (variable stun or normal)",
  "range": "10-250/350/500",
  "ammo": "5 (force-fed magazine with power generator)",
  "game_notes": "Antipersonnel wire-guided grenade. Fire rate 1/2 — power generator can only control one activated net at a time. Attaches to grenade magazine holder.",
  "source": "WEG40073 Galaxy Guide 10: Bounty Hunters p.82"
 },
 {
  "name": "Bow",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: bow",
  "cost": "200",
  "availability": "1, F",
  "damage": "2D+2",
  "range": "3-10/30/100",
  "ammo": "1",
  "game_notes": "",
  "source": "Adventure Journal 2 (page 203)"
 },
 {
  "name": "Discblade",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: discblade",
  "cost": "500 (2,000 black market)",
  "availability": "4, X",
  "damage": "STR+1D+1",
  "range": "3-20/50/200",
  "ammo": "",
  "game_notes": "Zeison Sha warrior weapon.",
  "source": "Hero's Guide (page 122)"
 },
 {
  "name": "Ewok Sling",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: sling",
  "cost": "Not for sale",
  "availability": "3, F",
  "damage": "2D+1",
  "range": "3-7/15/30",
  "ammo": "1 stone",
  "game_notes": "Primitive missile weapon.",
  "source": "Gamer Magazine"
 },
 {
  "name": "Kerestian Darkstick",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: darkstick",
  "cost": "3,000",
  "availability": "3, X",
  "damage": "3D+1 energy",
  "range": "5-20/40/60",
  "ammo": "",
  "game_notes": "Light-boomerang. Black light beam cuts like lightsaber. Returns to thrower (Easy DEX to catch, fail = lands 2m away, wild die 1 = self-damage).",
  "source": "Ultimate Alien Anthology (page 85)"
 },
 {
  "name": "Magna Bolas",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: magna bolas",
  "cost": "500",
  "availability": "2, F",
  "damage": "4D stun or entangle",
  "range": "3-6/12/25",
  "ammo": "1",
  "game_notes": "Choose stun (4D) or entangle (2D+2 + Difficult DEX or entangled: -1D attack, -2D DEX, half Move).",
  "source": "Coruscant and the Core Worlds (page 157)"
 },
 {
  "name": "Razorbug",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: razorbug",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "3D+1",
  "range": "1-6/20/40",
  "ammo": "",
  "game_notes": "Yuuzhan Vong. Self-guiding (+1 pip to hit). Returns if miss. On hit, burrows for another 3D+1 next round unless removed.",
  "source": "New Jedi Order Sourcebook (page 21)"
 },
 {
  "name": "Sith Lanvarok",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: Sith lanvarok",
  "cost": "4,000",
  "availability": "4, X",
  "damage": "3D+1",
  "range": "2-10/20/40",
  "ammo": "1 burst",
  "game_notes": "Disk launcher. +1D to hit within 10m (disks spread). Telekinesis extends bonus to full range. Full round to reload.",
  "source": "Dark Side Sourcebook (page 58)"
 },
 {
  "name": "Throwing Knife",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: knife",
  "cost": "35-50",
  "availability": "1",
  "damage": "STR+1D (max 6D)",
  "range": "2-3/5/10",
  "ammo": "",
  "game_notes": "May be used as normal knife in melee.",
  "source": "Rulebook (page 228)"
 },
 {
  "name": "Thud Bug",
  "category": "Thrown Weapons",
  "skill": "5D (self-guided)",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "4D",
  "range": "1-6/20/40",
  "ammo": "",
  "game_notes": "Yuuzhan Vong. Self-guided (5D skill). Continues attacking until hit or destroyed. Moderate STR or knocked prone.",
  "source": "New Jedi Order Sourcebook (page 21)"
 },
 {
  "name": "Zenji Needle",
  "category": "Thrown Weapons",
  "skill": "Thrown weapons: zenji needle",
  "cost": "Not for sale",
  "availability": "4",
  "damage": "STR+3D+1 (STR+1D without spec)",
  "range": "",
  "ammo": "",
  "game_notes": "Mistryl Shadow Guard weapon. Full damage only with specialization.",
  "source": "Gundark's Fantastic Technology (page 15)"
 },
 {
  "name": "Double Vibroblade",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: double vibroblade",
  "cost": "750",
  "availability": "3, R",
  "damage": "STR+3D (max 7D)",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. +5 parry bonus with specialization.",
  "source": "Ultimate Alien Anthology (page 59)"
 },
 {
  "name": "Double-Bladed Vibrostave",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: double-bladed vibrostave",
  "cost": "Not for sale",
  "availability": "4, X",
  "damage": "STR+3D",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate (Difficult without specialization). +5 parry bonus if trained. Royal Guardsman weapon.",
  "source": ""
 },
 {
  "name": "Duelist Vibrorapier",
  "category": "Vibro-Weapons",
  "skill": "Melee combat",
  "cost": "300",
  "availability": "2, R",
  "damage": "STR+3D (max 7D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "Gundark's Fantastic Technology (page 14)"
 },
 {
  "name": "Jengardin Double-Bladed Vibroblade",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibroblade",
  "cost": "6,000",
  "availability": "4, F/R/X",
  "damage": "STR+4D+1 (max 8D)",
  "range": "",
  "ammo": "",
  "game_notes": "Difficult. Two-handed, requires full concentration. Single-handed increases difficulty 2 levels. Miss by 10+ = self-damage.",
  "source": "Galladinium's Fantastic Technologies (page 69)"
 },
 {
  "name": "Talon Vibrodagger",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibrodagger",
  "cost": "50",
  "availability": "2, R",
  "damage": "STR+2D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Gundark's Fantastic Technology (pages 13-14)"
 },
 {
  "name": "Tehk'la Blade",
  "category": "Vibro-Weapons",
  "skill": "Melee combat",
  "cost": "250",
  "availability": "4",
  "damage": "STR+1D+2 (max 5D)",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty. Nagai vibrodagger.",
  "source": "Ultimate Alien Anthology (page 104)"
 },
 {
  "name": "Vibro-Ax",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibro-ax",
  "cost": "500",
  "availability": "2, R",
  "damage": "STR+3D+1 (max 7D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "Rulebook (page 228)"
 },
 {
  "name": "Vibro-Shiv",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibro-shiv",
  "cost": "200",
  "availability": "2, F",
  "damage": "STR+1D",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Adventure Journal 4 (page 119)"
 },
 {
  "name": "Vibrobayonet",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibrobayonet",
  "cost": "300",
  "availability": "2, F",
  "damage": "STR+1D+2",
  "range": "",
  "ammo": "",
  "game_notes": "Easy difficulty.",
  "source": "Star Wars Sourcebook (page 100)"
 },
 {
  "name": "Vibroblade",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibroblade",
  "cost": "250",
  "availability": "2, F",
  "damage": "STR+3D (max 6D)",
  "range": "",
  "ammo": "",
  "game_notes": "Moderate difficulty.",
  "source": "Rulebook (page 228)"
 },
 {
  "name": "Vibroknuckler",
  "category": "Vibro-Weapons",
  "skill": "Melee combat: vibroknuckler",
  "cost": "200",
  "availability": "2, R",
  "damage": "STR+1D+1 (STR+1 unpowered)",
  "range": "",
  "ammo": "",
  "game_notes": "Very Easy difficulty.",
  "source": "Arms and Equipment Guide (page 30)"
 }
];
