const FORCE_POWERS_DATA = [
 {
  "number": 1,
  "name": "Absorb/Dissipate Energy",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for sunburn/minor energy; Easy for intense sun; Moderate for solar wind/modest energy; Difficult for radiation storms/intense energy. For blaster bolts and Force lightning: Moderate plus attack damage roll.",
  "timeToUse": "One round",
  "keepUp": "Yes (constant sources only, not blaster bolts/lightning)",
  "effect": "Allows the Jedi to absorb or dissipate energy, including light, heat, radiation and blaster bolts. A successful control roll means the energy is dissipated. If the user fails the roll, she takes full damage. May be used to ward off sunburn, heat-stroke and radiation exposure, as well as withstand intense heat. May also absorb blaster bolts (as Darth Vader did on Cloud City). Must activate in the same round to absorb blaster bolt or Force lightning \u2014 must roll before the attack lands. Cannot be used after the attack has hit.",
  "source": "R&E (page 142-143)"
 },
 {
  "number": 2,
  "name": "Accelerate Healing",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy for wounded; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "A Jedi who uses this power successfully may make two natural healing rolls for the current day (12 hours apart) regardless of the severity of the injury. The Jedi gets a +2 modifier to both Strength rolls to heal. Accelerate healing may only be attempted once per day.",
  "source": "R&E (page 143)"
 },
 {
  "number": 3,
  "name": "Concentration",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy if relaxed and at peace; Difficult if filled with aggression, fear or other negative emotions; Very Difficult if acting on those negative emotions.",
  "timeToUse": "One round",
  "keepUp": "No",
  "effect": "The Jedi clears all negative thoughts from her mind, concentrating on one specific task. If successful, the Jedi may add +4D to any one action in that round. The Jedi may do nothing other than using concentration and that one skill for one action. No bonus if anything else is done in that round, including duplicate uses of the same skill or dodges or parries. May be used in conjunction with Force Points or Character Points. Only in effect for one round.",
  "source": "R&E (page 143)"
 },
 {
  "number": 4,
  "name": "Contort/Escape",
  "category": "Control",
  "prereqs": "3,6,9",
  "darkSide": false,
  "difficulty": "Very Easy for loose bonds; Easy for hand binder; Moderate for serious restraints; Difficult to Heroic for maximum security (varies at GM discretion).",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The character may escape bonds by contorting in painful and difficult (but still physically possible) ways. By stretching, twisting, and dislocating joints a Jedi can escape almost any physical restraining device. Jedi are trained to block out the pain and focus on the task at hand.",
  "source": "WEG40082 Tales of the Jedi Companion p.41, Jedi Academy Sourcebook (page 42)"
 },
 {
  "number": 5,
  "name": "Control Disease",
  "category": "Control",
  "prereqs": "2",
  "darkSide": false,
  "difficulty": "Very Easy for mild infection (cold); Easy for modest infection (high fever, severe flu); Moderate for severe illness (gangrene, hive virus); Difficult for life-threatening disease; Very Difficult for massive long-standing disease; Heroic for rapid-acting life-threatening disease.",
  "timeToUse": "30 minutes to several uses over weeks",
  "keepUp": "No",
  "effect": "Allows the Jedi to direct and control the anti-bodies and healing resources of her body to throw off an infection or resist diseases. Requires 30 minutes of meditation. If the disease is life-threatening or long-standing, the Jedi must make repeated skill attempts over several weeks or months to cure entirely (GM discretion on how many rolls and how often).",
  "source": "R&E (page 143)"
 },
 {
  "number": 6,
  "name": "Control Pain",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for wounded or stunned; Easy for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round",
  "keepUp": "Yes (new roll required when injured again at new injury level)",
  "effect": "A wounded Jedi who controls pain can act as if she has not been wounded, starting the round after the power roll. The wound is not healed, but the character doesn't suffer the penalties of being wounded: wounded Jedi has no die code penalties; incapacitated or mortally wounded can act normally. Can shrug off stun results. However, the character is still injured and prone to getting worse. Mortally wounded Jedi may still die from injuries even if not feeling pain.",
  "source": "R&E (page 143-144)"
 },
 {
  "number": 7,
  "name": "Detoxify Poison",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for very mild poison (alcohol); Easy for mild poison; Moderate for average poison; Difficult for virulent poison; Very Difficult to Heroic for neurotoxin.",
  "timeToUse": "Five minutes",
  "keepUp": "No",
  "effect": "Allows a Jedi to detoxify or eject poisons that have entered her body. If the Jedi makes the power roll, the poison doesn't affect her.",
  "source": "R&E (page 144)"
 },
 {
  "number": 8,
  "name": "Emptiness",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Moderate. Note: Characters consumed by the dark side may not use this power.",
  "timeToUse": "",
  "keepUp": "Yes (see description)",
  "effect": "The user empties her mind and allows the Force to flow through her. The character falls into deep meditation, unconscious and oblivious to surroundings. Difficult to sense or affect with Force \u2014 add the emptiness roll to the difficulty for another character's sense roll (or control roll if power doesn't use sense). After coming out: +6 bonus to all Force skill rolls for a period equal to time spent in emptiness, reduced by -1 per Dark Side Point. Characters dehydrate and hunger normally \u2014 some initiates have died in emptiness. Difficult control roll to bring herself out. Player must declare duration when entering. May attempt to exit: when stated time passes, once each hour beyond the limit, or when body takes damage more serious than stun.",
  "source": "R&E (page 144)"
 },
 {
  "number": 9,
  "name": "Enhance Attribute",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One round",
  "keepUp": "No (duration determined by roll, extendable with Character Points)",
  "effect": "Increases a single attribute for a limited time. All skills controlled by the enhanced attribute increase by the same amount. Only one attribute at a time \u2014 enhancing a second drops the first. Duration extendable by spending Character Points (+1 round per point, spent any time before power fades). Beat difficulty by 0-13: +1D for 3 rounds. Beat by 14-25: +2D for 2 rounds. Beat by 26+: +3D for 1 round.",
  "source": "WEG40082 Tales of the Jedi Companion pp.44-45"
 },
 {
  "number": 10,
  "name": "Force of Will",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy.",
  "timeToUse": "One round",
  "keepUp": "Yes",
  "effect": "The character uses Willpower skill to fight hostile mind-based Force powers. Add Willpower to Control or Perception to create a 'protection number.' If attack roll < Control/Perception: no effect. If attack roll > protection number: full effects. If attack roll between the two: protected, but Willpower is 'battered' (-1D to Willpower, reroll protection number). If Willpower reaches 0D, power drops automatically. Recovery: 1 day per 1D, or 1 hour in emptiness/rage per 1D. Does NOT protect against Force lightning, Force storms, or telekinetically hurled objects (external powers). DOES work against injure/kill, telekinetic kill, inflict pain, and other powers that directly use the Force on the target.",
  "source": "WEG40082 Tales of the Jedi Companion p.45, Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 11,
  "name": "Hibernation Trance",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Places the Jedi into a deep trance, slowing all body functions. Heartbeat slows, breathing barely perceivable, falls unconscious. Can heal while in trance but can do nothing else. Appears dead unless specifically tested. Another Jedi with sense or life detection can detect Force within the character. Player must declare wake conditions (time or stimuli). Another Jedi can use 'place another in hibernation trance' to bring user out. Uses about 1/10th normal air. Survives: 1 week dry climate / 1 month wet climate without water (IV drip = indefinite); up to 3 months without food (IV sugar = 1 year).",
  "source": "R&E (page 144)"
 },
 {
  "number": 12,
  "name": "Instinctive Astrogation",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Difficult. Modified by astrogation difficulty: Very Easy +0, Easy +5, Moderate +10, Difficult +15, Very Difficult +20, Heroic +30.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "The Jedi calculates hyperspace equations mentally rather than feeling them through the Force (the sense-based version). If control roll succeeds, a Very Easy astrogation roll enters the routes into the nav computer. If the roll fails, the Jedi overlooks an obstacle \u2014 astrogation difficulty increases to Very Difficult. If missed by 5+, astrogation difficulty increases to Heroic. A largely unknown and rarely studied application \u2014 little more than a curiosity among Jedi theoreticians.",
  "source": "WEG40082 Tales of the Jedi Companion p.46"
 },
 {
  "number": 13,
  "name": "Rage",
  "category": "Control",
  "prereqs": "11",
  "darkSide": true,
  "difficulty": "Difficult. Note: Can only be used by characters consumed by the Dark Side. Use gives a Dark Side Point.",
  "timeToUse": "",
  "keepUp": "No (see description)",
  "effect": "Dark side counterpart to Emptiness. Character enters a trance, appearing lifeless, face clenched in horror. Must declare duration. Difficult control roll every 4 hours to stay in trance. After exiting: +10 modifier to all Force skill rolls for a period equal to time in rage. Then takes 1D damage per 2 hours spent in rage. Adds rage control roll to difficulty of Force powers targeting the user. Dehydrates twice as fast. -1D to Strength vs physical/energy damage while in rage. Physical contact by a living being may revive (Moderate control roll) and provoke instant berserker attack \u2014 Difficult control roll to stop before killing the person. Can anticipate a foe's arrival with Difficult sense roll (life sense) when entering rage \u2014 Easy control roll to awaken instantly when expected person comes within 5 meters. Can be used as preparation for transfer life \u2014 original body consumed by dark side (blue flames), 1D damage per 3 points over difficulty (3m blast radius).",
  "source": "Dark Empire Sourcebook (page 68), WEG40082 Tales of the Jedi Companion p.46"
 },
 {
  "number": 14,
  "name": "Reduce Injury",
  "category": "Control",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "Moderate for incapacitated; Difficult for mortally wounded; Very Difficult for dead.",
  "timeToUse": "Must be used same round as injury or immediately following round",
  "keepUp": "No",
  "effect": "Reduces injury suffered to wounded. Costs a Force Point. If the original injury would have killed the character, the GM inflicts a relevant permanent injury. Note: Not always a 'selfish' act to save one's life \u2014 character might get the Force Point back if fighting to save friends from certain doom (could be considered heroic).",
  "source": "R&E (page 144)"
 },
 {
  "number": 15,
  "name": "Remain Conscious",
  "category": "Control",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "Easy for stunned; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round (must be first action of round)",
  "keepUp": "No",
  "effect": "Allows a Jedi to remain conscious after injuries that would cause unconsciousness. When suffering such injury, loses all other actions for the rest of the round but stays conscious. At the beginning of next round, must attempt to activate as first action (cannot dodge or parry). If unsuccessful, passes out immediately. If successful, may perform one other action that round (often control pain). After that action, lapses into unconsciousness unless control pain or similar power is activated.",
  "source": "R&E (page 144-145)"
 },
 {
  "number": 16,
  "name": "Remove Fatigue",
  "category": "Control",
  "prereqs": "2,6",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Combats the effects of strenuous work by manipulating the Force to eject bodily toxins more efficiently, allowing greater stamina. While kept up, must make a stamina check once per day. Must fail two stamina checks before becoming fatigued. Still must eat and drink normally. If fatigued (two failed checks): -1D penalty to all attributes and skills for 1D hours. Note: Cannot be used for Lifting \u2014 use Enhance Attribute instead.",
  "source": "WEG40082 Tales of the Jedi Companion p.47, Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 17,
  "name": "Resist Stun",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One minute",
  "keepUp": "Yes",
  "effect": "Prepares the Jedi's body to resist stun damage. Must be activated before suffering any damage. Successful roll allows the Jedi to resist all stun results except unconscious. An unconscious result forces the Jedi to drop the power (considered stunned instead). Other injuries (wounded, incapacitated, mortally wounded, killed) are treated normally.",
  "source": "R&E (page 145)"
 },
 {
  "number": 18,
  "name": "Short-Term Memory Enhancement",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The Jedi can replay recent events to examine images and peripheral occurrences more carefully. Can freeze images and scan memory tracks to recall details that were seen but didn't register consciously. Can alert the Jedi to information, items, characters, or anything that passed before their senses. If the GM provided clues that players missed, this power can recall them. How far back: beat difficulty by 0-8 = current episode; 9-20 = last episode; 21+ = last two episodes.",
  "source": "WEG40082 Tales of the Jedi Companion p.47"
 },
 {
  "number": 19,
  "name": "Beast Languages",
  "category": "Sense",
  "prereqs": "24,29,34,43",
  "darkSide": false,
  "difficulty": "Easy for domesticated/friendly animals (bantha); Moderate to Difficult for wild non-predatory (undomesticated tauntaun); Very Difficult to Heroic for ferocious/predatory (wild rancor).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Allows the Jedi to translate beast-language and speak it. The Jedi reads differences in surface emotions within grunts, growls, and body language cues. Creatures rarely have 'true' languages. For beasts that can be ridden, subtract 2D from their orneriness code while in effect (minimum 0D).",
  "source": "WEG40082 Tales of the Jedi Companion p.48, Jedi Academy Sourcebook (page 45-46)"
 },
 {
  "number": 20,
  "name": "Combat Sense",
  "category": "Sense",
  "prereqs": "21,23,42",
  "darkSide": false,
  "difficulty": "Moderate for one opponent, +3 for each additional opponent the Jedi wants to defend against.",
  "timeToUse": "",
  "keepUp": "No (lasts 10 combat rounds)",
  "effect": "The Jedi focuses entirely on combat. All targets become mentally highlighted. Advantages: 1) The Jedi decides when to act during a round \u2014 no initiative rolls needed. If multiple Jedi use this, highest roll determines order. 2) Attack and defense rolls increased by +2D. Lasts 10 combat rounds. Does not count as a 'skill use' for determining die code penalties.",
  "source": "WEG40082 Tales of the Jedi Companion p.47"
 },
 {
  "number": 21,
  "name": "Danger Sense",
  "category": "Sense",
  "prereqs": "23,42",
  "darkSide": false,
  "difficulty": "Moderate or attacker's control roll (whichever is higher).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "The Jedi extends senses like protective sensors, creating an early warning system. When active, the Jedi detects any attacks the round before they are made, giving one round to decide how to react. Any character planning to attack the Jedi on the next round must declare their action the round before. Attackers may roll their control skill to increase the difficulty of this power.",
  "source": "WEG40082 Tales of the Jedi Companion p.48"
 },
 {
  "number": 22,
  "name": "Instinctive Astrogation (Sense Variation)",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "Moderate, modified by journey difficulty: Very Easy/Easy/Moderate +0, Difficult +5, Very Difficult +10, Heroic +15.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The better-known ability to calculate hyperspace routes without a nav computer. The Jedi uses sense to feel through the myriad possible routes to determine the safest path. If successful, only an Easy astrogation roll is needed to plot the route. If the sense roll fails, astrogation difficulty becomes Very Difficult. If missed by 5+, astrogation difficulty becomes Heroic.",
  "source": "WEG40082 Tales of the Jedi Companion pp.48-49"
 },
 {
  "number": 23,
  "name": "Life Detection",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy if subject has Force skills or is Force-sensitive; Moderate if not. Modified by relationship.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Detects live sentient beings who might otherwise remain hidden. When activated, the Jedi knows the location of all sentients within 10 meters. If kept up, the Jedi knows whenever a sentient approaches within 10 meters. Each creature makes an opposed control or Perception roll to avoid detection (these rolls don't count as actions). If the Jedi beats the target's roll by 10+, she is aware if the person has Force skills, is Force-sensitive, if she has met them before, and their identity.",
  "source": "R&E (page 146)"
 },
 {
  "number": 24,
  "name": "Life Sense",
  "category": "Sense",
  "prereqs": "23",
  "darkSide": false,
  "difficulty": "Very Easy. Modified by proximity and relationship.",
  "timeToUse": "",
  "keepUp": "Yes (to track a target)",
  "effect": "The user can sense the presence and identity of a specific person for whom she searches. The user can sense how badly wounded, diseased, or otherwise physically disturbed the target is. A target may hide identity from the Jedi by rolling control skill and adding it to the difficulty.",
  "source": "R&E (page 146)"
 },
 {
  "number": 25,
  "name": "Life Web",
  "category": "Sense",
  "prereqs": "23,24,30",
  "darkSide": false,
  "difficulty": "Depends on nearest population size: Very Easy for tens of billions; Easy for billions; Moderate for hundreds of millions; Difficult for tens of millions; Very Difficult for millions; Heroic for hundreds of thousands. Cannot detect populations under 100,000. Modified by proximity.",
  "timeToUse": "Two days (each additional 2 days adds +1D to sense roll)",
  "keepUp": "No",
  "effect": "Detects large concentrations of a specific species. The Jedi senses general direction toward the population. Beat difficulty by 10+: approximate distance (hundreds/thousands of km, or tens/hundreds/thousands of light-years). Force-user must choose one specific species as specialization when selecting this power. Additional species cost 3 Character Points each. Must be familiar with the species (spent time with a member). Requires at least 2 days continuous concentration.",
  "source": "WEG40082 Tales of the Jedi Companion p.49"
 },
 {
  "number": 26,
  "name": "Magnify Senses",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy. Modified by proximity.",
  "timeToUse": "Three rounds",
  "keepUp": "No",
  "effect": "Increases the effectiveness of normal senses to perceive things that would otherwise require artificial aids. Can hear noises beyond normal hearing due to distance or softness (not beyond normal frequencies). Can see normally visible things over distances requiring macrobinoculars. Can identify scents and odors normally too faint for human olfactory senses.",
  "source": "R&E (page 146)"
 },
 {
  "number": 27,
  "name": "Postcognition",
  "category": "Sense",
  "prereqs": "11,23,30",
  "darkSide": false,
  "difficulty": "Easy for less than 2 hours; Moderate for 2 hours to 1 week; Difficult for 1 week to 6 months; Very Difficult for 6 months to 1 year; Heroic for 1-2 years; +10 per additional year.",
  "timeToUse": "Five minutes (+10 difficulty per minute cut, minimum 1 minute)",
  "keepUp": "No",
  "effect": "Investigates Force imprints left on objects by living beings. Must handle the target object. Must declare how far back to look before rolling. Roll vs 3x difficulty: witness events as if present (crystal clear). Roll vs 2x difficulty: good impression but primary sense is wavery/obscured, other senses clear. Roll vs 1x difficulty: all senses muffled, vague impressions of who handled the object and what transpired.",
  "source": "R&E (page 146-147)"
 },
 {
  "number": 28,
  "name": "Predict Natural Disaster",
  "category": "Sense",
  "prereqs": "21,23,26,35",
  "darkSide": false,
  "difficulty": "Easy if lived in area 1+ year; Moderate for 6-12 months; Difficult for 1-6 months; Very Difficult for less than 1 month. Modified by disaster severity (larger = easier) and predictability.",
  "timeToUse": "15 minutes (may reduce in 5-min increments by increasing difficulty one level per increment, minimum 1 minute)",
  "keepUp": "No",
  "effect": "Senses local meteorological and geological conditions to predict imminent disasters: earthquakes, volcanic eruptions, floods, landslides, avalanches, cave-ins, tornadoes, hurricanes, etc. Similar to how animals sense earthquakes hours or days before. Takes weeks to learn local patterns. Prediction effective for 12 hours; difficulty increases one level per additional 12-hour extension.",
  "source": "Jedi Academy Sourcebook (page 45)"
 },
 {
  "number": 29,
  "name": "Receptive Telepathy",
  "category": "Sense",
  "prereqs": "23,24",
  "darkSide": false,
  "difficulty": "Very Easy for friendly, non-resisting targets. Resisting target makes Perception or control roll as difficulty. Modified by proximity and relationship.",
  "timeToUse": "",
  "keepUp": "Yes (if target willing and proximity modifier doesn't increase)",
  "effect": "Reads surface thoughts and emotions of the target \u2014 'hears' what the target is thinking but cannot probe deeper. If sense roll doubles the difficulty, can sift through memories up to 24 hours old (takes a full round, cannot be done in the same round as contact). Can read multiple minds simultaneously but each additional target requires a new roll. Works on creatures and sentient species but not droids.",
  "source": "R&E (page 146)"
 },
 {
  "number": 30,
  "name": "Sense Force",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate for an area; Difficult for sensing details or specific objects/Force-users within the area. Modified by proximity.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Senses the ambient Force within a place. Cannot specifically detect sentient beings. Tells the character: rough magnitude of the Force (rich, moderate, or poor), rough type and quantity of life-forms, and whether the area tends toward dark or light side (e.g., the dark side tree on Dagobah). An area rich in negative or positive energies may indicate past events or activities of past inhabitants. The Jedi may also receive vague premonitions ('I sense something wrong,' 'I sense a great impending tragedy').",
  "source": "WEG40082 Tales of the Jedi Companion p.50"
 },
 {
  "number": 31,
  "name": "Sense Force Potential",
  "category": "Sense",
  "prereqs": "23,24,29,30",
  "darkSide": false,
  "difficulty": "Moderate for friendly, non-resisting targets. Moderate plus target's Perception or control roll (whichever is higher) for unwilling subjects.",
  "timeToUse": "Six rounds",
  "keepUp": "No",
  "effect": "Probes the mind of a target to determine Force potential. Force-sensitive people have an involuntary subconscious shield that pushes back against intruders. The magnitude of the backlash indicates Force strength: merely Force-sensitive = shoved back several feet; actual Force skills with little training = sent reeling across the room; well-trained or great raw talent = sent flying across the room.",
  "source": "WEG40082 Tales of the Jedi Companion p.50"
 },
 {
  "number": 32,
  "name": "Sense Path",
  "category": "Sense",
  "prereqs": "8,11",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Informs the character of the 'path' he travels: whether current actions lead toward the dark side, and whether specified future actions are likely to do so. Like farseeing without control \u2014 the Jedi cannot choose to see past, present, or future; visions are allegorical rather than specific. Can tell a Jedi with Dark Side Points how successful atonement has been. Can be used consciously or as a GM plot device \u2014 to warn, encourage, provide hints, or foreshadow events. Different Jedi receive different renditions of the same scene. The path of darkness may be clear but the light may be elusive. A skilled Dark Jedi can twist the readings to suit their own ends.",
  "source": "WEG40082 Tales of the Jedi Companion pp.50-51"
 },
 {
  "number": 33,
  "name": "Shift Sense",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "Moderate for simple phenomena (heat, simple scents); Difficult for uncommon phenomena (comm frequencies, infrared); Very Difficult for specific complex phenomena (detecting Tibanna gas by scent).",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "The character may shift senses to detect phenomena of a different type than normal \u2014 infrared vision, frequencies above or below normal range, etc. This power counts as a 'skill use' for determining die code penalties. Note: useful but limited. For example, a Jedi may detect comm frequencies but cannot listen in on the transmission. Can detect a transmission is present but may not locate the source, and certainly cannot decode the information.",
  "source": "WEG40082 Tales of the Jedi Companion pp.51-52"
 },
 {
  "number": 34,
  "name": "Translation",
  "category": "Sense",
  "prereqs": "24,29,43",
  "darkSide": false,
  "difficulty": "Moderate for humans or aliens; Difficult for droids. +5 if target is being purposely cryptic; +20 if the language is written.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Translates a language and allows the Jedi to speak it. Can decipher body language, spoken words, or ancient texts. Must first hear the target speak or see written form. One application to 'understand' a language \u2014 as long as all speakers use the same language and the power is kept up, no additional rolls needed. Droids can be communicated with since they 'speak' using beeps and whistles. Note: the character does not truly know the language \u2014 once the power drops, the Jedi cannot understand or speak it again.",
  "source": "WEG40082 Tales of the Jedi Companion p.52"
 },
 {
  "number": 35,
  "name": "Weather Sense",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy if lived in area 1+ year; Moderate for 6-12 months; Difficult for 1-6 months; Very Difficult for less than 1 month. Modified by proximity and local meteorological conditions.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Attunes the Jedi to local weather patterns by sensing movements of clouds, winds, tides, and solar bodies. Can discern patterns and make limited predictions about atmospheric phenomena. Usually takes weeks to become accustomed to local patterns and topography for accurate readings. Prediction effective for 4 hours; difficulty increases for more extended forecasts.",
  "source": "WEG40082 Tales of the Jedi Companion p.52"
 },
 {
  "number": 36,
  "name": "Bolt of Hatred",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The Force-user creates a radiant sphere of pure hatred which he can hurl at any target within line of sight. After a successful alter roll, the Force-wielder makes a thrown weapons roll with a +2D bonus to launch the bolt. Characters hit suffer 6D damage and automatically lose a Character Point. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 37,
  "name": "Dark Side Web",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Summons strands of dark side power that wrap around the target, ensnaring them in a mesh of brilliance. The lattice severs the connection between the Force and the trapped individual and saps body strength. The target loses Force skill dice up to the number of the Force-wielder's alter dice, distributed across control, sense, and alter in any combination. If desired, the user may also include Strength in the reduction. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 38,
  "name": "Injure/Kill",
  "category": "Alter",
  "prereqs": "23,24",
  "darkSide": true,
  "difficulty": "Target's control or Perception roll.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The attacker must be touching the target (successful brawling attack in the same round). If the alter roll beats the target's control or Perception, figure damage as if the alter roll was a damage total and the control/Perception roll was a Strength roll to resist damage. Dark Side Point for use.",
  "source": "R&E (page 147)"
 },
 {
  "number": 39,
  "name": "Telekinesis",
  "category": "Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for 1kg or less; Easy for 1-10kg; Moderate for 11-100kg; Difficult for 101kg-1 metric ton; Very Difficult for 1,001kg-10 metric tons; Heroic for 10,001kg-100 metric tons. +5 per additional 10m/round movement. +1 to +5 gentle turns; +6 to +10 easy maneuvers; +11 to +25+ complex maneuvers. Modified by proximity.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Levitate and move objects with the mind. Multiple objects require separate rolls. Can levitate self or others. Targets may resist with Perception or control added to difficulty. Using levitated objects to attack gives a Dark Side Point. Damage by weight: under 1kg=1D, 1-10kg=2D, 11-100kg=4D, 101kg-1ton=3D speeder-scale, 1-10 tons=3D starfighter-scale, 11-100 tons=5D starfighter-scale. Attack requires additional control roll vs target's dodge (Easy if no dodge). Can serve as emergency space drive.",
  "source": "R&E (page 147)"
 },
 {
  "number": 40,
  "name": "Farseeing",
  "category": "Control+Sense",
  "prereqs": "24",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by proximity (+5 to +20 for past, +10 to +30+ for future). Sense: Very Easy if friendly/no resistance; target's control or Perception if resisting. Modified by relationship.",
  "timeToUse": "At least one minute",
  "keepUp": "No",
  "effect": "See a person or place as it currently exists, including immediate surroundings. Can see past or future. Requires calm, no danger. Vision accuracy by roll vs sense difficulty \u2014 Past/Present: 0-10=50%, 11-20=75%, 21-30=90%, 31+=100%. Future: 0-10=10%, 11-20=25%, 21-30=50%, 31+=75%. The future is always fluid. GM should make honest effort to represent what will happen at the rolled accuracy level.",
  "source": "WEG40082 Tales of the Jedi Companion p.53"
 },
 {
  "number": 41,
  "name": "Life Bond",
  "category": "Control+Sense",
  "prereqs": "23,24,26,29",
  "darkSide": false,
  "difficulty": "Control: Moderate. Sense: varies by level (see effect). Modified by proximity.",
  "timeToUse": "1D weeks to form bond",
  "keepUp": "Yes",
  "effect": "Permanent mental link with one other individual (normally a mate). Easy sense: aware of general location and emotional state. Moderate sense: experience other's senses (see, hear, feel); share pain; if one injured, other suffers one level lower injury. Difficult sense: telepathic link, read surface thoughts (if willing). Very Difficult sense: send thoughts (projective telepathy). Premonitions automatic within 1,000km; scaling difficulty beyond. Both must agree. Only one bond at a time. Death severs the bond \u2014 survivor enters catatonic shock for 1D days, then -1D to all die codes for same duration as bond formation. Partner receives Dark Side Points for bonded partner's evil actions. If both have the power, reduce sense difficulties one level.",
  "source": "WEG40082 Tales of the Jedi Companion p.54"
 },
 {
  "number": 42,
  "name": "Lightsaber Combat",
  "category": "Control+Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Control: Moderate. Sense: Easy.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Add sense dice to lightsaber skill when attacking and parrying. Add or subtract part/all of control dice to lightsaber damage (decide when activated). If activation fails, can only use lightsaber skill for the combat. Can parry blaster bolts as a reaction skill. Can attempt to redirect deflected bolts (additional action, no full parry): control roll vs range difficulty or target's dodge, original bolt damage. Power drops if stunned, wounded, or worse; may attempt to re-activate.",
  "source": "R&E (page 148)"
 },
 {
  "number": 43,
  "name": "Projective Telepathy",
  "category": "Control+Sense",
  "prereqs": "23,24,29",
  "darkSide": false,
  "difficulty": "Control: Very Easy (+5 to +10 if cannot verbalize). Modified by proximity. Sense: Very Easy if friendly/no resistance; target's Perception or control if resisting. Modified by relationship.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The target 'hears' the Jedi's thoughts and 'feels' her emotions. Can only broadcast feelings, emotions and perhaps a couple of words \u2014 cannot send sentences or hold conversations. Target knows the thoughts are not their own. If the Jedi doesn't identify herself, the target doesn't know who is projecting. Can only communicate, not control minds.",
  "source": "R&E (page 148)"
 },
 {
  "number": 44,
  "name": "Accelerate Another's Healing",
  "category": "Control+Alter",
  "prereqs": "6,47",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by relationship. Alter: Very Easy.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "The target may make extra healing rolls as outlined in Accelerate Healing. The Jedi must be touching the character when activating this power.",
  "source": "R&E (page 148)"
 },
 {
  "number": 45,
  "name": "Aura of Uneasiness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "Control: Easy, modified by proximity. Alter: Easy.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Projects a field of vague discomfort and unease, causing all non-sentient creatures to go out of their way to avoid the user. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 46,
  "name": "Control Another's Disease",
  "category": "Control+Alter",
  "prereqs": "2,5",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by relationship. Alter: Same as Control Disease.",
  "timeToUse": "30 minutes to several uses over weeks",
  "keepUp": "No",
  "effect": "Allows a Jedi to heal another character's disease using the same rules as Control Disease. The Jedi must be touching the character to be healed.",
  "source": "R&E (page 148-149)"
 },
 {
  "number": 47,
  "name": "Control Another's Pain",
  "category": "Control+Alter",
  "prereqs": "6",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by relationship. Alter: Easy for wounded; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "",
  "keepUp": "Yes (new roll when target injured again)",
  "effect": "Allows a Jedi to help another character control pain under the same rules as Control Pain. The Jedi must be touching the character.",
  "source": "R&E (page 149)"
 },
 {
  "number": 48,
  "name": "Control Breathing",
  "category": "Control+Alter",
  "prereqs": "3,11,39",
  "darkSide": false,
  "difficulty": "Control: Moderate. Alter: Very Difficult.",
  "timeToUse": "",
  "keepUp": "Yes (drops if incapacitated or willfully dropped)",
  "effect": "Controls the amount of oxygen flowing into the Jedi's body by pulling oxygen molecules through the skin into the lungs. Effectively breathe underwater; water breathers can survive on land. Negates the need for breath masks, mechgills, or rebreathers. Useless in the cold of space or hard vacuum \u2014 not enough oxygen to 'grab' even if the Jedi could survive the pressure and temperature.",
  "source": "WEG40082 Tales of the Jedi Companion p.56"
 },
 {
  "number": 49,
  "name": "Detoxify Poison in Another",
  "category": "Control+Alter",
  "prereqs": "2,6,7,44,47",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by relationship. Alter: Very Easy for mild poison (alcohol); Easy for mild poison; Moderate for average poison; Difficult for virulent poison; Very Difficult to Heroic for neurotoxin.",
  "timeToUse": "Five minutes",
  "keepUp": "No",
  "effect": "Removes or detoxifies poison from a patient's body. Jedi must remain in physical contact with the patient. While in contact, the patient is immune to the poison's effects. Failure to make the required rolls or breaking physical contact causes the patient a wound.",
  "source": "WEG40082 Tales of the Jedi Companion p.56"
 },
 {
  "number": 50,
  "name": "Electronic Manipulation",
  "category": "Control+Alter",
  "prereqs": "1,62",
  "darkSide": true,
  "difficulty": "Control: Easy for non-sentient machines; Moderate for sentient; Difficult for hostile sentient. Modified by proximity. Alter: Easy for slight alterations; Moderate for significant changes; Difficult for major reprogramming.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Channels anger into circuits of a computer, droid, or machine to reprogram it by manipulating physical and electrical components. Only existing programming can be altered; the machine may not be given programming it doesn't have. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 51,
  "name": "Feed on Dark Side",
  "category": "Control+Alter",
  "prereqs": "30",
  "darkSide": true,
  "difficulty": "Control: Moderate when first activated, Very Easy each round after. Alter: Moderate when first activated; no additional rolls.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Feeds off a foe's anger, fear, hatred, or other negative emotions to become stronger. In any round where a light side Force-sensitive in the user's presence gains a Dark Side Point, the user gains a Dark Side Point and a Force Point. Multiple characters gaining Dark Side Points = multiple Force Points. Force Points must be spent within 5 minutes. The only way to stop this power is to resist the dark side \u2014 brute force will not work. Dark Side Point for use. Warning: avoid overuse, can severely disrupt game balance.",
  "source": "WEG40082 Tales of the Jedi Companion pp.56-57"
 },
 {
  "number": 52,
  "name": "Force Lightning",
  "category": "Control+Alter",
  "prereqs": "1,38,53",
  "darkSide": false,
  "difficulty": "Control: Difficult, modified by proximity (line of sight). Alter: Target's Perception or control roll.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Produces bolts of white or blue energy from the user's fingertips. Cannot be parried or dodged. Victim's only defense is rolling higher with Perception or control. Can be blocked by lightsaber combat (higher control total) but cannot be redirected. Can be absorbed with absorb/dissipate energy. Damage: 1D per 1D of alter the user has. Armor is useless. If the target is stunned, wounded, or worse, they cannot act for the rest of the round and the next round. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.57"
 },
 {
  "number": 53,
  "name": "Inflict Pain",
  "category": "Control+Alter",
  "prereqs": "6,24",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by proximity. Alter: Target's control or Perception, modified by proximity.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The target experiences great agony. Damage is rolled with alter vs target's control, Perception, or willpower. Damage is treated as a stun attack. If the target suffers any damage at all, they are incapable of acting for the rest of the round and the next round. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.57"
 },
 {
  "number": 54,
  "name": "Place Another in Hibernation Trance",
  "category": "Control+Alter",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Control: Very Easy, modified by relationship. Alter: Very Easy, modified by proximity.",
  "timeToUse": "Five minutes",
  "keepUp": "No",
  "effect": "Places another character into a hibernation trance. Must be in physical contact and target must agree \u2014 cannot be used as an attack. Can bring another character out of hibernation trance with +10 to alter difficulty.",
  "source": "R&E (page 149)"
 },
 {
  "number": 55,
  "name": "Remove Another's Fatigue",
  "category": "Control+Alter",
  "prereqs": "2,6,16,44,47",
  "darkSide": false,
  "difficulty": "Control: Easy. Alter: Moderate, modified by proximity and relationship.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Removes effects of fatigue in another character. Unlike the self version, the Jedi must wait until the target is actually fatigued before offering assistance. Penalties from failing stamina checks can be counteracted but must be addressed as they occur.",
  "source": "WEG40082 Tales of the Jedi Companion p.57"
 },
 {
  "number": 56,
  "name": "Return Another to Consciousness",
  "category": "Control+Alter",
  "prereqs": "6,15",
  "darkSide": false,
  "difficulty": "Control: Easy, modified by proximity and relationship. Alter: Easy for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The target returns to consciousness with the same restrictions as Remain Conscious. Must be touching the Jedi.",
  "source": "R&E (page 149)"
 },
 {
  "number": 57,
  "name": "Transfer Force",
  "category": "Control+Alter",
  "prereqs": "6,47",
  "darkSide": false,
  "difficulty": "Control: Easy, modified by relationship. Alter: Moderate.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "Saves a mortally wounded character from dying by transferring life force. Target remains mortally wounded but will not die unless injured again. Target enters hibernation for up to 6 weeks. Must be touching the target. Costs a Force Point (always considered heroic \u2014 the Jedi gets the Force Point back at end of adventure). Recipient must be willing.",
  "source": "R&E (page 149)"
 },
 {
  "number": 58,
  "name": "Waves of Darkness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "Control: Moderate for 1-2m; Difficult for 3-10m; Very Difficult for 11-20m; Heroic for 21-30m. Alter: same scale.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Channels anger into an expanding sphere of dark side energy. Anyone entering the area must make a Willpower or Control roll vs the Jedi's control roll. Failure: can't act current round or next round, must flee the following round. Success: confused, limited to one action per turn until leaving the area. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 59,
  "name": "Dim Other's Senses",
  "category": "Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Sense: Easy, modified by proximity. Alter: Target's control or Perception.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Greatly reduces the target's Perception and all Perception skills. Alter beats control/Perception by: 0-5 = -1 pip; 6-10 = -2 pips; 11-15 = -1D; 16-20 = -2D; 21+ = -3D. Can target multiple people: +3 to sense difficulty per additional target, using the highest control/Perception in the group.",
  "source": "WEG40082 Tales of the Jedi Companion p.64"
 },
 {
  "number": 60,
  "name": "Lesser Force Shield",
  "category": "Sense+Alter",
  "prereqs": "1,3,26,39",
  "darkSide": false,
  "difficulty": "Sense: Easy. Alter: Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Surrounds the Jedi's body with a Force-generated shield that repels energy and physical matter down to the molecular level. Acts as STR+1D armor against all energy and physical attacks, including non-directional attacks like gas clouds and grenade blasts. Not particularly strong but can be enough to prevent serious injury.",
  "source": "WEG40082 Tales of the Jedi Companion p.65"
 },
 {
  "number": 61,
  "name": "Force Wind",
  "category": "Sense+Alter",
  "prereqs": "26,33,39",
  "darkSide": false,
  "difficulty": "Sense: Moderate. Alter: Moderate for 5m; Difficult for 10m; Very Difficult for 15m.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Channels air currents into a powerful tornado. Damage equals the Jedi's alter dice to anyone within range.",
  "source": "WEG40082 Tales of the Jedi Companion p.88"
 },
 {
  "number": 62,
  "name": "Affect Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Control: Very Easy for perceptions; Easy for memories; Moderate for conclusions. Modified by proximity. Sense: Target's control or Perception. Alter: Very Easy for slight/momentary misperceptions, minor distant memory changes, or indifferent targets; Easy for brief visible phenomena, memories <1 year, or minor emotional investment; Moderate for short hallucinations, memories <1 day, or strict orders; Difficult for slight facial disguises, two-sense hallucinations, memories <1 minute, or very important matters; Very Difficult for all-five-senses hallucinations, major memory changes, or virtually impossible wrong conclusions.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Three modes: alter perceptions (illusions), memories (permanent alteration), or conclusions (wrong logic). Target believes illusions are real \u2014 illusory blows cause felt pain, illusory death causes unconsciousness \u2014 but no true injury occurs. Jedi must describe the exact intended effect before rolling. Normally affects one target; multiple targets require multiple uses. Cannot affect droids or recording devices.",
  "source": "R&E (page 149)"
 },
 {
  "number": 63,
  "name": "Battle Meditation",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Control/Sense/Alter: all scale with number of targets. Very Easy for 1-2; Easy for 3-20; Moderate for 21-100; Difficult for 101-1,000; Very Difficult for 1,001-10,000; Heroic for 10,001+.",
  "timeToUse": "5 minutes",
  "keepUp": "Yes",
  "effect": "Two possible effects (choose before activating). 1) Turn enemies against each other: Jedi's highest Force skill roll becomes difficulty targets must beat or they attack their own allies. Must maintain each round. 2) Buff allies/debuff enemies: enemies lose 1D per 4D in Jedi's best Force skill (to a chosen attribute, minimum 1D); allies gain the same bonus to a chosen attribute. Targets must have initiated combat. Enemies = those opposing Jedi's immediate goal; allies = those supporting it.",
  "source": "WEG40082 Tales of the Jedi Companion pp.58-59"
 },
 {
  "number": 64,
  "name": "Control Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 29,39,62",
  "darkSide": false,
  "difficulty": "Control: Easy for dark siders, Moderate for light siders. Modified by relationship. Sense: Target's Perception or control. Alter: scales by number of targets and dark/light side status. Dark side: 1=Very Easy, 2=Easy, 3=Moderate, 4-5=Difficult, 6-8=Very Difficult, 9-15=Heroic. Light side: 1=Moderate, 2=Difficult, 3=Very Difficult. Variant adds willing/unwilling distinction.",
  "timeToUse": "",
  "keepUp": "Yes (new roll when adding/switching targets)",
  "effect": "Takes control of others, turning them into puppets. Substantially easier for dark siders. Force-sensitive targets can resist with control or Perception. Cannot affect droids or computers. Controlled characters may attempt new escape rolls when Jedi adds new targets. Dark Side Point per use, plus additional Dark Side Point per evil action forced on victims.",
  "source": "WEG40082 Tales of the Jedi Companion p.87"
 },
 {
  "number": 65,
  "name": "Create Force Storms",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 11,12,13,23,24,26,29,30,39,40,43",
  "darkSide": false,
  "difficulty": "Control: Heroic. Sense: Heroic. Alter: Heroic, modified by proximity. +5 for 100m or less, +10 for 100m-1km, +15 for 1km base (+2 per km diameter). +5 per 1D of damage. Heroic each round to control. Very Difficult to dissipate.",
  "timeToUse": "",
  "keepUp": "Yes (must roll each round)",
  "effect": "The single most destructive Force power known. Creates vast storms of Force energy by twisting space-time. Capital-scale damage. Can swallow whole fleets or tear surfaces off worlds. If the Jedi fails any roll, the storm attempts to consume the summoner. If the summoner is destroyed, the storm dissipates within minutes. Can create vortices to draw victims to a point (+10 difficulty). Requires focusing hate and anger. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.60"
 },
 {
  "number": 66,
  "name": "Doppleganger",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,8,23,24,26,29,30,39,43,47,57,59,62",
  "darkSide": false,
  "difficulty": "Control: Very Difficult. Sense: Very Difficult. Alter: Heroic.",
  "timeToUse": "Five minutes",
  "keepUp": "Yes (must re-roll every 5 minutes)",
  "effect": "Creates an illusory duplicate of the user that appears real to all interactions. Registers as normal on all droid audio and video sensors. The user can sense through the doppleganger's normal senses. The duplicate acts with half the user's skill dice. If the Jedi stops using the power or the doppleganger is fatally injured, it simply fades away. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.60"
 },
 {
  "number": 67,
  "name": "Drain Life Energy",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,16,23,24,26,30,47",
  "darkSide": false,
  "difficulty": "Control: Easy. Sense: Easy, modified by proximity. Alter: Easy.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Draws power from nearby non-sentient beings. While kept up, the Jedi will not fatigue or require sleep. May not be used on sentient beings. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.88"
 },
 {
  "number": 68,
  "name": "Drain Life Essence",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,11,23,24,26,29,30,39,40,43,47,57,59,62,64",
  "darkSide": false,
  "difficulty": "Control: Very Difficult, inversely modified by relationship (close relatives +30, strangers of other species +0). Sense: scales by victims \u2014 Very Easy 1-5, Easy 6-50, Moderate 51-1,000, Difficult 1,001-50,000, Very Difficult 50,001-1M, Heroic 1M-10M. Alter: Easy for willing/worshipful, Difficult for ambivalent, Heroic for enemies (+10 if imbued with Light Side).",
  "timeToUse": "",
  "keepUp": "Yes (roll once per day)",
  "effect": "Draws life energy from surrounding beings and channels dark side effects into victims. Force Point gain scales by number drained: 1-5 = 1 FP/week, up to 1M-10M = 1 FP/12 hours. After 1 week to 1 month of sustained drain, also gains Force skill bonuses: 1-5 victims = +1D, scaling to 1M-10M = +4D+2. Jedi must roll daily; power is always 'up' with associated die penalties. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion pp.60-61"
 },
 {
  "number": 69,
  "name": "Enhance Coordination",
  "category": "Control+Sense+Alter",
  "prereqs": "24,62",
  "darkSide": false,
  "difficulty": "Control: Moderate. Sense: Difficult. Alter: scales by targets \u2014 Very Easy 1-10, Easy 11-100, Moderate 101-500, Difficult 501-5,000, Very Difficult 5,001-50,000, Heroic 51,000-500,000. Modified by proximity.",
  "timeToUse": "",
  "keepUp": "Yes (new roll when coordinating new troops or changing skills)",
  "effect": "Coordinates group activities to increase effectiveness. Used by Palpatine and C'baoth on troops. Only works on targets who agree with the Jedi's intent (no mental control granted). Links troops subconsciously for better organization. Jedi picks 3 specific Dexterity, Mechanical, or Strength skills; all troops receive +1D per 3D (rounded down) they have in those skills.",
  "source": "WEG40082 Tales of the Jedi Companion p.62"
 },
 {
  "number": 70,
  "name": "Force Harmony",
  "category": "Control+Sense+Alter",
  "prereqs": "23,24,29,43",
  "darkSide": false,
  "difficulty": "Control: Difficult, modified by proximity. Sense: Difficult, modified by relationship. Alter: Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Allows several willing Jedi to manifest the Light Side as a shield against dark side powers. Grants +5D per Force user linked to resist dark side effects. Max linked Jedi = initiator's lower of control or sense dice. If both control and sense rolls exceed the dark side power's highest success roll, the dark side power is interrupted (all 'up' powers interrupted as if stunned). Does not cancel dark side presence but distracts its servants. Note: keeping up costs -2D penalty.",
  "source": "WEG40082 Tales of the Jedi Companion pp.62-63"
 },
 {
  "number": 71,
  "name": "Memory Wipe",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,11,23,24,26,29,30,39,40,43,59,62,64",
  "darkSide": false,
  "difficulty": "Control: Moderate. Sense: Target's control or Perception, modified by relationship. Alter: Target's control or Perception, modified by relationship.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Allows the Jedi to sift through a target's mind and destroy all knowledge of a specific event or a learned skill. Requires direct physical contact. Only one specified objective per attempt. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.88"
 },
 {
  "number": 72,
  "name": "Projected Fighting",
  "category": "Control+Sense+Alter",
  "prereqs": "3,39",
  "darkSide": false,
  "difficulty": "Control: Difficult. Sense: Difficult. Alter: Moderate, modified by proximity.",
  "timeToUse": "",
  "keepUp": "Yes (as long as distance stays roughly the same)",
  "effect": "Strike at an opponent and inflict damage without physical contact. Line of sight required. After activating, make an Easy brawling roll (Force-sensitive targets may brawling parry; others cannot dodge). If successful, roll full Strength vs target's Strength. Can target specific body parts at -1D to brawling. Stun damage only to avoid Dark Side Point \u2014 any greater damage or non-protective use earns a Dark Side Point. Must re-roll if target moves significantly or switching targets.",
  "source": "WEG40082 Tales of the Jedi Companion p.63"
 },
 {
  "number": 73,
  "name": "Telekinetic Kill",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 6,24,38,53",
  "darkSide": false,
  "difficulty": "Control: Easy, modified by proximity. Sense: Easy, modified by proximity. Alter: Target's control or Perception.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Telekinetically injures or kills a target. Alter roll vs target's control or Perception determines damage. Methods vary: collapse trachea, stir the brain, squeeze the heart, etc. Dark Side Point for use.",
  "source": "WEG40082 Tales of the Jedi Companion p.63"
 },
 {
  "number": 74,
  "name": "Transfer Life",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 1,2,6,7,8,11,14,15,17,23,24,26,29,30,38,39,40,43,44,47,51,53,56,57,59,62,64",
  "darkSide": false,
  "difficulty": "Control: Heroic, modified by relationship (+15 if unwilling). Sense: Heroic, modified by proximity (+15 if unwilling). Alter: Prepared clone body = Easy; recently dead body = Moderate; live willing host = Very Difficult; live unwilling host = Heroic. Force-sensitive targets may make opposed alter or willpower roll.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "Transfers the user's life energy into another body. The key to immortality \u2014 one of the most difficult and evil dark side powers. Nearly impossible to overcome a spirit already in a body, which is why cloning host bodies is almost required. If the user's body perishes during a failed attempt, life energy is lost and dispersed. 2 Dark Side Points for use; 4 Dark Side Points if attempting to possess an unwilling host.",
  "source": "WEG40082 Tales of the Jedi Companion pp.63-64"
 },
 {
  "number": 75,
  "name": "Force Scream",
  "category": "Special",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "Involuntary \u2014 Difficult willpower roll to suppress when angered to rage.",
  "timeToUse": "Instantaneous (involuntary)",
  "keepUp": "No",
  "effect": "An involuntary dark side reflex triggered when a dark Jedi loses control of their temper. Produces a shockwave through the Force. If the willpower roll fails: all die codes reduced by -2D for 1 hour, must rest 1 hour or suffer cumulative additional -2D. Causes damage equal to the dark Jedi's alter skill to all beings within 50 meters, including the user. Force-sensitive characters resist with alter; non-Force users resist with Strength.",
  "source": "WEG40082 Tales of the Jedi Companion p.65"
 },
 {
  "number": 76,
  "name": "Lifemerge",
  "category": "Special",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Control: Difficult. Sense: Difficult.",
  "timeToUse": "Instantaneous",
  "keepUp": "No",
  "effect": "Does not need to be learned \u2014 any Jedi with 9D+ total in Force skills can attempt it at the moment of death. The Jedi calms mind and body (Difficult control), then reaches out tracing the Force (Difficult sense). On success, the spirit exits the body and becomes one with the Force; the body fades into nothingness. The Jedi can make visitations to close friends equal to their Force Points at death. Duration of each visitation = combined sense + alter + control roll in minutes. At GM discretion, only Force-sensitive characters may witness visitations. After death, the Jedi cannot influence the material world beyond visitations.",
  "source": "D6 Holocron"
 }
// --- END OF FORCE_POWERS_DATA ---
];
