// ============================================================
// DROID_COMPONENTS
// Curated catalog of modular droid parts and subsystems, drawn
// from the REUP Droids chapter (pp.387-397) + components
// referenced inside droid-template game_notes elsewhere in the
// WEG library. Complements data_equipment.js Droid Hardware /
// Droid TraitWare entries (WEG40116 Cynabar's Fantastic
// Technology: Droids).
//
// Fields:
//   name         — catalog display name
//   subcategory  — grouping inside "Droid Components"
//   cost         — credits (free-form string; may include ranges)
//   availability — WEG availability code (e.g. "2, R")
//   game_notes   — mechanical / descriptive text
//   source       — sourcebook citation
// ============================================================
const DROID_COMPONENTS = [

  // --- Armor Plating -----------------------------------------
  { name: "Chrystadurium Plating", subcategory: "Armor", cost: "50,000", availability: "3, R", game_notes: "Techno Union Chrystadurium Armor. +1D physical, +3D energy, -1D+2 to Dexterity and related skills. Integrated into chassis, not easily removed.", source: "REUP Droids p.388" },
  { name: "Duranium Battle Armor", subcategory: "Armor", cost: "10,000", availability: "4, X", game_notes: "Arakyd Industries Heavy Duranium Armor. +2D+2 physical and +1D+2 energy. Aftermarket upgrade incurs -1D+2 to Dexterity.", source: "REUP Droids p.388" },
  { name: "Duranium Plating", subcategory: "Armor", cost: "6,400", availability: "3, X", game_notes: "Baktoid Combat Automata Duranium D-65 package. +2D+1 physical and +1D energy. Aftermarket upgrade incurs -1D Dexterity.", source: "REUP Droids p.388" },
  { name: "Durasteel Battle Armor", subcategory: "Armor", cost: "9,600", availability: "3, X", game_notes: "Colicoid Creation Nest Battlesteel c-16. +2D+1 physical and +1D+1 energy. Aftermarket upgrade incurs -1D Dexterity.", source: "REUP Droids p.388" },
  { name: "Durasteel Plating", subcategory: "Armor", cost: "3,600", availability: "2, R", game_notes: "Baktoid Combat Automata Durasteel P-53 package. +2D physical and +1D+1 energy. Aftermarket upgrade incurs -1D Dexterity.", source: "REUP Droids p.388" },
  { name: "Durasteel Shell Armor", subcategory: "Armor", cost: "1,600", availability: "2, R", game_notes: "Baktoid Combat Automata Durasteel D-21 package. +1D+1 physical and +2 energy. Aftermarket upgrade incurs -2 Dexterity.", source: "REUP Droids p.388" },
  { name: "Duravlex Shell", subcategory: "Armor", cost: "1,000", availability: "2", game_notes: "Roche Durasteel-Kevlex Alloy Armor. +1D physical and energy, +3D vs fire/extreme heat, -1D Dexterity and related skills.", source: "REUP Droids p.388" },
  { name: "Laminanium Plating", subcategory: "Armor", cost: "3,000", availability: "2, R", game_notes: "Tendrandro Arms Laminanium Armor. +1D physical and energy, +2D vs corrosive acids and similar environmental hazards, -1D Dexterity.", source: "REUP Droids p.389" },
  { name: "Laminanium Heavy Plating", subcategory: "Armor", cost: "20,000", availability: "3, R", game_notes: "Tendrandro Arms Laminanium Armor. +3D physical and energy, +4D vs corrosive acids, -1D+2 Dexterity.", source: "REUP Droids p.389" },
  { name: "Mandalorian Shell Armor", subcategory: "Armor", cost: "8,100", availability: "4, X", game_notes: "Custom Mandalorian shell plating. +2D+2 physical and +1D+1 energy. Aftermarket upgrade incurs -1D+1 Dexterity.", source: "REUP Droids p.389" },
  { name: "Neutronium Plating Armor", subcategory: "Armor", cost: "12,100", availability: "4, X", game_notes: "Custom Heavy Neutronium Armor Coating. +3D physical and +2D energy. Aftermarket upgrade incurs -2D Dexterity.", source: "REUP Droids p.389" },
  { name: "Plasteel Shell Armor", subcategory: "Armor", cost: "400", availability: "2, F", game_notes: "Baktoid Combat Automata Plast 3c. +1D physical and +1 energy. Integrated into chassis.", source: "REUP Droids p.389" },
  { name: "Quadanium Battle Armor", subcategory: "Armor", cost: "4,900", availability: "3, X", game_notes: "Colicoid Creation Nest Battlesteel c-16. +2D+1 physical and +1D energy. Aftermarket upgrade incurs -1D+1 Dexterity.", source: "REUP Droids p.389" },
  { name: "Quadanium Plating Armor", subcategory: "Armor", cost: "2,500", availability: "2, R", game_notes: "Baktoid Combat Automata Quad 7a. +2D physical and +1D energy. Aftermarket upgrade incurs -1D Dexterity.", source: "REUP Droids p.389" },
  { name: "Quadanium Shell Armor", subcategory: "Armor", cost: "900", availability: "2, F", game_notes: "Baktoid Combat Automata Quad 7a. +1D physical and +2 energy. Aftermarket upgrade incurs -1 Dexterity.", source: "REUP Droids p.389" },

  // --- Sensors & Perception ----------------------------------
  { name: "Auditory Sensors (Human Range)", subcategory: "Sensors", cost: "—", availability: "1", game_notes: "Standard hearing pickup matching baseline Human auditory range.", source: "Various WEG droid templates" },
  { name: "Olfactory Sensor", subcategory: "Sensors", cost: "—", availability: "1", game_notes: "Chemical-detection intake for smell-based identification.", source: "Various WEG droid templates" },
  { name: "Motion Sensor", subcategory: "Sensors", cost: "—", availability: "1", game_notes: "Detects movement in the droid's immediate vicinity; can add to dodge, blaster, and search depending on loadout.", source: "Various WEG droid templates" },
  { name: "Night Vision Sensors", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Low-light visual pickup. Negates darkness penalties in night engagements.", source: "Various WEG droid templates" },
  { name: "Infrared Sensors", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Thermal imaging. Useful for tracking warm-blooded targets through smoke or poor visibility.", source: "Various WEG droid templates" },
  { name: "Radiation Sensors", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Detects ionizing radiation and electromagnetic pulses at range.", source: "Various WEG droid templates" },
  { name: "Electromagnetic Spectrum Sensors", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Broad-spectrum EM pickup — covers ultraviolet through long radio wavelengths.", source: "Various WEG droid templates" },
  { name: "Sonic Sensors", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Ultrasonic / subsonic pickup outside the standard auditory range.", source: "Various WEG droid templates" },
  { name: "Lifeform Sensor", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Biosignature detector. Identifies living creatures at short range.", source: "Various WEG droid templates" },
  { name: "Seismic Sensor", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Ground-vibration pickup. Detects footsteps, vehicles, or underground activity.", source: "Various WEG droid templates" },
  { name: "Long-Range Sensor Package", subcategory: "Sensors", cost: "Varies by +D bonus", availability: "2", game_notes: "Extended-range scanner suite. See Sensor Base Costs chart: +1D=150, +2D=300, +3D=450, +4D=600, +5D=750 credits. Additional target types multiply cost (×2-×6).", source: "REUP Droids p.388" },
  { name: "Extendible Video Sensor", subcategory: "Sensors", cost: "—", availability: "2", game_notes: "Retractable camera arm. Lets a stationary droid peek around corners or over obstacles.", source: "Various WEG droid templates" },
  { name: "Audio Enhancers", subcategory: "Sensors", cost: "2,000", availability: "1", game_notes: "Aural boosters. When eavesdropping or listening for distant/ambient sounds, reroll Perception checks and take the better result.", source: "REUP Droids p.389" },
  { name: "Sensor Booster", subcategory: "Sensors", cost: "200", availability: "1", game_notes: "Extends sensor range to a maximum of 2 kilometers, if the droid has a sensor pack installed.", source: "REUP Droids p.389" },
  { name: "Sensor Countermeasure Package", subcategory: "Sensors", cost: "1,000", availability: "3, F or X", game_notes: "Broadcasts signals that interfere with incoming sensor signals. Allows opposed sensors roll to avoid scanner detection.", source: "REUP Droids p.389" },
  { name: "Weapon Detector", subcategory: "Sensors", cost: "1,500", availability: "2", game_notes: "On-board weapon detection scanner. +2D to search for tell-tale high-frequency, energy and chemical signatures of weapons/explosives.", source: "REUP Droids p.389" },
  { name: "YV Sensor Package", subcategory: "Sensors", cost: "1,000", availability: "3", game_notes: "Tendrando Arms YV Sensor Package. +5D sensors vs Yuuzhan Vong's sneak or con: disguise within 20m, even through an ooglith masquer.", source: "REUP Droids p.389" },
  { name: "Multispectrum Searchlight", subcategory: "Sensors", cost: "100", availability: "2", game_notes: "Visible, infrared, or ultraviolet spotlight. Negates 1D of low-lighting penalty, 6-km range. Can blind targets in a 10-meter cone (Dex vs Perception).", source: "REUP Droids p.394" },
  { name: "Holocam (Basic)", subcategory: "Sensors", cost: "2,500", availability: "2", game_notes: "Neuro-Saav TL3 Holo-Imaging Package. Records first-person droid perspective up to 20m, downloads to datacards/dataplaques/holoprojectors. Upgrades: macrobinocular (+100m), all-environment 360°, thermal, motion sensor, UV night-vision — 200 cr each.", source: "REUP Droids p.394" },

  // --- Communications ----------------------------------------
  { name: "Vocabulator", subcategory: "Communications", cost: "—", availability: "1", game_notes: "Standard droid speech synthesizer. Required for verbal interaction with organics.", source: "Various WEG droid templates" },
  { name: "Broad-Band Antenna", subcategory: "Communications", cost: "—", availability: "1", game_notes: "Omnidirectional receiving antenna covering most civilian comm frequencies.", source: "Various WEG droid templates" },
  { name: "Broad-Band Broadcast Antenna", subcategory: "Communications", cost: "—", availability: "2", game_notes: "Transmits on a wide range of frequencies simultaneously. Useful for relay droids.", source: "Various WEG droid templates" },
  { name: "Internal Comlink (VoxLink)", subcategory: "Communications", cost: "100", availability: "2", game_notes: "Fabritech 'VoxLink' Internal Comlink. 50-km range in clear weather. Monitors up to 10 frequencies simultaneously.", source: "REUP Droids p.389" },
  { name: "High-Frequency Binary Comlink", subcategory: "Communications", cost: "—", availability: "2", game_notes: "Droid-to-droid data link using binary communication code. Private and nearly undetectable to organics.", source: "Various WEG droid templates" },
  { name: "Imperial Standard Comlink", subcategory: "Communications", cost: "—", availability: "3, R", game_notes: "Encrypted military-grade comlink keyed to Imperial channels. Illegal for private use in most sectors.", source: "WEG40131 Thrawn Trilogy Sourcebook (common Imperial droid fitment)" },
  { name: "Multinode Communications Link", subcategory: "Communications", cost: "—", availability: "2", game_notes: "Ties multiple droids into a shared communications net. Standard for coordinated units.", source: "Various WEG droid templates" },
  { name: "Starship Computer Link", subcategory: "Communications", cost: "—", availability: "2", game_notes: "Dedicated link to a specific starship's computer. Droid stays in contact while within short range of the ship.", source: "Various WEG droid templates" },
  { name: "Antitheft Comlink Locator", subcategory: "Communications", cost: "100", availability: "1", game_notes: "Sends a trackable distress signal to its master's comlink with no apparent activity. Continues to broadcast if deactivated, shuts down if destroyed.", source: "REUP Droids p.389" },
  { name: "Astromech Voice Box", subcategory: "Communications", cost: "250", availability: "2", game_notes: "Industrial Automaton R-Series Voice Box Adaptor. Allows R-series droid to speak a specific language (language programs 25-100 cr). Install: Moderate droid repair, 15 min. Remove: Easy droid repair, 15 min (failure: 3D stun + random skill loss).", source: "REUP Droids p.389" },
  { name: "Communications Countermeasure System", subcategory: "Communications", cost: "1,000", availability: "3, R", game_notes: "Anti-jamming device. Broadcasts on multiple frequencies to counteract interference. +2D communications vs jamming.", source: "REUP Droids p.389" },
  { name: "Communications Jammer", subcategory: "Communications", cost: "5,000", availability: "3, X", game_notes: "Jams all comlink signals within 1 km (Very Difficult communications roll). Also +2D computer programming/repair when slicing and holding a compromised system.", source: "REUP Droids p.390" },
  { name: "Interference Generator", subcategory: "Communications", cost: "2,500 (deluxe 6,000)", availability: "2, R", game_notes: "3-meter bubble of low-frequency sound that interferes with listening equipment (bugs, microphones). Deluxe version also defeats video/holographic recorders. Heroic search/communications to pick up words.", source: "REUP Droids p.390" },
  { name: "Space-Beacon Launcher", subcategory: "Communications", cost: "5,000 (beacons 300 ea)", availability: "2", game_notes: "Deploys 25-cm broadcast beacons in flight. Signal detectable system-wide (Easy sensors). Carries 12 beacons standard, max 24 (+10% cost per extra beacon).", source: "REUP Droids p.389" },

  // --- Cognition / Processing --------------------------------
  { name: "AA-1 Verbobrain", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Industrial Automaton's standard mid-grade droid brain. Used in a huge range of service droids.", source: "Various WEG droid templates" },
  { name: "AA-12X Verbobrain", subcategory: "Cognition", cost: "—", availability: "3", game_notes: "Upgraded Verbobrain with expanded language and analysis capacity. Common in protocol and specialist droids.", source: "Various WEG droid templates" },
  { name: "Intellex III Computer", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Mid-range primary processor used in utility and labor droids.", source: "Various WEG droid templates" },
  { name: "Intellex VI Computer", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Higher-tier Intellex processor. Stock astromech brain in many R-series droids.", source: "Various WEG droid templates" },
  { name: "Kraren XI Superprocessor", subcategory: "Cognition", cost: "—", availability: "3", game_notes: "High-end processing unit. Typically installed in tactical, espionage, or medical droids.", source: "Various WEG droid templates" },
  { name: "Analytical Computer", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Generic analysis subprocessor. Adds to investigation, search, or scholar rolls depending on loadout.", source: "Various WEG droid templates" },
  { name: "Probability Projection Computer", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Odds-calculation processor. Common in gambling, tactical, and astrogation droids.", source: "Various WEG droid templates" },
  { name: "Medical Diagnostic Computer", subcategory: "Cognition", cost: "—", availability: "2", game_notes: "Dedicated medical analysis subprocessor. Boosts first aid and (A) medicine when linked to medical sensors.", source: "Various WEG droid templates" },
  { name: "Anti-Reprogramming Package", subcategory: "Cognition", cost: "—", availability: "3", game_notes: "Hardware defenses against memory wipe and unauthorized reprogramming. Raises the difficulty to slice the droid.", source: "Various WEG droid templates" },
  { name: "Specialized Sub-Processor", subcategory: "Cognition", cost: "1,000", availability: "2", game_notes: "Secondary processor keyed to one specific skill. Grants an extra action per round for that skill; does not count toward Multiple Action Penalties. Only one per droid.", source: "REUP Droids p.396" },
  { name: "Improved Coordination Circuitry", subcategory: "Cognition", cost: "1,000", availability: "2", game_notes: "Links droids' skill routines for collaborative tasks. When a droid with this aids another with it, both gain +1D+1 to the keyed skill.", source: "REUP Droids p.394" },
  { name: "Tactician Battle Computer", subcategory: "Cognition", cost: "5,000 (transceiver set 20)", availability: "2, R", game_notes: "Software + transmitter package. Requires transceivers on allied ranged weapons. Action to analyze — grants +1D to next ranged attack roll for allies (up to the droid's tactics dice). Shuts down if picked up by droid without paired weapons.", source: "REUP Droids p.396" },

  // --- Personality Matrix (REUP-canonical 5 tiers) -----------
  { name: "Personality Matrix — None", subcategory: "Personality", cost: "—", availability: "1", game_notes: "No developed personality. Cold and mechanical but can still communicate. Many fifth-degree droids lack a matrix.", source: "REUP Droids p.397" },
  { name: "Personality Matrix — Simple", subcategory: "Personality", cost: "150", availability: "1", game_notes: "Single-word personality (friendly, ornery, cruel, timid). Common for power droids and some MSE-6 mouse droids. Program from scratch: Moderate (A) droid engineering or Difficult droid programming.", source: "REUP Droids p.397" },
  { name: "Personality Matrix — Elementary", subcategory: "Personality", cost: "300", availability: "2", game_notes: "Occasional organic contact. Standard astromech personality. Program from scratch: Moderate (A) droid engineering or Difficult droid programming.", source: "REUP Droids p.397" },
  { name: "Personality Matrix — Advanced", subcategory: "Personality", cost: "600", availability: "2", game_notes: "Regular organic interaction with limited intelligent conversation. Standard medical-droid tier. Program from scratch: Very Difficult (A) droid engineering or Heroic droid programming.", source: "REUP Droids p.397" },
  { name: "Personality Matrix — Complex", subcategory: "Personality", cost: "900", availability: "2", game_notes: "Apparently sentient behavior. Standard protocol-droid tier. Program from scratch: Very Difficult (A) droid engineering or Heroic droid programming.", source: "REUP Droids p.397" },

  // --- Language / Translation --------------------------------
  { name: "TranLang I-A Module", subcategory: "Language", cost: "—", availability: "2", game_notes: "Entry-level translation module. Covers roughly 1,000 common languages.", source: "Various WEG droid templates" },
  { name: "TranLang III Protocol Module", subcategory: "Language", cost: "—", availability: "2", game_notes: "Full protocol-droid translation suite. 6+ million forms of communication.", source: "WEG40131 Thrawn Trilogy Sourcebook" },
  { name: "Earphone Binary-to-Basic Translator", subcategory: "Language", cost: "20 (headphone) / 100 (earbud)", availability: "2", game_notes: "Installs on droid's Basic-output jack. Converts audible Binary into audible Basic to an earphone. Earbud version requires Difficult search to detect.", source: "REUP Droids p.394" },

  // --- Locomotion --------------------------------------------
  { name: "Hover Package", subcategory: "Locomotion", cost: "—", availability: "2", game_notes: "Hover-repulsor chassis supplement. Keeps the droid at low altitude (under 1m) over most terrain.", source: "Various WEG droid templates" },
  { name: "Thruster Package", subcategory: "Locomotion", cost: "—", availability: "3", game_notes: "Reaction-thruster set for short-range flight or zero-G maneuvering.", source: "Various WEG droid templates" },
  { name: "Climbing Claws", subcategory: "Locomotion", cost: "200", availability: "2", game_notes: "Aro droid friction-coated hands. +1D to all climbing rolls.", source: "REUP Droids p.390" },
  { name: "Digging Claws", subcategory: "Locomotion", cost: "500", availability: "2", game_notes: "Grants a burrow speed equal to half Move (rounded down) through solid stone; half that through transparisteel.", source: "REUP Droids p.390" },
  { name: "Gyroscopic Stabilizers", subcategory: "Locomotion", cost: "Move × 100", availability: "2", game_notes: "Series of gyros and hydraulics. +2D Dexterity to resist being knocked or falling prone.", source: "REUP Droids p.391" },
  { name: "Jump Servos", subcategory: "Locomotion", cost: "550", availability: "2", game_notes: "Arakyd Industries servo upgrade. +1D+2 to all jumping rolls.", source: "REUP Droids p.391" },
  { name: "Locked Access", subcategory: "Locomotion", cost: "50", availability: "1", game_notes: "Kalibac Industries Secure Shut Down. Shut-down switch moved inside the chassis. Droid must be disabled or subdued before it can be turned off.", source: "REUP Droids p.391" },
  { name: "Magnetic Feet", subcategory: "Locomotion", cost: "185", availability: "1", game_notes: "Cybot Galactica a-550 Magnas. Normal movement across unstable or slanted metallic surfaces (e.g. ship hulls). Only available for wheels/legs/treads locomotion.", source: "REUP Droids p.391" },
  { name: "Magnetic Hands", subcategory: "Locomotion", cost: "100", availability: "2", game_notes: "Pairs with magnetic feet. +1D climbing/jumping on starship hulls; +5 to difficulty of knocking the droid off a hull.", source: "REUP Droids p.391" },
  { name: "Underwater Drive", subcategory: "Locomotion", cost: "Desired Move × 215", availability: "3", game_notes: "Aquatic propulsion. Cost = underwater Move × 215 credits. Available in Moves 1-15.", source: "REUP Droids p.391" },

  // --- Navigation --------------------------------------------
  { name: "Astrogation Buffer (Lifeline)", subcategory: "Navigation", cost: "1,300", availability: "2, F", game_notes: "Cybot Galactica 'Lifeline' Astrogation Buffer. Stores one set of nav coordinates indefinitely (newest overwrites older). Transfer via scomp-link + Moderate computer programming/repair.", source: "REUP Droids p.391" },
  { name: "Automap", subcategory: "Navigation", cost: "1,000", availability: "1", game_notes: "Active terrain scan within 20m. +2D search. Reveals terrain, atmospherics, EM signatures, and lifeforms (not through walls). Includes direction/speed/global coordinates if linked to satellite or starship.", source: "REUP Droids p.391" },
  { name: "Internal Reference System (AutoTracker)", subcategory: "Navigation", cost: "4,000", availability: "2", game_notes: "SoroSuub 'AutoTracker' Droid GPS Module. Links to orbiting data source for accurate location, weather, and navigational hazards. Moderate computer programming/repair per hour to maintain link.", source: "REUP Droids p.391" },

  // --- Manipulation / Tools ----------------------------------
  { name: "Fine Manipulator Arm", subcategory: "Manipulation", cost: "350", availability: "2", game_notes: "Retractable precision arm extending up to 0.5m. Servo-boosted for typing and small-object manipulation. Various tip options (claws, pincers, 3- or 5-fingered hands).", source: "REUP Droids p.392" },
  { name: "Retractable Heavy Grasping Arm", subcategory: "Manipulation", cost: "550", availability: "2", game_notes: "Stores flush to chassis; extends 0.5m with servo-boosted grip. +2D lifting when deployed.", source: "REUP Droids p.392" },
  { name: "Welding Arm", subcategory: "Manipulation", cost: "—", availability: "2", game_notes: "Arc-welding appendage. Performs structural repairs; can be improvised as a melee weapon (STR+1D damage).", source: "Various WEG droid templates" },
  { name: "Extendable Arm with Buffer", subcategory: "Manipulation", cost: "—", availability: "2", game_notes: "Long-reach arm with polishing buffer. Common on custodial and detail droids.", source: "Various WEG droid templates" },
  { name: "Grasping Claw", subcategory: "Manipulation", cost: "—", availability: "2", game_notes: "Basic two-prong gripper. Handles standard objects; no fine manipulation.", source: "Various WEG droid templates" },
  { name: "Heavy Scooper", subcategory: "Manipulation", cost: "—", availability: "2", game_notes: "Large bucket-style implement for moving loose material. +1D lifting while scooping.", source: "Various WEG droid templates" },
  { name: "Cargo Winch (AR5G)", subcategory: "Manipulation", cost: "400 (basic) / 800 (heavy)", availability: "2", game_notes: "Utilitech AR5G Cargo Winch. 50m durasteel cable, supports 80 kg. Heavy version grants +1D lifting.", source: "REUP Droids p.391" },
  { name: "Circular Saw (Type 10)", subcategory: "Manipulation", cost: "500 (external) / 1,200 (retractable internal)", availability: "2", game_notes: "Industrial Automaton Type 10 Cutting Saw. 4D damage, 0.3m range. Limited as a weapon. Retractable model requires droid minimum 0.3m tall/long.", source: "REUP Droids p.391" },
  { name: "Internal Grapple Gun", subcategory: "Manipulation", cost: "200", availability: "2", game_notes: "Fires a magnetic grappling hook with 15m of ultra-thin cord. Range 2-15/35/100. External magazine holds +100m of cord. Detach as free action.", source: "REUP Droids p.392" },
  { name: "Multi-Function Apparatus", subcategory: "Manipulation", cost: "80", availability: "1", game_notes: "Appendage housing up to 3 tools or weapons. Only one active at a time; switching is a free action.", source: "REUP Droids p.392" },
  { name: "Quick-Release Coupling", subcategory: "Manipulation", cost: "50 (appendage) + 10 per tool", availability: "1", game_notes: "Detachable appendage-tool interface. Attaching/detaching a tool is an action, no roll.", source: "REUP Droids p.392" },
  { name: "Welding Laser (HL)", subcategory: "Manipulation", cost: "1,200", availability: "2", game_notes: "Drever Corporation HL Automata-Assisted Welding Laser. 5 cm tool, 3 cm range, 5D+2 damage. External pack: 10 rounds. On droid power: 5 rounds (longer requires Moderate stamina/Strength or 2D self-damage per round, max 10 rounds total).", source: "REUP Droids p.392" },

  // --- Defensive / Weapon Systems ----------------------------
  { name: "Stun Appendage", subcategory: "Weaponry", cost: "—", availability: "3", game_notes: "Built-in stun rod. Typically 6D stun damage at melee range.", source: "Various WEG droid templates" },
  { name: "Stun Bolt Projector", subcategory: "Weaponry", cost: "—", availability: "3", game_notes: "Ranged stun weapon. Shoots stunning ionized pulses. Typical: 5D stun, range 3-7/25/50.", source: "Various WEG droid templates" },
  { name: "Chemical Spray Appendages", subcategory: "Weaponry", cost: "—", availability: "2", game_notes: "Nozzle array for dispensing fire retardant, radiation foam, or adhesive. Non-lethal by default.", source: "WEG40131 Thrawn Trilogy Sourcebook (decontamination droid)" },
  { name: "Blaster Recharge Interface", subcategory: "Weaponry", cost: "300", availability: "1, F", game_notes: "Hand accessory. Recharges a standard blaster power pack in 3 rounds. Drains droid energy — 1-10 recharges per full depletion.", source: "REUP Droids p.392" },
  { name: "Concealed Vibroblade", subcategory: "Weaponry", cost: "500 (basic) / 800 (sensor-resistant)", availability: "2, X", game_notes: "Concealed melee weapon, typically wrist or finger on humanoid droids. STR+3D (max 6D+2). Basic: Easy sensors reveals. Sensor-resistant: Difficult sensors to detect.", source: "REUP Droids p.392" },
  { name: "Droid Shields", subcategory: "Weaponry", cost: "2,500-10,000 (by bonus)", availability: "3, X", game_notes: "Energy shield. Cost by bonus: +2=2,500; +1D+2=5,000; +2D+1=7,500; +3D=10,000. Once droid takes Damaged+, shield blows — Moderate droid programming to reactivate.", source: "REUP Droids p.392" },
  { name: "Electric Defense Grid", subcategory: "Weaponry", cost: "3,000", availability: "2, R or X", game_notes: "Installed into the droid's armor/outer casing. Any melee or brawling contact deals 3D energy damage to the attacker.", source: "REUP Droids p.392" },
  { name: "Hidden Holster", subcategory: "Weaponry", cost: "500", availability: "2, X", game_notes: "Installed in a droid's leg; holds a small weapon. Activating as a free action opens the holster. +2 to blaster for quickdraw.", source: "REUP Droids p.393" },
  { name: "Internal Defenses", subcategory: "Weaponry", cost: "1,500", availability: "2, R", game_notes: "Triggers when a character accesses maintenance panels without permission. 3D damage to the intruder, droid unharmed. Disabled with Very Difficult security/droid repair (1 hour) or after 10 attacks.", source: "REUP Droids p.393" },
  { name: "Micro Shield", subcategory: "Weaponry", cost: "600 (droid) / 400 (hand-held)", availability: "3, F", game_notes: "Collapsible mini energy shield. If melee parry beats attacker's blaster roll, +1D to resist energy damage. Hand-held version runs 1 hour per cell.", source: "REUP Droids p.393" },
  { name: "Onboard Blaster", subcategory: "Weaponry", cost: "1,200 (basic) / 1,600 (sensor-resistant) / 800 (exterior)", availability: "3, X", game_notes: "Concealed energy weapon. Base 4D damage, range 3-10/30/120, 100 shots. +1D per 400 cr (max 6D). Basic: Easy sensors reveals; sensor-resistant: Very Difficult sensors or Heroic search.", source: "REUP Droids p.393" },
  { name: "Onboard Flame Projector", subcategory: "Weaponry", cost: "600 (basic) / 1,000 (sensor-resistant) / 200 per extra canister", availability: "3, X", game_notes: "Droid-operated flame projector. Damage 5D first round, 3D next 5 rounds unless extinguished. Range 3-4/5/7, Fire Rate 1/2, 10 ammo. Tank damage: 3D corrosive/round until washed off.", source: "REUP Droids p.393" },
  { name: "Onboard Grenade Launcher", subcategory: "Weaponry", cost: "800 (standard) / 1,200 (sensor-resistant)", availability: "3, X", game_notes: "Concealed grenade launcher. Range 5-25/100/250, Fire Rate 1/2, 3 ammo. Damage varies by grenade. Cannot equip on droids smaller than 1m.", source: "REUP Droids p.393" },
  { name: "Projectile Hands", subcategory: "Weaponry", cost: "200 (installation 250)", availability: "2, F", game_notes: "Launching projectile appendage. Range 2/7/12, 3D+2 damage. Can attack a target or knock a blaster away.", source: "REUP Droids p.393" },
  { name: "Rocket Arm", subcategory: "Weaponry", cost: "2,000", availability: "2, X", game_notes: "Hollowed-out arm with short-range rocket engine. Range 3-30/120/350, 5D/3D damage, blast radius 0-1/2. Arm suffers -3D for fine manipulation. Failed install (Difficult droid programming/repair) may cause detonation while attached.", source: "REUP Droids p.393" },
  { name: "Shield Expansion Module", subcategory: "Weaponry", cost: "250-1,000 (by shield bonus)", availability: "3, X", game_notes: "Extends shield radius to adjacent characters (Moderate shields to extend one fire arc). Cost by installed shield: +2=250, +1D+2=500, +2D+1=750, +3D=1,000. Larger droids can install a second module.", source: "REUP Droids p.393" },
  { name: "Taser", subcategory: "Weaponry", cost: "250", availability: "2, F", game_notes: "Fires two projectiles on thin wires delivering an electric charge. 4D stun/ion damage, range 0-2/4/7. Doubles as electroshock probe in melee.", source: "REUP Droids p.394" },

  // --- Utility / Iconic --------------------------------------
  { name: "Restraining Bolt (Factory-Installed)", subcategory: "Utility", cost: "—", availability: "1", game_notes: "Standard obedience device. A matching droid caller enforces commands; removal requires a Moderate security roll.", source: "Core Rulebook; universal" },
  { name: "Scomp-Link (Nexus)", subcategory: "Utility", cost: "800", availability: "2", game_notes: "Cybot Galactica Nexus Scomp-link. Transfers data between droid and virtually any data-storage device. +1D computer programming/repair when searching networks.", source: "REUP Droids p.389" },
  { name: "Power Cell (Standard)", subcategory: "Utility", cost: "—", availability: "1", game_notes: "Baseline rechargeable droid power source. Powers most service droids for weeks between charges.", source: "Various WEG droid templates" },
  { name: "Publictechnic Power Cell", subcategory: "Utility", cost: "—", availability: "2", game_notes: "Heavy-duty rechargeable cell used in industrial droids. Longer duration than standard cells.", source: "Various WEG droid templates" },
  { name: "Holographic Recorder and Projector", subcategory: "Utility", cost: "—", availability: "2", game_notes: "Combined record-and-play holographic system. Captures and displays 3D imagery.", source: "Various WEG droid templates" },
  { name: "Holoprojector (G-series)", subcategory: "Utility", cost: "300-8,000", availability: "2", game_notes: "SoroSuub G-series Holoprojection Unit. Basic model (R-series astromech standard) projects prerecorded holograms up to 1.5m away at 0.5-10m image size.", source: "REUP Droids p.394" },
  { name: "Holographic Image Disguiser", subcategory: "Utility", cost: "20,000 (basic) / 40,000 (advanced)", availability: "3, R or X", game_notes: "Array of holographic projectors that disguise the droid, matching movements and vocabulator. Very Difficult search to see through (sensors/cameras/droids +2D). Advanced model adds environmental tracking — Heroic search, sensor bonus reduced to +1D.", source: "REUP Droids p.395" },
  { name: "Holographic Game System", subcategory: "Utility", cost: "300", availability: "1", game_notes: "Fifteen popular holo-games including dejarik and sabacc. Uses droid's holoprojector (sold separately). Ten additional games installable with Moderate computer programming/repair.", source: "REUP Droids p.394" },
  { name: "Medical SupportLink", subcategory: "Utility", cost: "—", availability: "2", game_notes: "Dedicated data link to hospital or emergency medical computer. +1D to medical skills when interfaced.", source: "Various WEG droid templates (medical droids)" },
  { name: "DataLink", subcategory: "Utility", cost: "—", availability: "1", game_notes: "Generic wired data-transfer port. Accepts standard datapad / datacard / computer cable connections.", source: "Various WEG droid templates" },
  { name: "Espionage Hardwired Module", subcategory: "Utility", cost: "—", availability: "X", game_notes: "Covert surveillance hardware. Survives standard memory wipes — must be physically extracted.", source: "WEG40131 Thrawn Trilogy Sourcebook" },
  { name: "DNA Tracer Module", subcategory: "Utility", cost: "—", availability: "3", game_notes: "+3D to search when tracking a target via residual DNA traces.", source: "WEG40075 Galaxy Guide 11 (Seeker Droid)" },
  { name: "Threat Evaluation Module", subcategory: "Utility", cost: "—", availability: "3", game_notes: "Tactical subprocessor that decides whether to engage, disarm, or request reinforcement.", source: "WEG40075 Galaxy Guide 11 (Seeker Droid)" },
  { name: "IMR Module", subcategory: "Utility", cost: "—", availability: "3", game_notes: "Integrated Maintenance and Repair module. Bundles tools and schematics for weapons/armor servicing.", source: "WEG40073 Galaxy Guide 10 (Armorer Droid)" },
  { name: "System Diagnosis Package", subcategory: "Utility", cost: "—", availability: "2", game_notes: "Self-test and error-reporting suite. +1D to droid repair when diagnosing faults.", source: "Various WEG droid templates" },
  { name: "Collapsible Construction", subcategory: "Utility", cost: "2,000", availability: "2", game_notes: "Structural mod allowing the droid to fold and collapse for storage. Decreases size up to 45%. Enters standby mode while collapsed.", source: "REUP Droids p.394" },
  { name: "Concealed Item", subcategory: "Utility", cost: "Item cost + compartment cost × 2", availability: "2, X", game_notes: "Functional item installed as a concealed component — blaster in an arm, disguised as a beam cutter, etc. Very Difficult search to discover.", source: "REUP Droids p.394" },
  { name: "Courier Compartment", subcategory: "Utility", cost: "200 (+200 for toaster system)", availability: "2, X", game_notes: "Hidden storage in torso/head/limb. Very Difficult search to detect. Optional toaster destroys contents with plasma on trigger.", source: "REUP Droids p.394" },
  { name: "Credit Reader", subcategory: "Utility", cost: "50", availability: "2, F", game_notes: "Credit analyzer. +2D vs forgery rolls for financial documents. Instantly counts hard credits as a free action.", source: "REUP Droids p.394" },
  { name: "Emergency Oxygen Supply", subcategory: "Utility", cost: "200", availability: "2", game_notes: "30 minutes of breathable air. Attachable via breath mask or used to recharge a vac suit. Common on rescue and medical droids.", source: "REUP Droids p.394" },
  { name: "Hidden Core", subcategory: "Utility", cost: "200 (+200 deluxe)", availability: "2, R", game_notes: "Backup that retains programming, skills, and personality after a memory wipe. 1D days after wipe, Difficult droid programming/repair restores. Deluxe: Heroic difficulty to discover.", source: "REUP Droids p.394" },
  { name: "ID Dodge", subcategory: "Utility", cost: "5,000", availability: "3, X", game_notes: "Biometric security countermeasure. +2D+2 security to defeat retinal/fingerprint scans by simulating biological data.", source: "REUP Droids p.394" },
  { name: "Personality Downloader", subcategory: "Utility", cost: "5,000", availability: "3, X", game_notes: "Illegal override device. Plugs into droid's dataport. Droid programming/repair vs droid's willpower — on failure, personality copies over in 5 min. Every 10 min the original can contest to regain control.", source: "REUP Droids p.394" },
  { name: "Radiant Heat Element", subcategory: "Utility", cost: "200", availability: "1", game_notes: "Droid heater radiates warmth from the torso. Can boil water or cook food. Highest setting: 2D+1 damage adjacent, 3D+1 on contact.", source: "REUP Droids p.394" },
  { name: "Remote Limb Control", subcategory: "Utility", cost: "1,500 (basic) / 6,000 (deluxe)", availability: "3", game_notes: "Limbs removable while retaining full control. Built-in repulsor: 10m flight ceiling, 40m max range from droid. Deluxe: multiple limbs active at once.", source: "REUP Droids p.394" },
  { name: "Remote Processor", subcategory: "Utility", cost: "1,000-1,000,000 (by range)", availability: "2, R", game_notes: "Baktoid Combat Automata Remote Processor. Droid can't act independently unless it has a backup processor. Modified stock droids take -1D Perception initiative and -1D reactions. Costs: 5km=1,000; 50km=10,000; 500km=100,000; 5,000km=1,000,000.", source: "REUP Droids p.395" },
  { name: "Remote Processor (Backup)", subcategory: "Utility", cost: "100", availability: "2, R", game_notes: "Baktoid Combat Automata TD-12C. Lets a remote-controlled droid continue on last instructions if the primary processor fails or signal is lost.", source: "REUP Droids p.395" },
  { name: "Remote Receiver", subcategory: "Utility", cost: "70", availability: "2, R", game_notes: "Baktoid Combat Automata TX-191 Receiver. Allows a droid to receive instructions from a remote processor.", source: "REUP Droids p.395" },
  { name: "Remote Receiver Jammer", subcategory: "Utility", cost: "2,000", availability: "2, X", game_notes: "Backpack transmitter + hand controller. Jams remote-processor droids within 100m (opposed communications vs Perception). Droid is rendered useless unless it has a backup processor.", source: "REUP Droids p.395" },
  { name: "Remote Receiver Signal Booster", subcategory: "Utility", cost: "500", availability: "3", game_notes: "Extends remote-processor receiving range by 50%. Heroic communications pushes it to 100% farther for 1 hour.", source: "REUP Droids p.395" },
  { name: "Remote Starship Starter", subcategory: "Utility", cost: "2,800", availability: "2, R", game_notes: "2-km range controller. Runs diagnostics and pre-flight startup in 5 minutes so the ship is ready for immediate takeoff.", source: "REUP Droids p.395" },
  { name: "Sensor-Shielded Storage Compartment", subcategory: "Utility", cost: "500 (external) / 8,000 (internal)", availability: "3, X", game_notes: "Illegally-modified Utilitech Droid Storage Module. Sensor-absorbent — Very Difficult sensors to see contents. External immediately visible; internal Very Difficult search/Perception or Difficult sensors to detect. Max 2 compartments on droids ≥1m.", source: "REUP Droids p.395" },
  { name: "Silence-Bubble Generator", subcategory: "Utility", cost: "3,500", availability: "2, R", game_notes: "5-meter sound dampening radius. Listeners outside (or inside trying to hear out) take -3D to search rolls.", source: "REUP Droids p.396" },
  { name: "Storage Compartment", subcategory: "Utility", cost: "200 (external) / 4,000 (internal)", availability: "2", game_notes: "Utilitech Droid Storage Module. 20×10×8 cm internal volume. Holds a comlink, small blaster, datapad or medpac. Moderate search/Perception (Easy sensors) to detect internal. Max 2 on droids ≥1m.", source: "REUP Droids p.396" },
  { name: "Storage Compartment (Spring-Loaded)", subcategory: "Utility", cost: "150", availability: "2", game_notes: "Rim Securities F-9 ejection system. Lets the droid eject a small object (≤4 kg) up to 8 meters. Aiming uses thrown weapons skill. Requires a standard or shielded storage compartment to attach to.", source: "REUP Droids p.396" },
  { name: "Survival Kit (Droid)", subcategory: "Utility", cost: "100", availability: "2", game_notes: "Small fridge, water recycler/dispenser, rechargeable glow rod, fire sparker. Grants +1D to the droid master's survival rolls.", source: "REUP Droids p.396" },
  { name: "Video Screen", subcategory: "Utility", cost: "10 per cm² of screen", availability: "1", game_notes: "Built-in display for text, translations, diagnostics, pictures. Sizes 5-50 cm.", source: "REUP Droids p.396" },
  { name: "Voice-Print Command Lock", subcategory: "Utility", cost: "400", availability: "1", game_notes: "Voice-recognition security. Droid analyzes its master's voice and ignores commands from anyone else. Recorded/spoofed command attempts: droid programming vs droid's willpower +5.", source: "REUP Droids p.397" },

  // --- Databases (specialized memory modules) ----------------
  { name: "Database — Weapons", subcategory: "Database", cost: "—", availability: "2", game_notes: "Detailed specs on most known personal weapons. Adds to (A) weapon engineering and armor/blaster repair.", source: "WEG40073 Galaxy Guide 10 (Armorer Droid)" },
  { name: "Database — Medical", subcategory: "Database", cost: "—", availability: "2", game_notes: "Medical procedures, drug interactions, and species physiology. Adds to first aid and (A) medicine rolls.", source: "Various WEG droid templates" },
  { name: "Database — Cargo Codes", subcategory: "Database", cost: "—", availability: "2", game_notes: "Current cargo classification codes across major shipping networks. Aids streetwise and value skills.", source: "Various WEG droid templates" },
  { name: "Database — Repair", subcategory: "Database", cost: "—", availability: "2", game_notes: "Schematics and repair procedures for common ships, vehicles, and droids. +1D to relevant repair skills.", source: "Various WEG droid templates" },
  { name: "Database — Languages", subcategory: "Database", cost: "—", availability: "2", game_notes: "Bulk language storage (separate from TranLang translation logic). Adds to languages rolls.", source: "Various WEG droid templates" },
  { name: "Database — Gambling", subcategory: "Database", cost: "—", availability: "2", game_notes: "Rules, odds, and procedures for ~100 games of chance. Adds to gambling rolls.", source: "WEG40075 Galaxy Guide 11 (Gambling Droid)" },
  { name: "Database — Galactic Fashion", subcategory: "Database", cost: "—", availability: "2", game_notes: "Regional fashion, etiquette, and social customs. Used by protocol and concierge droids.", source: "Various WEG droid templates" },
  { name: "Database — Food Preparation", subcategory: "Database", cost: "—", availability: "2", game_notes: "Recipes, dietary profiles, and cooking techniques across thousands of cultures.", source: "Various WEG droid templates" },
  { name: "Database — Entomology", subcategory: "Database", cost: "—", availability: "2", game_notes: "Classification of insect and arthropod species. Used by scout and field-research droids.", source: "Various WEG droid templates" },

  // --- Restraint / Control -----------------------------------
  { name: "Restraining Bolt", subcategory: "Restraint", cost: "50", availability: "1", game_notes: "Small receiver attached to a droid that bypasses motivational programming. A droid fitted with a restraining bolt must obey commands sent by a matching Caller. The droid cannot resist the bolt's effects. Install/remove: droid repair.", source: "REUP Droids p.398" },
  { name: "Caller", subcategory: "Restraint", cost: "100-500", availability: "1", game_notes: "Compact short-range signaling device (droid programming). Broadcasts directly into a droid's motivational processor via its restraining bolt. Simple callers send basic activate/deactivate commands; sophisticated models handle complex orders. Average range 20m.", source: "REUP Droids p.398" },
  { name: "Rental Restraining Bolt", subcategory: "Restraint", cost: "10", availability: "2", game_notes: "Standard bolt with a credit reader. Deposit credits to enable control for a timed period; droid deactivates when time expires until more credits are fed in.", source: "REUP Droids p.398" },
  { name: "Droid Remote Control", subcategory: "Restraint", cost: "500", availability: "2", game_notes: "Advanced restraining-bolt variant. Allows the owner (via droid caller) to move the droid using its own locomotion at Cautious speed. Cannot compel other systems or possessions.", source: "REUP Droids p.398" },

  // --- Support Infrastructure --------------------------------
  { name: "Droid Oil Bath", subcategory: "Infrastructure", cost: "50-1,000 (service) / 1,500 (character-scale unit) / 5,000 (speeder-scale unit)", availability: "1", game_notes: "Fryil Industries TD series. Cleanses movement-control actuators. Giving a droid an oil bath negates the Dexterity penalties accrued from existing in a harsh environment without bathing (-1 pip per month in harsh environment).", source: "REUP Droids p.397" },
  { name: "Droid Memory Wipe", subcategory: "Infrastructure", cost: "50-500 (service)", availability: "1", game_notes: "Difficult droid programming. Returns the droid's personality matrix to basic configuration. Any 'tinkered' pip improvements are lost. Hardwired skills (factory or previous owner) remain intact.", source: "REUP Droids p.398" },
  { name: "Droid Command Station", subcategory: "Infrastructure", cost: "10,000", availability: "1, F", game_notes: "Password-protected overseer station. Requires comlinks/remote receivers on all droids. Grants +2D overseer's command skill, maintains active comms, locates droids (via tracking device or bolt), reports droid status, performs basic reprogramming, and translates Binary↔Basic.", source: "REUP Droids p.398" },
  { name: "Droid Battle Station", subcategory: "Infrastructure", cost: "50,000 per 100 droids", availability: "1, R", game_notes: "Scaled-up command station for combat direction of hundreds to thousands of droids. Some emulate droid commanders — typical brain tactics 4D+2, command 6D (varies).", source: "REUP Droids p.398" },
  { name: "Droid Recharge Station", subcategory: "Infrastructure", cost: "4,000", availability: "1", game_notes: "Full recharge in one hour. Many starports charge 20 cr per public use. Provides an Easy droid repair diagnostic including damage status and operational check on appendages/systems/tools.", source: "REUP Droids p.398" },
  { name: "Droid Socket", subcategory: "Infrastructure", cost: "10,000 (usually included in ship price)", availability: "3, R", game_notes: "Starfighter/droid interface socket. Allows astromech to pilot/copilot, manage shields, reroute power, repair, run comms/sensors, input hyperspace coords, and operate ejection systems. Weapons firing and unapproved hyperspace jumps prohibited without pilot override. Retrofitting requires Very Difficult starfighter/transport repair.", source: "REUP Droids p.398" },

];

// Expose as a window global for index.html's pcPopulateEquipGrid helper.
if (typeof window !== 'undefined') window.DROID_COMPONENTS = DROID_COMPONENTS;
