const FORCE_POWERS_DATA = [
 {
  "number": 1,
  "name": "Absorb/Dissipate Energy",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for sunburn/minor energy; Easy for intense sun; Moderate for solar wind/modest energy; Difficult for radiation storms/intense energy. For blaster bolts and Force lightning: Moderate plus attack damage roll.",
  "timeToUse": "One round",
  "keepUp": "Yes (constant sources only, not blaster bolts/lightning)",
  "effect": "Allows the Jedi to absorb or dissipate energy, including light, heat, radiation and blaster bolts. A successful control roll means the energy is dissipated. If the user fails the roll, she takes full damage. May be used to ward off sunburn, heat-stroke and radiation exposure, as well as withstand intense heat. May also absorb blaster bolts (as Darth Vader did on Cloud City). Must activate in the same round to absorb blaster bolt or Force lightning \u2014 must roll before the attack lands. Cannot be used after the attack has hit.",
  "source": "R&E (page 142-143)"
 },
 {
  "number": 2,
  "name": "Accelerate Healing",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy for wounded; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "A Jedi who uses this power successfully may make two natural healing rolls for the current day (12 hours apart) regardless of the severity of the injury. The Jedi gets a +2 modifier to both Strength rolls to heal. Accelerate healing may only be attempted once per day.",
  "source": "R&E (page 143)"
 },
 {
  "number": 3,
  "name": "Concentration",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy if relaxed and at peace; Difficult if filled with aggression, fear or other negative emotions; Very Difficult if acting on those negative emotions.",
  "timeToUse": "One round",
  "keepUp": "No",
  "effect": "The Jedi clears all negative thoughts from her mind, concentrating on one specific task. If successful, the Jedi may add +4D to any one action in that round. The Jedi may do nothing other than using concentration and that one skill for one action. No bonus if anything else is done in that round, including duplicate uses of the same skill or dodges or parries. May be used in conjunction with Force Points or Character Points. Only in effect for one round.",
  "source": "R&E (page 143)"
 },
 {
  "number": 4,
  "name": "Contort/Escape",
  "category": "Control",
  "prereqs": "03,06,09",
  "darkSide": false,
  "difficulty": "Very Easy for loose bonds; Easy for hand binder; Moderate for serious restraints; Difficult to Heroic for maximum security (varies at GM discretion).",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The character may escape bonds by contorting in painful and difficult (but still physically possible) ways. By stretching, twisting, and dislocating joints a Jedi can escape almost any physical restraining device. Jedi are trained to block out the pain and focus on the task at hand.",
  "source": "Tales of the Jedi Companion (page 41), Jedi Academy Sourcebook (page 42)"
 },
 {
  "number": 5,
  "name": "Control Disease",
  "category": "Control",
  "prereqs": "02",
  "darkSide": false,
  "difficulty": "Very Easy for mild infection (cold); Easy for modest infection (high fever, severe flu); Moderate for severe illness (gangrene, hive virus); Difficult for life-threatening disease; Very Difficult for massive long-standing disease; Heroic for rapid-acting life-threatening disease.",
  "timeToUse": "30 minutes to several uses over weeks",
  "keepUp": "No",
  "effect": "Allows the Jedi to direct and control the anti-bodies and healing resources of her body to throw off an infection or resist diseases. Requires 30 minutes of meditation. If the disease is life-threatening or long-standing, the Jedi must make repeated skill attempts over several weeks or months to cure entirely (GM discretion on how many rolls and how often).",
  "source": "R&E (page 143)"
 },
 {
  "number": 6,
  "name": "Control Pain",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for wounded or stunned; Easy for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round",
  "keepUp": "Yes (new roll required when injured again at new injury level)",
  "effect": "A wounded Jedi who controls pain can act as if she has not been wounded, starting the round after the power roll. The wound is not healed, but the character doesn't suffer the penalties of being wounded: wounded Jedi has no die code penalties; incapacitated or mortally wounded can act normally. Can shrug off stun results. However, the character is still injured and prone to getting worse. Mortally wounded Jedi may still die from injuries even if not feeling pain.",
  "source": "R&E (page 143-144)"
 },
 {
  "number": 7,
  "name": "Detoxify Poison",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Easy for very mild poison (alcohol); Easy for mild poison; Moderate for average poison; Difficult for virulent poison; Very Difficult to Heroic for neurotoxin.",
  "timeToUse": "Five minutes",
  "keepUp": "No",
  "effect": "Allows a Jedi to detoxify or eject poisons that have entered her body. If the Jedi makes the power roll, the poison doesn't affect her.",
  "source": "R&E (page 144)"
 },
 {
  "number": 8,
  "name": "Emptiness",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Moderate. Note: Characters consumed by the dark side may not use this power.",
  "timeToUse": "",
  "keepUp": "Yes (see description)",
  "effect": "The user empties her mind and allows the Force to flow through her. The character falls into deep meditation, unconscious and oblivious to surroundings. Difficult to sense or affect with Force \u2014 add the emptiness roll to the difficulty for another character's sense roll (or control roll if power doesn't use sense). After coming out: +6 bonus to all Force skill rolls for a period equal to time spent in emptiness, reduced by -1 per Dark Side Point. Characters dehydrate and hunger normally \u2014 some initiates have died in emptiness. Difficult control roll to bring herself out. Player must declare duration when entering. May attempt to exit: when stated time passes, once each hour beyond the limit, or when body takes damage more serious than stun.",
  "source": "R&E (page 144)"
 },
 {
  "number": 9,
  "name": "Enhance Attribute",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One round",
  "keepUp": "No (duration determined by roll, extendable with Character Points)",
  "effect": "Increases a single attribute for a limited time. All skills controlled by the enhanced attribute increase by the same amount. Only one attribute at a time \u2014 enhancing a second drops the first. Duration extendable by spending Character Points (+1 round per point, spent any time before power fades). Beat difficulty by 0-13: +1D for 3 rounds. Beat by 14-25: +2D for 2 rounds. Beat by 26+: +3D for 1 round.",
  "source": "Tales of the Jedi Companion (page 44-45)"
 },
 {
  "number": 10,
  "name": "Force of Will",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Easy.",
  "timeToUse": "One round",
  "keepUp": "Yes",
  "effect": "The character uses Willpower skill to fight hostile mind-based Force powers. Add Willpower to Control or Perception to create a 'protection number.' If attack roll < Control/Perception: no effect. If attack roll > protection number: full effects. If attack roll between the two: protected, but Willpower is 'battered' (-1D to Willpower, reroll protection number). If Willpower reaches 0D, power drops automatically. Recovery: 1 day per 1D, or 1 hour in emptiness/rage per 1D. Does NOT protect against Force lightning, Force storms, or telekinetically hurled objects (external powers). DOES work against injure/kill, telekinetic kill, inflict pain, and other powers that directly use the Force on the target.",
  "source": "Tales of the Jedi Companion (page 45), Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 11,
  "name": "Hibernation Trance",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Places the Jedi into a deep trance, slowing all body functions. Heartbeat slows, breathing barely perceivable, falls unconscious. Can heal while in trance but can do nothing else. Appears dead unless specifically tested. Another Jedi with sense or life detection can detect Force within the character. Player must declare wake conditions (time or stimuli). Another Jedi can use 'place another in hibernation trance' to bring user out. Uses about 1/10th normal air. Survives: 1 week dry climate / 1 month wet climate without water (IV drip = indefinite); up to 3 months without food (IV sugar = 1 year).",
  "source": "R&E (page 144)"
 },
 {
  "number": 12,
  "name": "Instinctive Astrogation",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Very Difficult. Modified by astrogation difficulty: Very Easy +0, Easy +5, Moderate +10, Difficult +15, Very Difficult +20, Heroic +30.",
  "timeToUse": "One minute",
  "keepUp": "No",
  "effect": "The Jedi calculates hyperspace equations mentally rather than feeling them through the Force (the sense-based version). If control roll succeeds, a Very Easy astrogation roll enters the routes into the nav computer. If the roll fails, the Jedi overlooks an obstacle \u2014 astrogation difficulty increases to Very Difficult. If missed by 5+, astrogation difficulty increases to Heroic. A largely unknown and rarely studied application \u2014 little more than a curiosity among Jedi theoreticians.",
  "source": "Tales of the Jedi Companion (unconfirmed)"
 },
 {
  "number": 13,
  "name": "Rage",
  "category": "Control",
  "prereqs": "11",
  "darkSide": true,
  "difficulty": "Difficult. Note: Can only be used by characters consumed by the Dark Side. Use gives a Dark Side Point.",
  "timeToUse": "",
  "keepUp": "No (see description)",
  "effect": "Dark side counterpart to Emptiness. Character enters a trance, appearing lifeless, face clenched in horror. Must declare duration. Difficult control roll every 4 hours to stay in trance. After exiting: +10 modifier to all Force skill rolls for a period equal to time in rage. Then takes 1D damage per 2 hours spent in rage. Adds rage control roll to difficulty of Force powers targeting the user. Dehydrates twice as fast. -1D to Strength vs physical/energy damage while in rage. Physical contact by a living being may revive (Moderate control roll) and provoke instant berserker attack \u2014 Difficult control roll to stop before killing the person. Can anticipate a foe's arrival with Difficult sense roll (life sense) when entering rage \u2014 Easy control roll to awaken instantly when expected person comes within 5 meters. Can be used as preparation for transfer life \u2014 original body consumed by dark side (blue flames), 1D damage per 3 points over difficulty (3m blast radius).",
  "source": "Dark Empire Sourcebook (page 68), Tales of the Jedi Companion (page 46)"
 },
 {
  "number": 14,
  "name": "Reduce Injury",
  "category": "Control",
  "prereqs": "06",
  "darkSide": false,
  "difficulty": "Moderate for incapacitated; Difficult for mortally wounded; Very Difficult for dead.",
  "timeToUse": "Must be used same round as injury or immediately following round",
  "keepUp": "No",
  "effect": "Reduces injury suffered to wounded. Costs a Force Point. If the original injury would have killed the character, the GM inflicts a relevant permanent injury. Note: Not always a 'selfish' act to save one's life \u2014 character might get the Force Point back if fighting to save friends from certain doom (could be considered heroic).",
  "source": "R&E (page 144)"
 },
 {
  "number": 15,
  "name": "Remain Conscious",
  "category": "Control",
  "prereqs": "06",
  "darkSide": false,
  "difficulty": "Easy for stunned; Moderate for incapacitated; Difficult for mortally wounded.",
  "timeToUse": "One round (must be first action of round)",
  "keepUp": "No",
  "effect": "Allows a Jedi to remain conscious after injuries that would cause unconsciousness. When suffering such injury, loses all other actions for the rest of the round but stays conscious. At the beginning of next round, must attempt to activate as first action (cannot dodge or parry). If unsuccessful, passes out immediately. If successful, may perform one other action that round (often control pain). After that action, lapses into unconsciousness unless control pain or similar power is activated.",
  "source": "R&E (page 144-145)"
 },
 {
  "number": 16,
  "name": "Remove Fatigue",
  "category": "Control",
  "prereqs": "02,06",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "",
  "keepUp": "Yes",
  "effect": "Combats the effects of strenuous work by manipulating the Force to eject bodily toxins more efficiently, allowing greater stamina. While kept up, must make a stamina check once per day. Must fail two stamina checks before becoming fatigued. Still must eat and drink normally. If fatigued (two failed checks): -1D penalty to all attributes and skills for 1D hours. Note: Cannot be used for Lifting \u2014 use Enhance Attribute instead.",
  "source": "Tales of the Jedi Companion (page 47), Jedi Academy Sourcebook (page 44)"
 },
 {
  "number": 17,
  "name": "Resist Stun",
  "category": "Control",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "Moderate.",
  "timeToUse": "One minute",
  "keepUp": "Yes",
  "effect": "Prepares the Jedi's body to resist stun damage. Must be activated before suffering any damage. Successful roll allows the Jedi to resist all stun results except unconscious. An unconscious result forces the Jedi to drop the power (considered stunned instead). Other injuries (wounded, incapacitated, mortally wounded, killed) are treated normally.",
  "source": "R&E (page 145)"
 },
 {
  "number": 18,
  "name": "Short-Term Memory Enhancement",
  "category": "Control",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "Difficult.",
  "timeToUse": "",
  "keepUp": "No",
  "effect": "The Jedi can replay recent events to examine images and peripheral occurrences more carefully. Can freeze images and scan memory tracks to recall details that were seen but didn't register consciously. Can alert the Jedi to information, items, characters, or anything that passed before their senses. If the GM provided clues that players missed, this power can recall them. How far back: beat difficulty by 0-8 = current episode; 9-20 = last episode; 21+ = last two episodes.",
  "source": "Tales of the Jedi Companion (page 47)"
 },
 {
  "number": 19,
  "name": "Beast Languages",
  "category": "Sense",
  "prereqs": "24,30,35,44",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 20,
  "name": "Combat Sense",
  "category": "Sense",
  "prereqs": "21,23,43",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 21,
  "name": "Danger Sense",
  "category": "Sense",
  "prereqs": "23,43",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 22,
  "name": "Instinctive Astrogation (Sense Variation)",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 23,
  "name": "Life Detection",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 24,
  "name": "Life Sense",
  "category": "Sense",
  "prereqs": "23",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 25,
  "name": "Life Web",
  "category": "Sense",
  "prereqs": "23,24,31",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 26,
  "name": "Magnify Senses",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 27,
  "name": "Merge Senses",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 28,
  "name": "Postcognition",
  "category": "Sense",
  "prereqs": "11,23,31",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 29,
  "name": "Predict Natural Disaster",
  "category": "Sense",
  "prereqs": "21,23,26,36",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 30,
  "name": "Receptive Telepathy",
  "category": "Sense",
  "prereqs": "23,24",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 31,
  "name": "Sense Force",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 32,
  "name": "Sense Force Potential",
  "category": "Sense",
  "prereqs": "23,24,30,31",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 33,
  "name": "Sense Path",
  "category": "Sense",
  "prereqs": "08,11",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 34,
  "name": "Shift Sense",
  "category": "Sense",
  "prereqs": "26",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 35,
  "name": "Translation",
  "category": "Sense",
  "prereqs": "24,30,44",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 36,
  "name": "Weather Sense",
  "category": "Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 37,
  "name": "Bolt of Hatred",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 38,
  "name": "Dark Side Web",
  "category": "Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 39,
  "name": "Injure/Kill",
  "category": "Alter",
  "prereqs": "23,24",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 40,
  "name": "Telekinesis",
  "category": "Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 41,
  "name": "Farseeing",
  "category": "Control+Sense",
  "prereqs": "24",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 42,
  "name": "Life Bond",
  "category": "Control+Sense",
  "prereqs": "23,24,26,30",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 43,
  "name": "Lightsaber Combat",
  "category": "Control+Sense",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 44,
  "name": "Projective Telepathy",
  "category": "Control+Sense",
  "prereqs": "23,24,30",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 45,
  "name": "Accelerate Another's Healing",
  "category": "Control+Alter",
  "prereqs": "06,48",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 46,
  "name": "Aura of Uneasiness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 47,
  "name": "Control Another's Disease",
  "category": "Control+Alter",
  "prereqs": "02,05",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 48,
  "name": "Control Another's Pain",
  "category": "Control+Alter",
  "prereqs": "06",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 49,
  "name": "Control Breathing",
  "category": "Control+Alter",
  "prereqs": "03,11,40",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 50,
  "name": "Detoxify Poison in Another",
  "category": "Control+Alter",
  "prereqs": "02,06,07,45,48",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 51,
  "name": "Electronic Manipulation",
  "category": "Control+Alter",
  "prereqs": "01,63",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 52,
  "name": "Feed on Dark Side",
  "category": "Control+Alter",
  "prereqs": "31",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 53,
  "name": "Force Lightning",
  "category": "Control+Alter",
  "prereqs": "01,39,54",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 54,
  "name": "Inflict Pain",
  "category": "Control+Alter",
  "prereqs": "06,24",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 55,
  "name": "Place Another in Hibernation Trance",
  "category": "Control+Alter",
  "prereqs": "11",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 56,
  "name": "Remove Another's Fatigue",
  "category": "Control+Alter",
  "prereqs": "02,06,16,45,48",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 57,
  "name": "Return Another to Consciousness",
  "category": "Control+Alter",
  "prereqs": "06,15",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 58,
  "name": "Transfer Force",
  "category": "Control+Alter",
  "prereqs": "06,48",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 59,
  "name": "Waves of Darkness",
  "category": "Control+Alter",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 60,
  "name": "Dim Other's Senses",
  "category": "Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 61,
  "name": "Lesser Force Shield",
  "category": "Sense+Alter",
  "prereqs": "01,03,26,40",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 62,
  "name": "Force Wind",
  "category": "Sense+Alter",
  "prereqs": "26,34,40",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 63,
  "name": "Affect Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 64,
  "name": "Battle Meditation",
  "category": "Control+Sense+Alter",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 65,
  "name": "Control Mind",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 30,40,63",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 66,
  "name": "Create Force Storms",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 11,12,13,23,24,26,30,31,40,41,44",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 67,
  "name": "Doppleganger",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 06,08,23,24,26,30,31,40,44,48,58,60,63",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 68,
  "name": "Drain Life Energy",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 06,16,23,24,26,31,48",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 69,
  "name": "Drain Life Essence",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 06,11,23,24,26,30,31,40,41,44,48,58,60,63,65",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 70,
  "name": "Enhance Coordination",
  "category": "Control+Sense+Alter",
  "prereqs": "24,63",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 71,
  "name": "Force Harmony",
  "category": "Control+Sense+Alter",
  "prereqs": "23,24,30,44",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 72,
  "name": "Memory Wipe",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 06,11,23,24,26,30,31,40,41,44,60,63,65",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 73,
  "name": "Projected Fighting",
  "category": "Control+Sense+Alter",
  "prereqs": "03,40",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 74,
  "name": "Telekinetic Kill",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 06,24,39,54",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 75,
  "name": "Transfer Life",
  "category": "Control+Sense+Alter",
  "prereqs": "DS 01,02,06,07,08,11,14,15,17,23,24,26,30,31,39,40,41,44,45,48,52,54,57,58,60,63,65",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 76,
  "name": "Force Scream",
  "category": "Special",
  "prereqs": "",
  "darkSide": true,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 },
 {
  "number": 77,
  "name": "Lifemerge",
  "category": "Special",
  "prereqs": "",
  "darkSide": false,
  "difficulty": "",
  "timeToUse": "",
  "keepUp": "",
  "effect": "",
  "source": ""
 }
];
