// Notable NPCs Database — Sourcebook characters with full stat blocks
// Used by GM tab Notable NPC Lookup
const NOTABLE_NPCS = [
  // ── GELGELAR FREE PORT (WEG40217 Platt's Starport Guide p.56–78) ──
  {
    name: "Loro Eels",
    species: "Sullustan",
    system: "Gelgelar",
    location: "Gelgelar Free Port",
    affiliations: ["Eels Family", "Gelgelar Free Port Administration"],
    role: "Unofficial mayor & entrepreneur",
    type: "Sullustan Entrepreneur",
    stats: {
      DEXTERITY: { base: "2D+2", skills: { blaster: "4D+2", dodge: "5D+1" } },
      KNOWLEDGE: { base: "2D+2", skills: { "alien species": "5D", bureaucracy: "7D+2", business: "7D", languages: "4D+1", streetwise: "6D+1", value: "7D" } },
      MECHANICAL: { base: "3D+1", skills: { astrogation: "6D+1", sensors: "4D+2", "space transports": "5D+1", "starship gunnery": "4D+2" } },
      PERCEPTION: { base: "3D+1", skills: { bargain: "8D", command: "6D+2", con: "5D", forgery: "8D+2", gambling: "6D+1", hide: "5D+1", investigation: "5D", persuasion: "8D", sneak: "6D" } },
      STRENGTH: { base: "2D+1", skills: {} },
      TECHNICAL: { base: "3D+2", skills: { "droid repair": "5D+2", security: "6D+1", "space transports repair": "7D", "starfighter repair": "6D+2", "starship weapon repair": "5D+1" } }
    },
    specialAbilities: "Enhanced Senses: +2D to search and related Perception checks in low-light conditions. Location Sense: Cannot get lost in a previously visited place; +1D astrogation for planets visited before.",
    forcePoints: 2,
    characterPoints: 8,
    move: 10,
    equipment: "Blaster pistol (4D), comlink, datapad",
    capsule: "Loro Eels is Gelgelar Free Port's unofficial mayor. He and his extensive family run the starport and maintain a minimal peace in town. Eels is rarely seen in public, as he is wanted by the SoroSuub Corporation for smuggling, spacejacking, and other assorted crimes. He provides forged starship and pilot documents and other illegal services, all for a price. Eels's family runs several businesses in town, including the Nofre Repair Bay and Gelgelar Outfitters. The local population respects Eels, since he always acts in their best interests. He makes sure spacers' credits find their way into local business coffers, but also intervenes if spacers are cheated or overcharged. Some say Eels lives in a warren of watertight passages beneath the starport and part of the town. He entrusts his family members to carry out his judgments and maintain peace and economic fairness. A friendly Sullustan once you earn his trust, he tends to reflect the manner in which someone approaches him. Also a good sabacc player.",
    source: "WEG40217 Platt's Starport Guide p.62"
  },
  {
    name: "Nofre Eels",
    species: "Sullustan",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Nofre Repair Bay",
    affiliations: ["Eels Family", "Nofre Repair Bay"],
    role: "Master mechanic & repair bay operator",
    type: "Sullustan Mechanic",
    stats: {
      DEXTERITY: { base: "3D", skills: { blaster: "4D+2", "brawling parry": "4D", dodge: "4D" } },
      KNOWLEDGE: { base: "2D+2", skills: { bureaucracy: "4D", "business: starships": "6D+2", languages: "4D+2", streetwise: "3D+1", "value: starships": "6D" } },
      MECHANICAL: { base: "3D", skills: { astrogation: "4D", "capital ship piloting": "5D+2", "capital ship shields": "4D+1", sensors: "4D", "space transports": "6D" } },
      PERCEPTION: { base: "3D+1", skills: { bargain: "7D+1", command: "4D+2", forgery: "5D", gambling: "5D+2", persuasion: "4D+2" } },
      STRENGTH: { base: "2D+1", skills: { brawling: "4D", "climbing/jumping": "4D+2", lifting: "4D+1", stamina: "4D" } },
      TECHNICAL: { base: "3D+2", skills: { "capital starship repair": "5D", "computer programming/repair": "4D+2", "droid programming": "4D+2", "droid repair": "4D", "first aid": "5D", "repulsorlift repair": "4D+2", security: "6D+1", "space transports repair": "8D+2", "starfighter repair": "7D+1", "starship weapon repair": "6D+2" } }
    },
    specialAbilities: "Enhanced Senses: +2D to search and related Perception checks in low-light conditions. Location Sense: Cannot get lost in a previously visited place; +1D astrogation for planets visited before.",
    forcePoints: 1,
    characterPoints: 6,
    move: 10,
    equipment: "Blaster pistol (4D), comlink, datapad, protective goggles, tool kit",
    capsule: "Nofre Eels is the sister of Gelgelar Free Port's unofficial administrator, Loro Eels. She is a short Sullustan who wears a greasy work suit with the contents of a tool kit strapped to her utility belt. Nofre is friendly and drives her mechanics hard but rewards them well. She is fond of talking to starship captains about the intricacies of repair and is always interested in where they've come from. Her talkative manner is one way she collects information for her brother — she's quick to report any mention or signs of slaves and is always interested in news from other systems. Nofre keeps a database on her office computer of starships, including captains, repairs done on Gelgelar, modifications, weapons, and anything else of interest. This database helps her diagnose problems on ships which use the repair bay frequently. She offers discounts to regular customers.",
    source: "WEG40217 Platt's Starport Guide p.68"
  },
  {
    name: "Qulo Eels",
    species: "Sullustan",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Gelgelar Outfitters",
    affiliations: ["Eels Family", "Gelgelar Outfitters"],
    role: "General store owner & cargo buyer",
    type: "Sullustan Entrepreneur",
    stats: {
      DEXTERITY: { base: "3D", skills: { blaster: "4D" } },
      KNOWLEDGE: { base: "2D+2", skills: { "alien species": "4D+2", bureaucracy: "4D", business: "7D", cultures: "5D", languages: "5D+2", streetwise: "5D", value: "7D+2" } },
      MECHANICAL: { base: "3D+1", skills: { "repulsorlift operation": "4D+2" } },
      PERCEPTION: { base: "3D+1", skills: { bargain: "7D+1", persuasion: "6D+2" } },
      STRENGTH: { base: "2D+2", skills: { "climbing/jumping": "3D+2", lifting: "4D", stamina: "4D" } },
      TECHNICAL: { base: "3D", skills: { "armor repair": "3D+2", "computer programming/repair": "4D", "droid programming": "4D", "droid repair": "4D+2", "repulsorlift repair": "5D" } }
    },
    specialAbilities: "Enhanced Senses: +2D to search and related Perception checks in low-light conditions. Location Sense: Cannot get lost in a previously visited place; +1D astrogation for planets visited before.",
    forcePoints: 1,
    characterPoints: 8,
    move: 10,
    equipment: "Datapad",
    capsule: "Qulo Eels runs Gelgelar Outfitters and purchases all goods for his establishment. While he drives a hard bargain when purchasing goods from freighter captains, he tries to make all parties think they've made a good deal. He is concerned about Gelgelar's economic climate and knows if he charges too much, he'll drain credits from the local population. Qulo always has at least 10,000 credits on hand when making deals. If he's not in his office at the back of the store, he's out greeting starship captains of recently landed ships, seeing if they wish to sell him their cargo.",
    source: "WEG40217 Platt's Starport Guide p.70"
  },
  {
    name: "Slerog Fenn",
    species: "Rodian",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Fenn's Landing",
    affiliations: ["Fenn's Landing", "Independent Criminal"],
    role: "Criminal & rival docking platform operator",
    type: "Rodian Criminal",
    stats: {
      DEXTERITY: { base: "3D+1", skills: { blaster: "5D+2", dodge: "4D+1", "pick pocket": "6D" } },
      KNOWLEDGE: { base: "3D", skills: { bureaucracy: "4D+2", business: "4D", intimidation: "6D+1", streetwise: "5D+1", value: "6D" } },
      MECHANICAL: { base: "2D+2", skills: { "repulsorlift operation": "4D+2", "space transports": "4D", "starship gunnery": "5D+1" } },
      PERCEPTION: { base: "3D+2", skills: { bargain: "6D", command: "4D+2", con: "5D+2", persuasion: "4D+2", search: "5D", sneak: "5D+2" } },
      STRENGTH: { base: "3D+1", skills: { "climbing/jumping": "4D" } },
      TECHNICAL: { base: "2D", skills: { demolition: "3D+2", security: "5D" } }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 3,
    move: 10,
    equipment: "Credit pouch, datapad, heavy blaster pistol (5D)",
    capsule: "Slerog Fenn is a greedy Rodian who runs Fenn's Landing, a group of docking platforms away from the main starport facilities run by Loro Eels. He dresses in a greasy flight suit and always keeps his blaster handy. Fenn personally collects docking fees accompanied by two thugs. He can be rude and offensive, making patrons feel he's doing them a favor. Despite his lagging business, Fenn believes he is Loro Eels's chief competition. He hates the Sullustan and has foolishly vowed to drive Eels's operation into swamp mire. While his threats are often meaningless, Fenn is still a trigger-happy Rodian with a very short temper.",
    source: "WEG40217 Platt's Starport Guide p.63"
  },
  {
    name: "Thulls",
    species: "Ithorian",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Slippery Gelgelar Eel cantina",
    affiliations: ["Slippery Gelgelar Eel", "Independent"],
    role: "Bartender & information broker",
    type: "Ithorian Bartender",
    stats: {
      DEXTERITY: { base: "2D", skills: { blaster: "3D" } },
      KNOWLEDGE: { base: "4D", skills: { business: "4D+2", streetwise: "6D" } },
      PERCEPTION: { base: "4D", skills: { bargain: "5D", con: "6D+2", gambling: "4D+2" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 2,
    move: 10,
    equipment: "Blaster rifle (5D), grungy towel",
    capsule: "Thulls the Ithorian has had a constant cold since arriving on Gelgelar several years ago, mistaking it for a humid tropical planet instead of a cold wet one. He quietly notes who visits the bar, who they talk to, and picks up bits of conversation. If properly motivated with a handful of credits, he'll answer questions about what's going on in town. He's aware of what ships are in port, what cargoes they carry, and where they're headed. He keeps a blaster rifle under the bar for rowdy spacers. He gives swamp farmers drink discounts as regular customers, but raises prices when pilgrims or brash spacers walk in.",
    source: "WEG40217 Platt's Starport Guide p.71"
  },
  {
    name: "Brack",
    species: "Unknown",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Farmers' Landing Warehouses",
    affiliations: ["Farmers' Landing", "Independent"],
    role: "Vohis mold warehouse manager",
    type: "Warehouse Manager",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: { business: "4D+2", value: "5D" } },
      PERCEPTION: { base: "2D", skills: { bargain: "5D+2", con: "4D+1", persuasion: "3D+2" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Datapad, pocket computer",
    capsule: "Brack is an oily little womp rat who always peers up his long snout at the farmers and freighter captains who do business with him. He buys vohis mold from farmers for 100 credits per ton and tries to sell it to freighter captains for 200 credits per ton (will bargain down to 150 if warehouses are full). While he rarely cheats on deals, he always maximizes his profits. If stuck with a sour deal, Brack whines about it around town hoping to bruise the spacer's reputation and arouse Loro Eels's attention.",
    source: "WEG40217 Platt's Starport Guide p.65"
  },
  {
    name: "Vleen Argoe",
    species: "Unknown",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Shvash Gas Cooperative",
    affiliations: ["Shvash Gas Cooperative", "Independent"],
    role: "Shvash gas dealer",
    type: "Gas Dealer",
    stats: {
      DEXTERITY: { base: "2D", skills: { "pick pocket": "3D+2" } },
      KNOWLEDGE: { base: "2D", skills: { business: "3D" } },
      PERCEPTION: { base: "2D", skills: { bargain: "4D+1" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: { demolitions: "5D" } }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Mini-flamer, pack of hand-rolled cigarras",
    capsule: "Vleen runs the Shvash Gas Cooperative and barely manages to get by on the few credits she makes buying and selling shvash gas. She's an awful businesswoman, fond of sitting around her office all day smoking hand-rolled cigarras and setting small items on fire. She isn't terribly good at bargaining. If her tanks get too full, she burns a little off rather than turn away harvesters. She is fascinated by fire and sometimes distracted by the small flame from her mini-flamer when lighting a cigarra.",
    source: "WEG40217 Platt's Starport Guide p.66"
  },
  {
    name: "Varrik",
    species: "Human",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Fenn's Landing",
    affiliations: ["Fenn's Landing"],
    role: "Mechanic (burned out)",
    type: "Human Mechanic",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: {} },
      PERCEPTION: { base: "2D", skills: {} },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "3D", skills: { security: "4D", "space transports repair": "4D+2", "starship weapon repair": "4D" } }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 9,
    equipment: "Datapad, hold-out blaster (3D), toolkit",
    capsule: "Varrik is an old, burned-out Human mechanic retained by Slerog Fenn at Fenn's Landing. His repair services are usually double the normal cost, and replacement parts are rarely available — captains often wait up to 10 days for new parts to arrive.",
    source: "WEG40217 Platt's Starport Guide p.63"
  },
  {
    name: "Red Threxa",
    species: "Suiraon",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Red Threxa's Boarding House",
    affiliations: ["Red Threxa's Boarding House", "Independent"],
    role: "Boarding house owner",
    type: "Suiraon Innkeeper",
    stats: {
      DEXTERITY: { base: "2D", skills: { blaster: "3D+1" } },
      KNOWLEDGE: { base: "2D", skills: { bureaucracy: "3D+2", business: "4D", languages: "4D", streetwise: "3D+2" } },
      PERCEPTION: { base: "2D", skills: { bargain: "3D", persuasion: "3D+2" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Heavy blaster pistol (5D), reinforced credit box with 3,000 credits",
    capsule: "Red Threxa is a shifty lizard-like Suiraon who turned several prefab housing units he stole into Gelgelar's only motel. One of the boarding house's appeals is that it's one of the few dry buildings with a huge heating unit in the common room — the roof doesn't leak and patrons stay warm and dry. Rooms are sparse but at 15 credits a night, it's better than a starship bunk. Red keeps an eye on who comes and goes but cares little for their affairs. He keeps the heat generator pumped up high, creating a humid, foggy atmosphere. Red can be found behind his registration desk basking in the heat, keeping a watchful eye on his credit box. Some say he has no room — he just sleeps behind his desk.",
    source: "WEG40217 Platt's Starport Guide p.72"
  },
  {
    name: "Wise Man of Kooroo",
    species: "Human",
    system: "Gelgelar",
    location: "Gelgelar — Shrine of Kooroo",
    affiliations: ["Fellowship of Kooroo", "Force-Sensitive"],
    role: "Mystic & shrine keeper (former Jedi apprentice)",
    type: "Mystic",
    stats: {
      DEXTERITY: { base: "3D", skills: { "archaic guns": "4D", lightsaber: "7D", "melee combat": "3D+2", "melee parry": "3D+1" } },
      KNOWLEDGE: { base: "4D", skills: { "alien species": "6D+2", cultures: "5D", languages: "5D+2", "planetary systems": "4D+2", survival: "5D", willpower: "6D" } },
      MECHANICAL: { base: "2D", skills: { "archaic starship piloting": "5D", astrogation: "4D" } },
      PERCEPTION: { base: "4D", skills: { persuasion: "5D" } },
      STRENGTH: { base: "2D+1", skills: { stamina: "3D+2" } },
      TECHNICAL: { base: "2D+2", skills: { "droid programming": "4D", "droid repair": "3D+2", "first aid": "4D+2" } }
    },
    specialAbilities: "Force Skills: Sense 3D — Life Detection, Life Sense, Receptive Telepathy, Sense Force. Force-sensitive.",
    forcePoints: 3,
    characterPoints: 5,
    move: 8,
    equipment: "Cane, pipe",
    capsule: "The Wise Man of Kooroo has long since forgotten his name. His original name was Glovan Thule; some believe he was an apprenticed Jedi Knight. For reasons unknown, he fled to Gelgelar to live out his life in a damp shrine. He is now a doddering old man who sits on a pile of tattered animal skins, leaning on his cane and smoking a pipe. He doles out advice and philosophical sayings to visiting pilgrims who believe him to be a shaman of a long-forgotten faith. He depends on the goodness of visitors for food — in times of few pilgrims, Thulls the Ithorian brings him food from the Slippery Gelgelar Eel.",
    source: "WEG40217 Platt's Starport Guide p.73"
  },

  // ── GELGELAR FREE PORT — Generic NPC Templates ──
  {
    name: "Fenn's Security Goons",
    species: "Various aliens",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Fenn's Landing",
    affiliations: ["Fenn's Landing"],
    role: "Platform guards & petty thieves",
    type: "Generic — Thugs",
    stats: {
      DEXTERITY: { base: "3D", skills: { blaster: "4D+2" } },
      KNOWLEDGE: { base: "2D", skills: { intimidation: "3D", search: "3D+1" } },
      PERCEPTION: { base: "2D", skills: {} },
      STRENGTH: { base: "2D+2", skills: { brawling: "4D" } },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Heavy blaster pistol (5D)",
    capsule: "Fenn's security goons do a good job of protecting ships — they usually shoot anything that comes near them, including ships' crews. Their security duties often include breaking into ships while crews are in town, grabbing small items like a few credits or a hydrospanner. Luckily they're not smart enough to rummage through ships' computers.",
    source: "WEG40217 Platt's Starport Guide p.63"
  },
  {
    name: "Sullustan Mechanics",
    species: "Sullustan",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Nofre Repair Bay",
    affiliations: ["Eels Family", "Nofre Repair Bay"],
    role: "Starship repair technicians",
    type: "Generic — Mechanics",
    stats: {
      DEXTERITY: { base: "2D", skills: { blaster: "4D+1" } },
      KNOWLEDGE: { base: "2D", skills: { business: "3D+1", value: "3D" } },
      PERCEPTION: { base: "2D", skills: { bargain: "3D+2" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: { "repulsorlift repair": "5D+1", "space transports repair": "6D", "starfighter repair": "5D", "starship weapon repair": "5D+2" } }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Blaster pistol (4D), datapad, protective goggles, tool kit",
    capsule: "Nofre's mechanics are hard-working and dedicated to pleasing customers. At least six are working in the hangar bay at any time of day. All carry blaster pistols since Slerog Fenn's thugs occasionally break into the bay seeking spare parts or to sabotage repairs.",
    source: "WEG40217 Platt's Starport Guide p.68"
  },
  {
    name: "Gelgelar Outfitters Clerks",
    species: "Sullustan",
    system: "Gelgelar",
    location: "Gelgelar Free Port — Gelgelar Outfitters",
    affiliations: ["Eels Family", "Gelgelar Outfitters"],
    role: "Retail clerks",
    type: "Generic — Clerks",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: { business: "4D", languages: "4D+2", value: "5D" } },
      PERCEPTION: { base: "2D", skills: { bargain: "6D", persuasion: "5D+1" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Datapad",
    capsule: "The store clerks haggle over the price of every item — it gives them an opportunity to offer better deals and make customers feel they're getting a bargain. They are helpful in leading customers through the maze of bins and shelves. Customers left alone can take an hour to find items and sometimes get lost. Merchandise is marked up 10–25% to allow for haggling.",
    source: "WEG40217 Platt's Starport Guide p.69"
  },

  // ── KUAT PASSENGER PORT (WEG40217 Platt's Starport Guide p.38–56) ──
  {
    name: "Sergeant Reggis Thine",
    species: "Human",
    system: "Kuat",
    location: "Kuat Passenger Port",
    affiliations: ["Kuat Starport Security", "Imperial Administration"],
    role: "Security officer (sympathetic to free-traders)",
    type: "Security Officer",
    stats: {
      DEXTERITY: { base: "2D", skills: { blaster: "4D" } },
      KNOWLEDGE: { base: "2D", skills: { "law enforcement": "4D", streetwise: "4D+2" } },
      PERCEPTION: { base: "2D", skills: { investigation: "4D", persuasion: "4D" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Blaster pistol (4D), security uniform, comlink",
    capsule: "Sergeant Reggis Thine is a Kuat Passenger Port security officer who is helpful to free-traders navigating the station's complex clearance requirements.",
    source: "WEG40217 Platt's Starport Guide p.38"
  },
  {
    name: "Benni",
    species: "Unknown",
    system: "Kuat",
    location: "Kuat Passenger Port",
    affiliations: ["Independent", "Information Broker"],
    role: "Pack tracker & information broker",
    type: "Information Broker",
    stats: {
      DEXTERITY: { base: "2D", skills: { "pick pocket": "4D+2" } },
      KNOWLEDGE: { base: "2D", skills: { streetwise: "6D" } },
      PERCEPTION: { base: "2D", skills: { bargain: "5D", investigation: "5D+2", search: "5D" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Pack tracker gear",
    capsule: "Benni works the Kuat Passenger Port docking areas as a pack tracker and information broker. He charges 3 credits for hauling luggage and 25 to 50 credits for useful information about port operations, security patterns, and other travelers.",
    source: "WEG40217 Platt's Starport Guide p.38"
  },
  {
    name: "Captain Dorai",
    species: "Duros",
    system: "Kuat",
    location: "Kuat Passenger Port — Kuat Central Plaza",
    affiliations: ["Independent Pilot"],
    role: "Transport pilot & KDY stardock informant",
    type: "Transport Pilot",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: {} },
      PERCEPTION: { base: "2D", skills: {} },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: { "space transports": "5D", astrogation: "4D" } },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Comlink, datapad",
    capsule: "Captain Dorai is a Duros transport pilot who lives in a staff apartment in Kuat Central Plaza. He trades information about KDY stardock operations for galactic news from visiting spacers.",
    source: "WEG40217 Platt's Starport Guide p.38"
  },
  {
    name: "Benja Da'aapp",
    species: "Gruvian",
    system: "Kuat",
    location: "Kuat Passenger Port",
    affiliations: ["Gruvian Tourists"],
    role: "Tourist (useful for obtaining Core transit permits)",
    type: "Gruvian Tourist",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: { "alien species": "5D", cultures: "6D", "planetary systems": "6D+2" } },
      PERCEPTION: { base: "2D", skills: { persuasion: "6D" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "Gruvian physiology: Large green-skinned species with 4 arms, 8 eyestalks, and 2 mouths.",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Vacation holos (extensive collection), Core Worlds travel clearance documents",
    capsule: "Benja Da'aapp is one of two Gruvian tourists (along with Olaal) who frequent the Kuat Passenger Port. They are intensely friendly and have legitimate Core Worlds clearance, making them potentially useful for obtaining transit permits. However, any companion must endure hours of vacation holos.",
    source: "WEG40217 Platt's Starport Guide p.38"
  },
  {
    name: "Olaal Da'aapp",
    species: "Gruvian",
    system: "Kuat",
    location: "Kuat Passenger Port",
    affiliations: ["Gruvian Tourists"],
    role: "Tourist (useful for obtaining Core transit permits)",
    type: "Gruvian Tourist",
    stats: {
      DEXTERITY: { base: "2D", skills: {} },
      KNOWLEDGE: { base: "2D", skills: { "alien species": "5D", cultures: "6D", "planetary systems": "6D+2" } },
      PERCEPTION: { base: "2D", skills: { persuasion: "6D" } },
      STRENGTH: { base: "2D", skills: {} },
      MECHANICAL: { base: "2D", skills: {} },
      TECHNICAL: { base: "2D", skills: {} }
    },
    specialAbilities: "Gruvian physiology: Large green-skinned species with 4 arms, 8 eyestalks, and 2 mouths.",
    forcePoints: 0,
    characterPoints: 0,
    move: 10,
    equipment: "Vacation holos (extensive collection), Core Worlds travel clearance documents",
    capsule: "Olaal Da'aapp is one of two Gruvian tourists (along with Benja) who frequent the Kuat Passenger Port. They are intensely friendly and have legitimate Core Worlds clearance, making them potentially useful for obtaining transit permits. However, any companion must endure hours of vacation holos.",
    source: "WEG40217 Platt's Starport Guide p.38"
  },

  // ── PLATT OKEEFE (WEG40217 Platt's Starport Guide p.6) ──
  {
    name: "Platt Okeefe",
    species: "Human",
    system: "Varies",
    location: "Varies (based on Brentaal, frequents Gelgelar Free Port and others)",
    affiliations: ["Independent Smuggler"],
    role: "Smuggler & entrepreneur",
    type: "Smuggler",
    stats: {
      DEXTERITY: { base: "3D+1", skills: { blaster: "6D+1", dodge: "5D", running: "5D+1" } },
      KNOWLEDGE: { base: "2D+1", skills: { "alien species": "4D+1", languages: "4D", "languages: Sullustan": "6D", "planetary systems": "8D", streetwise: "6D" } },
      MECHANICAL: { base: "3D+2", skills: { astrogation: "5D", sensors: "4D+2", "space transports": "6D+2", "starship gunnery": "5D" } },
      PERCEPTION: { base: "3D", skills: { bargain: "5D", con: "4D", sneak: "4D+2" } },
      STRENGTH: { base: "3D", skills: { brawling: "5D", "climbing/jumping": "4D+2", stamina: "4D" } },
      TECHNICAL: { base: "2D+2", skills: { "space transports repair": "5D+2", "starship weapon repair": "4D" } }
    },
    specialAbilities: "",
    forcePoints: 5,
    characterPoints: 12,
    move: 10,
    equipment: "Comlink, datapad, heavy blaster pistol (5D). Often accompanied by co-pilots including the Twi'lek gunrunner Tru'eb Cholakk and a Sullustan from the Suuliem family. ◆ THE LAST CHANCE — Modified CEC YT-1300 Transport. Scale: Starfighter. Length: 27m. Crew: 1–2 (can coordinate), Gunners: 2. Passengers: 6. Cargo: 100 metric tons. Consumables: 2 months. Hyperdrive: x1 (Backup: x10). Nav Computer: Yes. Maneuverability: 2D. Space: 4. Atmosphere: 480; 800 kmh. Hull: 4D+2. Shields: 2D. Sensors — Passive: 10/0D, Scan: 25/1D, Search: 40/2D, Focus: 2/3D. Weapons: 2 Quad Laser Cannons (turret, Fire Control 2D, Space Range 1-3/12/25, Atmo 100-300/1.2/2.5 km, Damage 6D), Concussion Missile Tube (front, Fire Control 2D, Space Range 1/3/7, Atmo 50-100/300/700, Damage 9D). The crew lounge is fancifully decorated with collectibles from her journeys, not all lawfully acquired.",
    capsule: "Platt Okeefe considers herself a legendary entrepreneur who has been causing trouble for the Empire, running legal and not-so-legal cargoes, and getting into trouble throughout the galaxy for several years. She always loved space travel — growing up on Brentaal, she spent her afternoons at the starport watching freighters. On her twelfth birthday she ran away and signed on as a cabin steward aboard a Sullustan starliner. She later joined a tramp freighter crew plying the Anarid Cluster and has since gone through different ships like clothing goes through styles. During her extensive travels she has recorded everything she could about the spacefaring life and cultivated a network of contacts so her information on systems and starports is accurate. Her most remarkable features are her silvery white hair streaming down her back (often tied with a silver and red striped sash) and her bright outfit — white blouse with red pants, boots, and vest. Her heavy blaster is always at her side. She enjoys stunning unsuspecting spacer jocks with her girlish smile. Platt is easygoing and has great concern for her fellow smugglers, offering help whenever it won't jeopardize her own affairs.",
    source: "WEG40217 Platt's Starport Guide p.6"
  },

  // ── PORT HAVEN (WEG40217 Platt's Starport Guide p.20–35) ──
  {
    name: "Hallomar",
    species: "Human",
    system: "Whendyll",
    location: "Port Haven",
    affiliations: ["Port Haven Administration", "Independent"],
    role: "Hunter & impromptu governor of Port Haven",
    type: "Hunter",
    stats: {
      DEXTERITY: { base: "4D", skills: { "archaic guns": "8D+2", blaster: "7D", "blaster: blaster rifle": "9D", "brawling parry": "7D+2", dodge: "8D", "melee combat": "7D", "melee parry": "6D+2", running: "7D+1", "thrown weapon": "7D" } },
      KNOWLEDGE: { base: "2D+2", skills: { intimidation: "5D", "survival: jungle": "9D+2", willpower: "7D" } },
      MECHANICAL: { base: "2D+2", skills: { "beast riding": "5D+2" } },
      PERCEPTION: { base: "3D", skills: { search: "6D", "search: tracking": "8D+2", "sneak: jungle": "8D" } },
      STRENGTH: { base: "3D+2", skills: { brawling: "8D", "climbing/jumping": "6D+1", lifting: "5D+2", stamina: "7D", swimming: "6D" } },
      TECHNICAL: { base: "2D", skills: { "archaic gun repair": "5D", "first aid": "7D+2" } }
    },
    specialAbilities: "",
    forcePoints: 5,
    characterPoints: 15,
    move: 10,
    equipment: "Ammo bandolier, animal hide clothing, large knife (STR+1D+2), leather satchel, needle-shell rifle (5D+2), pipe, wood axe (STR+2D)",
    capsule: "Few smugglers who visit Port Haven know of Hallomar's true origins. Some say he was an outlaw who came to escape some unknown crime, while others believe he's the last survivor from the group of colonists who tried to settle the planet. Whatever his origins, Hallomar is a rugged survivor who carves his simple life from the jungles of Port Haven. He stands just over two meters tall, sporting a long unkempt brown beard and a nest of shaggy hair, wearing piles of animal skin clothing over the vestiges of a tattered tunic. This rugged mountain of a man is the impromptu governor of Port Haven. He seldom talks and when he does, he has a deep voice punctuated by grunts and huffs. He cares little for visitors as long as they don't raise trouble. He spends half his time hunting immense jungle beasts with his ancient oversized needle-shell rifle, and the rest butchering prey, curing skins, and smoking meat in his curing tent. Evenings are spent brooding in a dark corner of Haven's Water, drinking frothy ale and smoking his hand-carved pipe. He rarely gives away more than 10 skins at a time (worth 50–200 credits each depending on market). His smoked meat strips are tasty if you like chewing on something with the consistency of spacer's gloves — sold as novelty for 10–50 credits, or up to 100 credits to specialty restaurants.",
    source: "WEG40217 Platt's Starport Guide p.30"
  },
  {
    name: "Mister Mxil",
    species: "Mon Calamari",
    system: "Whendyll",
    location: "Port Haven — Haven's Water tavern",
    affiliations: ["Haven's Water", "Independent", "Mon Calamari Refugee"],
    role: "Tavern host & bartender",
    type: "Mon Calamari Bartender",
    stats: {
      DEXTERITY: { base: "3D", skills: { dodge: "4D+2" } },
      KNOWLEDGE: { base: "4D", skills: { "alien species": "6D+2", cultures: "6D", "drink mixicology": "9D", languages: "5D", "planetary systems": "6D", "survival: jungle": "8D" } },
      MECHANICAL: { base: "2D", skills: {} },
      PERCEPTION: { base: "3D", skills: { persuasion: "5D", search: "6D+1", sneak: "4D+1" } },
      STRENGTH: { base: "2D+1", skills: { stamina: "4D", swimming: "6D+1" } },
      TECHNICAL: { base: "3D+2", skills: { "first aid": "6D+2" } }
    },
    specialAbilities: "Moist Environments: In moist environments (such as Port Haven), Mon Calamari receive +1D bonus to all Dexterity, Perception, and Strength attribute and skill checks.",
    forcePoints: 1,
    characterPoints: 9,
    move: 10,
    equipment: "Apron, worn tunic",
    capsule: "A refugee from his homeworld of Calamari, Mister Mxil is the host of all visitors to Haven's Water, the only tavern in Port Haven. He was formerly a chief steward aboard the Mon Calamari starliner Kuari Princess, responsible for all meals, bars, and culinary satisfaction of passengers. When he ran into trouble speaking out about the Empire enslaving his homeworld, he quickly became an Imperial fugitive and found sanctuary in Port Haven. After fixing up one of the larger structures and learning the ways of the jungle with Hallomar's help, he opened Haven's Water to visiting spacers. He serves natural drinks brewed, distilled, and steeped from jungle ingredients — ale from beans and bark, liquor from fruits, tea from dried herbs, leaves, and flower petals. He cooks spicy stew and tasty roasts served with jungle fruits, tubers, and vegetables, using meat supplied by Hallomar. All food and drink is offered as a gift of hospitality. Occasionally he gifts skins of Haven water from a nearby jungle spring, worth up to 40 credits. A red-and-green-dappled Mon Calamari in a tattered service tunic and apron, he lives on a hammock in the back room among hanging herbs and leaves.",
    source: "WEG40217 Platt's Starport Guide p.32"
  }
];
